"use client";
import {useState,type FormEvent} from "react";
import {ArtistPortalShell} from "../../artist-components";
import {useLanguage} from "../../i18n/language-provider";

export default function ArtistContactPage(){
  const{locale}=useLanguage();
  const[name,setName]=useState("");
  const[email,setEmail]=useState("");
  const[subject,setSubject]=useState("");
  const[message,setMessage]=useState("");
  const translations={
    en:{kicker:"MOCIFY SUPPORT",title:"Contact",intro:"Have a question about your artist account, releases, promotion or MOCIFY Studio? Send us a message.",name:"Name",email:"Email",subject:"Subject",message:"Message",send:"Send message",back:"Back to Dashboard",note:"Your message will open in your email app, ready to send to MOCIFY Support."},
    nl:{kicker:"MOCIFY SUPPORT",title:"Contact",intro:"Heb je een vraag over je artiestenaccount, releases, promotie of MOCIFY Studio? Stuur ons een bericht.",name:"Naam",email:"E-mail",subject:"Onderwerp",message:"Bericht",send:"Bericht versturen",back:"Terug naar Dashboard",note:"Je bericht wordt geopend in je e-mailapp, klaar om naar MOCIFY Support te versturen."},
    ro:{kicker:"MOCIFY SUPPORT",title:"Contact",intro:"Ai o întrebare despre contul de artist, lansări, promovare sau MOCIFY Studio? Trimite-ne un mesaj.",name:"Nume",email:"E-mail",subject:"Subiect",message:"Mesaj",send:"Trimite mesaj",back:"Înapoi la Dashboard",note:"Mesajul se va deschide în aplicația de e-mail, pregătit pentru MOCIFY Support."},
    de:{kicker:"MOCIFY SUPPORT",title:"Kontakt",intro:"Fragen zu Künstlerkonto, Releases, Promotion oder MOCIFY Studio? Schreib uns.",name:"Name",email:"E-Mail",subject:"Betreff",message:"Nachricht",send:"Nachricht senden",back:"Zurück zum Dashboard",note:"Die Nachricht wird in deiner E-Mail-App geöffnet und kann an den MOCIFY Support gesendet werden."},
    fr:{kicker:"MOCIFY SUPPORT",title:"Contact",intro:"Une question sur votre compte artiste, vos sorties, la promotion ou MOCIFY Studio ? Envoyez-nous un message.",name:"Nom",email:"E-mail",subject:"Objet",message:"Message",send:"Envoyer",back:"Retour au Dashboard",note:"Votre message s’ouvrira dans votre application e-mail, prêt à être envoyé au support MOCIFY."},
    es:{kicker:"MOCIFY SUPPORT",title:"Contacto",intro:"¿Tienes una pregunta sobre tu cuenta de artista, lanzamientos, promoción o MOCIFY Studio? Envíanos un mensaje.",name:"Nombre",email:"Correo",subject:"Asunto",message:"Mensaje",send:"Enviar mensaje",back:"Volver al panel",note:"Tu mensaje se abrirá en tu aplicación de correo, listo para enviarlo a MOCIFY Support."},
    it:{kicker:"MOCIFY SUPPORT",title:"Contatti",intro:"Hai una domanda sul tuo account artista, release, promozione o MOCIFY Studio? Scrivici.",name:"Nome",email:"E-mail",subject:"Oggetto",message:"Messaggio",send:"Invia messaggio",back:"Torna alla Dashboard",note:"Il messaggio si aprirà nella tua app e-mail, pronto per essere inviato al supporto MOCIFY."},
    pt:{kicker:"MOCIFY SUPPORT",title:"Contacto",intro:"Tens uma pergunta sobre a conta de artista, lançamentos, promoção ou MOCIFY Studio? Envia-nos uma mensagem.",name:"Nome",email:"E-mail",subject:"Assunto",message:"Mensagem",send:"Enviar mensagem",back:"Voltar ao Dashboard",note:"A mensagem será aberta na tua aplicação de e-mail, pronta para enviar ao suporte MOCIFY."},
    pl:{kicker:"MOCIFY SUPPORT",title:"Kontakt",intro:"Masz pytanie o konto artysty, wydania, promocję lub MOCIFY Studio? Napisz do nas.",name:"Imię",email:"E-mail",subject:"Temat",message:"Wiadomość",send:"Wyślij wiadomość",back:"Wróć do panelu",note:"Wiadomość otworzy się w aplikacji pocztowej, gotowa do wysłania do MOCIFY Support."},
    tr:{kicker:"MOCIFY SUPPORT",title:"İletişim",intro:"Sanatçı hesabın, yayınlar, tanıtım veya MOCIFY Studio hakkında sorunun mu var? Bize mesaj gönder.",name:"Ad",email:"E-posta",subject:"Konu",message:"Mesaj",send:"Mesaj gönder",back:"Panele dön",note:"Mesajın e-posta uygulamanda açılır ve MOCIFY Support’a gönderilmeye hazır olur."},
    id:{kicker:"MOCIFY SUPPORT",title:"Kontak",intro:"Ada pertanyaan tentang akun artis, rilisan, promosi, atau MOCIFY Studio? Kirim pesan kepada kami.",name:"Nama",email:"Email",subject:"Subjek",message:"Pesan",send:"Kirim pesan",back:"Kembali ke Dashboard",note:"Pesan akan dibuka di aplikasi email dan siap dikirim ke MOCIFY Support."},
    ja:{kicker:"MOCIFY SUPPORT",title:"お問い合わせ",intro:"アーティストアカウント、リリース、プロモーション、MOCIFY Studioについて質問がありますか？",name:"名前",email:"メール",subject:"件名",message:"メッセージ",send:"送信",back:"ダッシュボードへ戻る",note:"メッセージはメールアプリで開き、MOCIFY Supportへ送信できます。"},
    ko:{kicker:"MOCIFY SUPPORT",title:"문의",intro:"아티스트 계정, 릴리스, 프로모션 또는 MOCIFY Studio에 대한 질문이 있나요? 메시지를 보내주세요.",name:"이름",email:"이메일",subject:"제목",message:"메시지",send:"메시지 보내기",back:"대시보드로 돌아가기",note:"메시지가 이메일 앱에서 열리며 MOCIFY Support로 보낼 준비가 됩니다."},
    hi:{kicker:"MOCIFY SUPPORT",title:"संपर्क",intro:"कलाकार खाते, रिलीज़, प्रमोशन या MOCIFY Studio के बारे में सवाल है? हमें संदेश भेजें।",name:"नाम",email:"ईमेल",subject:"विषय",message:"संदेश",send:"संदेश भेजें",back:"डैशबोर्ड पर वापस",note:"आपका संदेश ईमेल ऐप में खुलेगा और MOCIFY Support को भेजने के लिए तैयार रहेगा।"}
  } as const;
  const t=translations[locale]??translations.en;
  const submit=(e:FormEvent)=>{e.preventDefault();const mailSubject=encodeURIComponent(subject||"MOCIFY Artist Portal contact");const body=encodeURIComponent(`Name: ${name}\nEmail: ${email}\n\n${message}`);window.location.href=`mailto:contact@mocify.ai?subject=${mailSubject}&body=${body}`};
  return <ArtistPortalShell active="studio"><section className="artist-contact-page"><div className="artist-contact-wrap"><div className="artist-contact-intro"><p>{t.kicker}</p><h1>{t.title}</h1><span>{t.intro}</span><a href="/dashboard">← {t.back}</a></div><form className="artist-contact-form" onSubmit={submit}><div className="artist-contact-row"><label><span>{t.name}</span><input required value={name} onChange={e=>setName(e.target.value)}/></label><label><span>{t.email}</span><input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label></div><label><span>{t.subject}</span><input value={subject} onChange={e=>setSubject(e.target.value)}/></label><label><span>{t.message}</span><textarea required rows={7} value={message} onChange={e=>setMessage(e.target.value)}/></label><button type="submit">{t.send} →</button><small>{t.note}</small></form></div></section></ArtistPortalShell>
}