"use client";
import Link from "next/link";
import {useMemo,useRef,useState} from "react";
import {Shell} from "../components";
import SectionHero from "../section-hero";
import {countryGenreMap,countryPlaylists,genrePlaylists,regionalGenres,releases} from "../data";
import {useListenerPlayer} from "../listener-player";
import {useLanguage} from "../i18n/language-provider";


const playlistCopy={
 en:{kicker:"MOCIFY PLAYLISTS",titleA:"Charts &",titleB:"genres.",intro:"Choose a country for its chart, major genres and local music styles.",select:"SELECT COUNTRY",market:"SELECTED MARKET",search:"Search playlists, genres or styles...",searchAria:"Search playlists",personal:"Personal playlists",browse:"Browse playlists",international:"INTERNATIONAL CHART",countryChart:"COUNTRY CHART",genre:"GENRE",streamed:(n:number)=>"The "+n+" most streamed tracks in this market.",play:"Play",open:"Open playlist",empty:"No releases yet.",emptySub:"This playlist will fill as matching music is released.",none:(q:string)=>'No playlists match “'+q+'”.',count:(n:number)=>n+" playlists"},
 nl:{kicker:"MOCIFY PLAYLISTS",titleA:"Hitlijsten &",titleB:"genres.",intro:"Kies een land voor de hitlijsten, belangrijkste genres en lokale muziekstijlen.",select:"KIES LAND",market:"GESELECTEERDE MARKT",search:"Zoek playlists, genres of stijlen...",searchAria:"Zoek playlists",personal:"Persoonlijke playlists",browse:"Bekijk playlists",international:"INTERNATIONALE HITLIJST",countryChart:"LANDENHITLIJST",genre:"GENRE",streamed:(n:number)=>"De "+n+" meest gestreamde tracks in deze markt.",play:"Speel",open:"Open playlist",empty:"Nog geen releases.",emptySub:"Deze playlist wordt gevuld zodra passende muziek verschijnt.",none:(q:string)=>'Geen playlists gevonden voor “'+q+'”.',count:(n:number)=>n+" playlists"},
 ro:{kicker:"PLAYLISTURI MOCIFY",titleA:"Topuri &",titleB:"genuri.",intro:"Alege o țară pentru topuri, genuri principale și stiluri muzicale locale.",select:"ALEGE ȚARA",market:"PIAȚĂ SELECTATĂ",search:"Caută playlisturi, genuri sau stiluri...",searchAria:"Caută playlisturi",personal:"Playlisturile mele",browse:"Explorează playlisturi",international:"TOP INTERNAȚIONAL",countryChart:"TOP NAȚIONAL",genre:"GEN",streamed:(n:number)=>"Cele mai ascultate "+n+" piese din această piață.",play:"Redă",open:"Deschide playlistul",empty:"Încă nu sunt lansări.",emptySub:"Playlistul se va completa pe măsură ce apare muzică potrivită.",none:(q:string)=>'Niciun playlist pentru „'+q+'”.',count:(n:number)=>n+" playlisturi"},
 de:{kicker:"MOCIFY PLAYLISTS",titleA:"Charts &",titleB:"Genres.",intro:"Wähle ein Land für Charts, wichtige Genres und lokale Musikstile.",select:"LAND WÄHLEN",market:"AUSGEWÄHLTER MARKT",search:"Playlists, Genres oder Stile suchen...",searchAria:"Playlists suchen",personal:"Eigene Playlists",browse:"Playlists entdecken",international:"INTERNATIONALE CHARTS",countryChart:"LANDESCHARTS",genre:"GENRE",streamed:(n:number)=>"Die "+n+" meistgestreamten Tracks in diesem Markt.",play:"Abspielen",open:"Playlist öffnen",empty:"Noch keine Veröffentlichungen.",emptySub:"Diese Playlist füllt sich mit passenden Veröffentlichungen.",none:(q:string)=>'Keine Playlists für „'+q+'“.',count:(n:number)=>n+" Playlists"},
 fr:{kicker:"PLAYLISTS MOCIFY",titleA:"Classements &",titleB:"genres.",intro:"Choisissez un pays pour ses classements, genres majeurs et styles locaux.",select:"CHOISIR UN PAYS",market:"MARCHÉ SÉLECTIONNÉ",search:"Rechercher playlists, genres ou styles...",searchAria:"Rechercher des playlists",personal:"Playlists personnelles",browse:"Parcourir les playlists",international:"CLASSEMENT INTERNATIONAL",countryChart:"CLASSEMENT NATIONAL",genre:"GENRE",streamed:(n:number)=>"Les "+n+" titres les plus écoutés sur ce marché.",play:"Lire",open:"Ouvrir la playlist",empty:"Aucune sortie pour le moment.",emptySub:"Cette playlist se remplira avec les sorties correspondantes.",none:(q:string)=>'Aucune playlist pour « '+q+' ».',count:(n:number)=>n+" playlists"},
 es:{kicker:"PLAYLISTS MOCIFY",titleA:"Listas &",titleB:"géneros.",intro:"Elige un país para ver sus listas, géneros principales y estilos locales.",select:"ELEGIR PAÍS",market:"MERCADO SELECCIONADO",search:"Buscar playlists, géneros o estilos...",searchAria:"Buscar playlists",personal:"Playlists personales",browse:"Explorar playlists",international:"LISTA INTERNACIONAL",countryChart:"LISTA NACIONAL",genre:"GÉNERO",streamed:(n:number)=>"Las "+n+" canciones más escuchadas de este mercado.",play:"Reproducir",open:"Abrir playlist",empty:"Aún no hay lanzamientos.",emptySub:"Esta playlist se llenará cuando haya música que coincida.",none:(q:string)=>'No hay playlists para «'+q+'».',count:(n:number)=>n+" playlists"},
 it:{kicker:"PLAYLIST MOCIFY",titleA:"Classifiche &",titleB:"generi.",intro:"Scegli un paese per classifiche, generi principali e stili musicali locali.",select:"SCEGLI PAESE",market:"MERCATO SELEZIONATO",search:"Cerca playlist, generi o stili...",searchAria:"Cerca playlist",personal:"Playlist personali",browse:"Esplora playlist",international:"CLASSIFICA INTERNAZIONALE",countryChart:"CLASSIFICA NAZIONALE",genre:"GENERE",streamed:(n:number)=>"I "+n+" brani più ascoltati in questo mercato.",play:"Riproduci",open:"Apri playlist",empty:"Nessuna uscita al momento.",emptySub:"La playlist si riempirà con le nuove uscite corrispondenti.",none:(q:string)=>'Nessuna playlist per “'+q+'”.',count:(n:number)=>n+" playlist"},
 pt:{kicker:"PLAYLISTS MOCIFY",titleA:"Tabelas &",titleB:"géneros.",intro:"Escolha um país para ver tabelas, géneros principais e estilos locais.",select:"ESCOLHER PAÍS",market:"MERCADO SELECIONADO",search:"Pesquisar playlists, géneros ou estilos...",searchAria:"Pesquisar playlists",personal:"Playlists pessoais",browse:"Explorar playlists",international:"TABELA INTERNACIONAL",countryChart:"TABELA NACIONAL",genre:"GÉNERO",streamed:(n:number)=>"As "+n+" faixas mais ouvidas neste mercado.",play:"Reproduzir",open:"Abrir playlist",empty:"Ainda não há lançamentos.",emptySub:"Esta playlist será preenchida com lançamentos correspondentes.",none:(q:string)=>'Nenhuma playlist para “'+q+'”.',count:(n:number)=>n+" playlists"},
 pl:{kicker:"PLAYLISTY MOCIFY",titleA:"Listy &",titleB:"gatunki.",intro:"Wybierz kraj, aby zobaczyć listy, główne gatunki i lokalne style muzyczne.",select:"WYBIERZ KRAJ",market:"WYBRANY RYNEK",search:"Szukaj playlist, gatunków lub stylów...",searchAria:"Szukaj playlist",personal:"Własne playlisty",browse:"Przeglądaj playlisty",international:"LISTA MIĘDZYNARODOWA",countryChart:"LISTA KRAJOWA",genre:"GATUNEK",streamed:(n:number)=>n+" najczęściej odtwarzanych utworów na tym rynku.",play:"Odtwórz",open:"Otwórz playlistę",empty:"Brak wydań.",emptySub:"Playlista zapełni się, gdy pojawi się pasująca muzyka.",none:(q:string)=>'Brak playlist dla „'+q+'”.',count:(n:number)=>n+" playlist"},
 tr:{kicker:"MOCIFY ÇALMA LİSTELERİ",titleA:"Listeler &",titleB:"türler.",intro:"Listeler, ana türler ve yerel müzik stilleri için bir ülke seçin.",select:"ÜLKE SEÇ",market:"SEÇİLEN PAZAR",search:"Çalma listesi, tür veya stil ara...",searchAria:"Çalma listesi ara",personal:"Kişisel listeler",browse:"Listelere göz at",international:"ULUSLARARASI LİSTE",countryChart:"ÜLKE LİSTESİ",genre:"TÜR",streamed:(n:number)=>"Bu pazarda en çok dinlenen "+n+" parça.",play:"Oynat",open:"Listeyi aç",empty:"Henüz yayın yok.",emptySub:"Uygun müzik yayınlandıkça bu liste dolacak.",none:(q:string)=>'“'+q+'” için liste yok.',count:(n:number)=>n+" liste"},
 id:{kicker:"PLAYLIST MOCIFY",titleA:"Tangga lagu &",titleB:"genre.",intro:"Pilih negara untuk tangga lagu, genre utama, dan gaya musik lokal.",select:"PILIH NEGARA",market:"PASAR TERPILIH",search:"Cari playlist, genre, atau gaya...",searchAria:"Cari playlist",personal:"Playlist pribadi",browse:"Jelajahi playlist",international:"TANGGA INTERNASIONAL",countryChart:"TANGGA NEGARA",genre:"GENRE",streamed:(n:number)=>n+" lagu paling banyak diputar di pasar ini.",play:"Putar",open:"Buka playlist",empty:"Belum ada rilisan.",emptySub:"Playlist ini akan terisi saat musik yang sesuai dirilis.",none:(q:string)=>'Tidak ada playlist untuk “'+q+'”.',count:(n:number)=>n+" playlist"},
 ja:{kicker:"MOCIFY プレイリスト",titleA:"チャート＆",titleB:"ジャンル。",intro:"国を選択して、チャート、主要ジャンル、ローカル音楽スタイルをチェック。",select:"国を選択",market:"選択中のマーケット",search:"プレイリスト、ジャンル、スタイルを検索...",searchAria:"プレイリストを検索",personal:"マイプレイリスト",browse:"プレイリストを見る",international:"インターナショナルチャート",countryChart:"国内チャート",genre:"ジャンル",streamed:(n:number)=>"このマーケットで最も再生されている"+n+"曲。",play:"再生",open:"プレイリストを開く",empty:"まだリリースがありません。",emptySub:"対象の楽曲がリリースされると、このプレイリストに追加されます。",none:(q:string)=>'「'+q+'」に一致するプレイリストはありません。',count:(n:number)=>n+" プレイリスト"},
 ko:{kicker:"MOCIFY 플레이리스트",titleA:"차트 &",titleB:"장르.",intro:"국가를 선택해 차트, 주요 장르와 현지 음악 스타일을 확인하세요.",select:"국가 선택",market:"선택한 마켓",search:"플레이리스트, 장르 또는 스타일 검색...",searchAria:"플레이리스트 검색",personal:"내 플레이리스트",browse:"플레이리스트 둘러보기",international:"인터내셔널 차트",countryChart:"국가 차트",genre:"장르",streamed:(n:number)=>"이 마켓에서 가장 많이 재생된 "+n+"곡.",play:"재생",open:"플레이리스트 열기",empty:"아직 발매곡이 없습니다.",emptySub:"해당 음악이 발매되면 이 플레이리스트가 채워집니다.",none:(q:string)=>'“'+q+'”에 맞는 플레이리스트가 없습니다.',count:(n:number)=>n+"개 플레이리스트"},
 hi:{kicker:"MOCIFY प्लेलिस्ट",titleA:"चार्ट और",titleB:"जॉनर।",intro:"चार्ट, प्रमुख जॉनर और स्थानीय संगीत शैलियों के लिए देश चुनें।",select:"देश चुनें",market:"चुना हुआ बाज़ार",search:"प्लेलिस्ट, जॉनर या स्टाइल खोजें...",searchAria:"प्लेलिस्ट खोजें",personal:"निजी प्लेलिस्ट",browse:"प्लेलिस्ट देखें",international:"अंतरराष्ट्रीय चार्ट",countryChart:"देश चार्ट",genre:"जॉनर",streamed:(n:number)=>"इस बाज़ार के "+n+" सबसे अधिक स्ट्रीम किए गए ट्रैक।",play:"चलाएँ",open:"प्लेलिस्ट खोलें",empty:"अभी कोई रिलीज़ नहीं।",emptySub:"मिलता-जुलता संगीत रिलीज़ होने पर यह प्लेलिस्ट भर जाएगी।",none:(q:string)=>'“'+q+'” से मेल खाने वाली प्लेलिस्ट नहीं मिली।',count:(n:number)=>n+" प्लेलिस्ट"}
} as const;

const genreNames:Record<string,Record<string,string>>={
 en:{pop:"Pop","hip-hop-rap":"Hip-Hop / Rap",rnb:"R&B",rock:"Rock","dance-electronic":"Dance / Electronic",house:"House",techno:"Techno",trap:"Trap",jazz:"Jazz",classical:"Classical",reggae:"Reggae",latin:"Latin",metal:"Metal",punk:"Punk","romanian-folk":"Romanian Folk","french-house":"French House","varietes-francaises":"French Popular Music","drum-bass":"Drum & Bass",garage:"UK Garage",britpop:"Britpop",folk:"British Folk",country:"Country",blues:"Blues",gospel:"Gospel",soul:"Soul",funk:"Funk",bluegrass:"Bluegrass"},
 nl:{pop:"Pop","hip-hop-rap":"Hip-Hop / Rap",rnb:"R&B",rock:"Rock","dance-electronic":"Dance / Elektronisch",house:"House",techno:"Techno",trap:"Trap",jazz:"Jazz",classical:"Klassiek",reggae:"Reggae",latin:"Latin",metal:"Metal",punk:"Punk","romanian-folk":"Roemeense folk","french-house":"Franse house","varietes-francaises":"Franse populaire muziek","drum-bass":"Drum & Bass",garage:"UK Garage",folk:"Britse folk",country:"Country",blues:"Blues",gospel:"Gospel",soul:"Soul",funk:"Funk"},
 ro:{pop:"Pop","hip-hop-rap":"Hip-Hop / Rap",rnb:"R&B",rock:"Rock","dance-electronic":"Dance / Electronică",house:"House",techno:"Techno",trap:"Trap",jazz:"Jazz",classical:"Clasică",reggae:"Reggae",latin:"Latin",metal:"Metal",punk:"Punk","romanian-folk":"Folclor românesc","french-house":"House francez","varietes-francaises":"Muzică populară franceză","drum-bass":"Drum & Bass",garage:"UK Garage",folk:"Folk britanic",country:"Country",blues:"Blues",gospel:"Gospel",soul:"Soul",funk:"Funk"},
 de:{pop:"Pop","hip-hop-rap":"Hip-Hop / Rap",rnb:"R&B",rock:"Rock","dance-electronic":"Dance / Elektronisch",house:"House",techno:"Techno",trap:"Trap",jazz:"Jazz",classical:"Klassik",reggae:"Reggae",latin:"Latin",metal:"Metal",punk:"Punk","romanian-folk":"Rumänische Folklore","french-house":"French House","varietes-francaises":"Französische Unterhaltungsmusik","drum-bass":"Drum & Bass",garage:"UK Garage",folk:"Britischer Folk",country:"Country",blues:"Blues",gospel:"Gospel",soul:"Soul",funk:"Funk"},
 fr:{pop:"Pop","hip-hop-rap":"Hip-Hop / Rap",rnb:"R&B",rock:"Rock","dance-electronic":"Dance / Électronique",house:"House",techno:"Techno",trap:"Trap",jazz:"Jazz",classical:"Classique",reggae:"Reggae",latin:"Latino",metal:"Metal",punk:"Punk","romanian-folk":"Folk roumain","french-house":"House française","varietes-francaises":"Variétés françaises","drum-bass":"Drum & Bass",garage:"UK Garage",folk:"Folk britannique",country:"Country",blues:"Blues",gospel:"Gospel",soul:"Soul",funk:"Funk"},
 es:{pop:"Pop","hip-hop-rap":"Hip-Hop / Rap",rnb:"R&B",rock:"Rock","dance-electronic":"Dance / Electrónica",house:"House",techno:"Techno",trap:"Trap",jazz:"Jazz",classical:"Clásica",reggae:"Reggae",latin:"Latina",metal:"Metal",punk:"Punk","romanian-folk":"Folk rumano","french-house":"House francés","varietes-francaises":"Música popular francesa","drum-bass":"Drum & Bass",garage:"UK Garage",folk:"Folk británico",country:"Country",blues:"Blues",gospel:"Góspel",soul:"Soul",funk:"Funk"},
 it:{pop:"Pop","hip-hop-rap":"Hip-Hop / Rap",rnb:"R&B",rock:"Rock","dance-electronic":"Dance / Elettronica",house:"House",techno:"Techno",trap:"Trap",jazz:"Jazz",classical:"Classica",reggae:"Reggae",latin:"Latina",metal:"Metal",punk:"Punk","romanian-folk":"Folk rumeno","french-house":"House francese","varietes-francaises":"Musica popolare francese","drum-bass":"Drum & Bass",garage:"UK Garage",folk:"Folk britannico",country:"Country",blues:"Blues",gospel:"Gospel",soul:"Soul",funk:"Funk"},
 pt:{pop:"Pop","hip-hop-rap":"Hip-Hop / Rap",rnb:"R&B",rock:"Rock","dance-electronic":"Dance / Eletrónica",house:"House",techno:"Techno",trap:"Trap",jazz:"Jazz",classical:"Clássica",reggae:"Reggae",latin:"Latina",metal:"Metal",punk:"Punk","romanian-folk":"Folk romeno","french-house":"House francesa","varietes-francaises":"Música popular francesa","drum-bass":"Drum & Bass",garage:"UK Garage",folk:"Folk britânico",country:"Country",blues:"Blues",gospel:"Gospel",soul:"Soul",funk:"Funk"},
 pl:{pop:"Pop","hip-hop-rap":"Hip-hop / Rap",rnb:"R&B",rock:"Rock","dance-electronic":"Dance / Elektronika",house:"House",techno:"Techno",trap:"Trap",jazz:"Jazz",classical:"Muzyka klasyczna",reggae:"Reggae",latin:"Latino",metal:"Metal",punk:"Punk","romanian-folk":"Folk rumuński","french-house":"Francuski house","varietes-francaises":"Francuska muzyka popularna","drum-bass":"Drum & Bass",garage:"UK Garage",folk:"Folk brytyjski",country:"Country",blues:"Blues",gospel:"Gospel",soul:"Soul",funk:"Funk"},
 tr:{pop:"Pop","hip-hop-rap":"Hip-Hop / Rap",rnb:"R&B",rock:"Rock","dance-electronic":"Dans / Elektronik",house:"House",techno:"Techno",trap:"Trap",jazz:"Caz",classical:"Klasik",reggae:"Reggae",latin:"Latin",metal:"Metal",punk:"Punk","romanian-folk":"Rumen halk müziği","french-house":"Fransız House","varietes-francaises":"Fransız popüler müziği","drum-bass":"Drum & Bass",garage:"UK Garage",folk:"Britanya folk",country:"Country",blues:"Blues",gospel:"Gospel",soul:"Soul",funk:"Funk"},
 id:{pop:"Pop","hip-hop-rap":"Hip-Hop / Rap",rnb:"R&B",rock:"Rock","dance-electronic":"Dance / Elektronik",house:"House",techno:"Techno",trap:"Trap",jazz:"Jazz",classical:"Klasik",reggae:"Reggae",latin:"Latin",metal:"Metal",punk:"Punk","romanian-folk":"Folk Rumania","french-house":"House Prancis","varietes-francaises":"Musik populer Prancis","drum-bass":"Drum & Bass",garage:"UK Garage",folk:"Folk Britania",country:"Country",blues:"Blues",gospel:"Gospel",soul:"Soul",funk:"Funk"},
 ja:{pop:"ポップ","hip-hop-rap":"ヒップホップ / ラップ",rnb:"R&B",rock:"ロック","dance-electronic":"ダンス / エレクトロニック",house:"ハウス",techno:"テクノ",trap:"トラップ",jazz:"ジャズ",classical:"クラシック",reggae:"レゲエ",latin:"ラテン",metal:"メタル",punk:"パンク","romanian-folk":"ルーマニア民謡","french-house":"フレンチ・ハウス","varietes-francaises":"フランス・ポピュラー音楽","drum-bass":"ドラムンベース",grime:"グライム",garage:"UKガラージ",britpop:"ブリットポップ",folk:"英国フォーク",country:"カントリー",blues:"ブルース",gospel:"ゴスペル",soul:"ソウル",funk:"ファンク",bluegrass:"ブルーグラス"},
 ko:{pop:"팝","hip-hop-rap":"힙합 / 랩",rnb:"R&B",rock:"록","dance-electronic":"댄스 / 일렉트로닉",house:"하우스",techno:"테크노",trap:"트랩",jazz:"재즈",classical:"클래식",reggae:"레게",latin:"라틴",metal:"메탈",punk:"펑크","romanian-folk":"루마니아 포크","french-house":"프렌치 하우스","varietes-francaises":"프랑스 대중음악","drum-bass":"드럼 앤 베이스",grime:"그라임",garage:"UK 개러지",britpop:"브릿팝",folk:"영국 포크",country:"컨트리",blues:"블루스",gospel:"가스펠",soul:"소울",funk:"펑크",bluegrass:"블루그래스",reggaeton:"레게톤",flamenco:"플라멩코",rumba:"룸바",sevillanas:"세비야나스",jota:"호타",manele:"마넬레",lautareasca:"러우터레아스커",balkan:"발칸",schlager:"슐라거",krautrock:"크라우트록"},
 hi:{pop:"पॉप","hip-hop-rap":"हिप-हॉप / रैप",rnb:"R&B",rock:"रॉक","dance-electronic":"डांस / इलेक्ट्रॉनिक",house:"हाउस",techno:"टेक्नो",trap:"ट्रैप",jazz:"जैज़",classical:"शास्त्रीय",reggae:"रेगे",latin:"लैटिन",metal:"मेटल",punk:"पंक","romanian-folk":"रोमानियाई लोक","french-house":"फ्रेंच हाउस","varietes-francaises":"फ्रांसीसी लोकप्रिय संगीत","drum-bass":"ड्रम एंड बेस",garage:"यूके गैराज",folk:"ब्रिटिश लोक",country:"कंट्री",blues:"ब्लूज़",gospel:"गॉस्पेल",soul:"सोल",funk:"फंक"}
};
function localizedGenre(locale:string,slug:string,fallback:string){return genreNames[locale]?.[slug]??fallback}
function localizedChartTitle(locale:string,code:string,name:string,size:number){const n=String(size);const map:Record<string,(label:string)=>string>={
 en:l=>l+" Top "+n,nl:l=>l+" Top "+n,ro:l=>"Top "+n+" "+l,de:l=>l+" Top "+n,fr:l=>"Top "+n+" "+l,es:l=>"Top "+n+" "+l,it:l=>"Top "+n+" "+l,pt:l=>"Top "+n+" "+l,pl:l=>l+" Top "+n,tr:l=>l+" Top "+n,id:l=>l+" Top "+n,ja:l=>l+" トップ"+n,ko:l=>l+" 톱 "+n,hi:l=>l+" टॉप "+n};
 const label=code==="INT"?"MOCIFY":code==="GB"?(locale==="ja"?"イギリス":locale==="ko"?"영국":"UK"):code==="US"?(locale==="ja"?"アメリカ":locale==="ko"?"미국":"US"):name;return(map[locale]??map.en)(label)}
const top40Ids=["toca-bonbon","bella-ciao","fara-mine","money-money","kill-the-beat","digital-touch","after-you","zero-gravity","afterlight"];
function getTracks(ids:readonly string[]){return ids.map(id=>releases.find(r=>r.id===id)).filter((r):r is (typeof releases)[number]=>Boolean(r));}
function chartTitle(code:string,name:string,size:number){const prefix=code==="INT"?"MOCIFY":code==="GB"?"UK":code==="US"?"US":name;return prefix+" Top "+size;}
export default function PlaylistsPage(){
 const{locale}=useLanguage(),t=playlistCopy[locale];
 const[selectedCountry,setSelectedCountry]=useState("INT"),[query,setQuery]=useState("");
 const boardRef=useRef<HTMLDivElement>(null),player=useListenerPlayer();
 const country=countryPlaylists.find(p=>p.code===selectedCountry)??countryPlaylists[0];
 const displayNames=useMemo(()=>{try{return new Intl.DisplayNames([locale],{type:"region"})}catch{return null}},[locale]);
 const countryName=(code:string,fallback:string)=>code==="INT"?(locale==="nl"?"Internationaal":locale==="ro"?"Internațional":locale==="de"?"International":locale==="fr"?"International":locale==="es"?"Internacional":locale==="it"?"Internazionale":locale==="pt"?"Internacional":locale==="pl"?"Międzynarodowe":locale==="tr"?"Uluslararası":locale==="id"?"Internasional":locale==="ja"?"インターナショナル":locale==="ko"?"인터내셔널":locale==="hi"?"अंतरराष्ट्रीय":"International"):(displayNames?.of(code)||fallback);
 const selectedCountryName=countryName(country.code,country.country);
 const allGenres=useMemo(()=>[...genrePlaylists,...Object.values(regionalGenres).flat()],[]);
 const playlistColumns=useMemo(()=>{const wanted=countryGenreMap[selectedCountry]??countryGenreMap.INT;const selectedGenres=wanted.map(slug=>allGenres.find(g=>g.slug===slug)).filter((g):g is NonNullable<typeof g>=>Boolean(g));const ids=selectedCountry==="INT"?top40Ids:country.releaseIds;return[40,100,1000].map(size=>({slug:"top"+size,title:localizedChartTitle(locale,selectedCountry,selectedCountryName,size),subtitle:size===40?country.subtitle:t.streamed(size),kicker:selectedCountry==="INT"?t.international:t.countryChart,releaseIds:ids})).concat(selectedGenres.map(g=>({...g,title:localizedGenre(locale,g.slug,g.title),kicker:t.genre})))},[selectedCountry,country,allGenres,t,selectedCountryName,locale]);
 const filtered=playlistColumns.filter(p=>!query.trim()||p.title.toLowerCase().includes(query.toLowerCase())||p.subtitle.toLowerCase().includes(query.toLowerCase()));
 const playable=(ids:readonly string[])=>getTracks(ids).filter(track=>"audioSrc"in track&&Boolean(track.audioSrc));
 const playList=(ids:readonly string[],shuffle=false)=>{let tracks=playable(ids);if(shuffle)tracks=[...tracks].sort(()=>Math.random()-.5);if(tracks[0])player.selectTrack(tracks[0],tracks,true)};
 const playTrack=(id:string,ids:readonly string[])=>{const tracks=playable(ids),track=tracks.find(r=>r.id===id);if(track)player.selectTrack(track,tracks,true)};
 return <Shell active="playlists"><section className="playlist-page page-wrap">
  <SectionHero theme="playlists" kicker={t.kicker} title={t.titleA} accent={t.titleB} text={t.intro} cta={t.browse} href="#playlist-market"/>
  <div id="playlist-market" className={"mocify-country-masthead country-"+selectedCountry.toLowerCase()}><div className="mocify-market-main"><div><span>{country.flag}</span><strong>{selectedCountryName}</strong></div></div><label className="playlist-country-select playlist-country-select-inline"><small>{t.select}</small><select value={selectedCountry} onChange={e=>setSelectedCountry(e.target.value)}>{countryPlaylists.map(p=><option key={p.code} value={p.code}>{p.flag} {countryName(p.code,p.country)}</option>)}</select></label></div>
  <div className="playlist-filterbar"><div className="playlist-filter-search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search} aria-label={t.searchAria}/><Link className="personal-playlists-button" href="/library#personal-playlists">{t.personal}</Link></div><span>{country.flag} {selectedCountryName} · {t.count(filtered.length)}</span></div>
  <div className="playlist-board-tools"><span>{t.browse}</span><div><button onClick={()=>boardRef.current?.scrollBy({left:-346,behavior:"smooth"})}>←</button><button onClick={()=>boardRef.current?.scrollBy({left:346,behavior:"smooth"})}>→</button></div></div>
  <div className="playlist-board" ref={boardRef}>{filtered.map(column=><section className="playlist-column" key={column.slug}><header><Link href={"/playlists/"+selectedCountry.toLowerCase()+"/"+column.slug}><small>{column.kicker}</small><h2>{column.title}</h2></Link><button onClick={()=>playList(column.releaseIds)} aria-label={t.play+" "+column.title}>▶</button></header><div className="playlist-song-list">{getTracks(column.releaseIds).length?getTracks(column.releaseIds).map((track,index)=><button className="playlist-song" key={track.id} onClick={()=>playTrack(track.id,column.releaseIds)}><span className="playlist-rank">{index+1}</span><span className={"playlist-song-cover "+track.art}/><span className="playlist-song-copy"><b>{track.title}</b><span>{track.artist}</span></span><span className="playlist-row-play">▶</span></button>):<div className="playlist-empty">{t.empty}<small>{t.emptySub}</small></div>}</div><Link className="playlist-open" href={"/playlists/"+selectedCountry.toLowerCase()+"/"+column.slug}>{t.open} →</Link></section>)}</div>
  {filtered.length===0&&<div className="playlist-no-results">{t.none(query)}</div>}
 </section></Shell>
}