"use client";
import Link from "next/link";
import { ArtistPortalShell } from "../artist-components";
import ArtistDashboardLayout from "../artist-dashboard-layout";
import {useLanguage} from "../i18n/language-provider";
import UploadForm from "./UploadForm";

const copy={
  en:{kicker:"ARTIST DASHBOARD · RELEASE",title:"Release on",intro:"Upload your final track, add artwork and metadata, and choose when your release becomes available to listeners.",flow:"RELEASE FLOW",flowTitle:"From master to release.",steps:["Upload your final track","Manage title, artwork and metadata","Publish now or choose a release date"],back:"Back to Dashboard"},
  nl:{kicker:"ARTIESTENDASHBOARD · RELEASE",title:"Release op",intro:"Upload je definitieve track, voeg artwork en metadata toe en bepaal wanneer je release beschikbaar wordt voor luisteraars.",flow:"RELEASE FLOW",flowTitle:"Van master naar release.",steps:["Upload je definitieve track","Beheer titel, artwork en metadata","Kies direct publiceren of een releasedatum"],back:"Terug naar Dashboard"},
  ro:{kicker:"DASHBOARD ARTIST · LANSARE",title:"Lansează pe",intro:"Încarcă piesa finală, adaugă artwork și metadate și alege când devine lansarea disponibilă ascultătorilor.",flow:"FLUX LANSARE",flowTitle:"De la master la lansare.",steps:["Încarcă piesa finală","Gestionează titlul, artwork-ul și metadatele","Publică acum sau alege o dată de lansare"],back:"Înapoi la Dashboard"}
}as const;

export default function UploadPage(){const{locale}=useLanguage();const t=copy[locale];return <ArtistPortalShell active="upload"><section className="artist-dashboard-page"><ArtistDashboardLayout><div className="mx-1 mt-5 mb-4 overflow-hidden rounded-2xl border border-white/10 bg-[radial-gradient(circle_at_84%_30%,rgba(237,53,197,.16),transparent_18%),radial-gradient(circle_at_74%_45%,rgba(116,56,255,.20),transparent_30%),linear-gradient(120deg,#0a0d1b,#11102b_68%,#150a20)] px-7 py-7"><p className="text-[9px] font-black tracking-[.16em] text-fuchsia-400">{t.kicker}</p><h1 className="mt-2 text-4xl font-black tracking-[-.05em] text-white md:text-5xl">{t.title} <span className="bg-gradient-to-r from-cyan-400 via-violet-500 to-fuchsia-500 bg-clip-text text-transparent">MOCIFY.</span></h1><p className="mt-3 max-w-2xl text-xs leading-6 text-zinc-400">{t.intro}</p></div><div className="mx-1 grid gap-4 lg:grid-cols-[.72fr_1.28fr]"><aside className="rounded-xl border border-white/10 bg-[linear-gradient(145deg,#0e101c,#090b15)] p-6"><p className="text-[9px] font-black tracking-[.14em] text-fuchsia-400">{t.flow}</p><h2 className="mt-2 text-2xl font-black text-white">{t.flowTitle}</h2><div className="mt-6 space-y-3 text-xs text-zinc-300">{t.steps.map((step,i)=><p className="rounded-lg border border-white/10 bg-black/20 p-4" key={step}><b className={`mr-3 ${i===0?"text-fuchsia-400":i===1?"text-violet-400":"text-cyan-400"}`}>0{i+1}</b>{step}</p>)}</div><Link className="mt-6 inline-flex rounded-lg border border-violet-500/50 bg-violet-500/10 px-4 py-3 text-xs text-white no-underline" href="/dashboard">← {t.back}</Link></aside><UploadForm/></div></ArtistDashboardLayout></section></ArtistPortalShell>}
