"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import { ArtistPortalShell } from "../artist-components";
import ArtistDashboardLayout from "../artist-dashboard-layout";
import {getStoredArtistPlan,hasArtistFeature,type ArtistPlanTier} from "../artist-access";
import {useLanguage} from "../i18n/language-provider";
import UploadForm from "./UploadForm";

const copy={
  en:{kicker:"ARTIST DASHBOARD · RELEASE",title:"Release on",introFree:"Upload your final track, add artwork and metadata. Artist Free releases go live automatically when processing and checks are complete.",introPaid:"Upload your final track, add artwork and metadata, and choose when your release becomes available to listeners.",flow:"RELEASE FLOW",flowTitle:"From master to release.",stepsFree:["Upload your final track","Manage title, artwork and metadata","MOCIFY publishes automatically when the release is ready"],stepsPaid:["Upload your final track","Manage title, artwork and metadata","Publish when ready or choose your own release date"],back:"Back to Dashboard"},
  nl:{kicker:"ARTIESTENDASHBOARD · RELEASE",title:"Release op",introFree:"Upload je definitieve track en voeg artwork en metadata toe. Artist Free-releases gaan automatisch live zodra verwerking en controles zijn afgerond.",introPaid:"Upload je definitieve track, voeg artwork en metadata toe en bepaal wanneer je release beschikbaar wordt voor luisteraars.",flow:"RELEASE FLOW",flowTitle:"Van master naar release.",stepsFree:["Upload je definitieve track","Beheer titel, artwork en metadata","MOCIFY publiceert automatisch zodra de release klaar is"],stepsPaid:["Upload je definitieve track","Beheer titel, artwork en metadata","Publiceer zodra hij klaar is of kies zelf een releasedatum"],back:"Terug naar Dashboard"},
  ro:{kicker:"DASHBOARD ARTIST · LANSARE",title:"Lansează pe",introFree:"Încarcă piesa finală și adaugă artwork și metadate. Lansările Artist Free devin publice automat după procesare și verificări.",introPaid:"Încarcă piesa finală, adaugă artwork și metadate și alege când devine lansarea disponibilă ascultătorilor.",flow:"FLUX LANSARE",flowTitle:"De la master la lansare.",stepsFree:["Încarcă piesa finală","Gestionează titlul, artwork-ul și metadatele","MOCIFY publică automat când lansarea este gata"],stepsPaid:["Încarcă piesa finală","Gestionează titlul, artwork-ul și metadatele","Publică atunci când este gata sau alege propria dată de lansare"],back:"Înapoi la Dashboard"},
de:{kicker:"KÜNSTLER-DASHBOARD · RELEASE",title:"Veröffentlichen auf",introFree:"Lade deinen finalen Track hoch und füge Artwork und Metadaten hinzu. Artist-Free-Releases gehen automatisch live, sobald Verarbeitung und Prüfungen abgeschlossen sind.",introPaid:"Lade deinen finalen Track hoch, füge Artwork und Metadaten hinzu und wähle, wann dein Release verfügbar wird.",flow:"RELEASE-ABLAUF",flowTitle:"Vom Master zum Release.",stepsFree:["Finalen Track hochladen","Titel, Artwork und Metadaten verwalten","MOCIFY veröffentlicht automatisch, sobald der Release bereit ist"],stepsPaid:["Finalen Track hochladen","Titel, Artwork und Metadaten verwalten","Veröffentlichen, sobald er bereit ist, oder eigenes Datum wählen"],back:"Zurück zum Dashboard"},
fr:{kicker:"DASHBOARD ARTISTE · SORTIE",title:"Publier sur",introFree:"Importez votre titre final et ajoutez artwork et métadonnées. Les sorties Artist Free sont publiées automatiquement après traitement et vérifications.",introPaid:"Importez votre titre final, ajoutez artwork et métadonnées et choisissez la date de disponibilité.",flow:"FLUX DE SORTIE",flowTitle:"Du master à la sortie.",stepsFree:["Importer le titre final","Gérer titre, artwork et métadonnées","MOCIFY publie automatiquement quand la sortie est prête"],stepsPaid:["Importer le titre final","Gérer titre, artwork et métadonnées","Publier quand prêt ou choisir une date"],back:"Retour au Dashboard"},
es:{kicker:"PANEL DE ARTISTA · LANZAMIENTO",title:"Lanzar en",introFree:"Sube tu pista final y añade portada y metadatos. Los lanzamientos Artist Free se publican automáticamente tras el procesamiento y las comprobaciones.",introPaid:"Sube tu pista final, añade portada y metadatos y elige cuándo estará disponible.",flow:"FLUJO DE LANZAMIENTO",flowTitle:"Del master al lanzamiento.",stepsFree:["Sube tu pista final","Gestiona título, portada y metadatos","MOCIFY publica automáticamente cuando esté listo"],stepsPaid:["Sube tu pista final","Gestiona título, portada y metadatos","Publica cuando esté listo o elige fecha"],back:"Volver al panel"},
it:{kicker:"DASHBOARD ARTISTA · RELEASE",title:"Pubblica su",introFree:"Carica la traccia finale e aggiungi artwork e metadati. Le release Artist Free vanno online automaticamente dopo elaborazione e controlli.",introPaid:"Carica la traccia finale, aggiungi artwork e metadati e scegli quando renderla disponibile.",flow:"FLUSSO RELEASE",flowTitle:"Dal master alla release.",stepsFree:["Carica la traccia finale","Gestisci titolo, artwork e metadati","MOCIFY pubblica automaticamente quando è pronta"],stepsPaid:["Carica la traccia finale","Gestisci titolo, artwork e metadati","Pubblica quando pronta o scegli una data"],back:"Torna alla Dashboard"},
pt:{kicker:"DASHBOARD DO ARTISTA · LANÇAMENTO",title:"Lançar no",introFree:"Carrega a faixa final e adiciona artwork e metadados. Lançamentos Artist Free ficam disponíveis automaticamente após processamento e verificações.",introPaid:"Carrega a faixa final, adiciona artwork e metadados e escolhe quando fica disponível.",flow:"FLUXO DE LANÇAMENTO",flowTitle:"Do master ao lançamento.",stepsFree:["Carrega a faixa final","Gere título, artwork e metadados","MOCIFY publica automaticamente quando estiver pronta"],stepsPaid:["Carrega a faixa final","Gere título, artwork e metadados","Publica quando estiver pronta ou escolhe uma data"],back:"Voltar ao Dashboard"},
pl:{kicker:"PANEL ARTYSTY · WYDANIE",title:"Wydaj w",introFree:"Prześlij finalny utwór i dodaj okładkę oraz metadane. Wydania Artist Free publikują się automatycznie po przetworzeniu i kontroli.",introPaid:"Prześlij finalny utwór, dodaj okładkę i metadane oraz wybierz datę publikacji.",flow:"PROCES WYDANIA",flowTitle:"Od mastera do wydania.",stepsFree:["Prześlij finalny utwór","Zarządzaj tytułem, okładką i metadanymi","MOCIFY publikuje automatycznie, gdy wydanie jest gotowe"],stepsPaid:["Prześlij finalny utwór","Zarządzaj tytułem, okładką i metadanymi","Opublikuj, gdy gotowe, lub wybierz datę"],back:"Wróć do panelu"},
tr:{kicker:"SANATÇI PANELİ · YAYIN",title:"Şurada yayınla",introFree:"Final parçanı yükle, kapak ve meta verileri ekle. Artist Free yayınları işlem ve kontroller tamamlanınca otomatik yayınlanır.",introPaid:"Final parçanı yükle, kapak ve meta verileri ekle ve ne zaman yayınlanacağını seç.",flow:"YAYIN AKIŞI",flowTitle:"Master'dan yayına.",stepsFree:["Final parçanı yükle","Başlık, kapak ve meta verileri yönet","Hazır olduğunda MOCIFY otomatik yayınlar"],stepsPaid:["Final parçanı yükle","Başlık, kapak ve meta verileri yönet","Hazır olduğunda yayınla veya tarih seç"],back:"Panele dön"}
,
id:{kicker:"DASHBOARD ARTIS · RILIS",title:"Rilis di",introFree:"Unggah track final, tambahkan artwork dan metadata. Rilisan Artist Free tayang otomatis setelah pemrosesan dan pemeriksaan selesai.",introPaid:"Unggah track final, tambahkan artwork dan metadata, lalu pilih kapan rilisan tersedia untuk pendengar.",flow:"ALUR RILIS",flowTitle:"Dari master ke rilisan.",stepsFree:["Unggah track final","Kelola judul, artwork, dan metadata","MOCIFY menerbitkan otomatis saat rilisan siap"],stepsPaid:["Unggah track final","Kelola judul, artwork, dan metadata","Terbitkan saat siap atau pilih tanggal rilismu"],back:"Kembali ke Dashboard"},
ja:{kicker:"アーティストダッシュボード · リリース",title:"リリース先",introFree:"完成トラックをアップロードし、アートワークとメタデータを追加。Artist Freeのリリースは処理とチェック完了後に自動公開されます。",introPaid:"完成トラックをアップロードし、アートワークとメタデータを追加して公開日を選択します。",flow:"リリースフロー",flowTitle:"マスターからリリースへ。",stepsFree:["完成トラックをアップロード","タイトル、アートワーク、メタデータを管理","準備完了後MOCIFYが自動公開"],stepsPaid:["完成トラックをアップロード","タイトル、アートワーク、メタデータを管理","準備完了時に公開、または公開日を選択"],back:"ダッシュボードへ戻る"},
ko:{kicker:"아티스트 대시보드 · 릴리스",title:"릴리스 위치",introFree:"최종 트랙을 업로드하고 아트워크와 메타데이터를 추가하세요. Artist Free 릴리스는 처리와 검사가 끝나면 자동 공개됩니다.",introPaid:"최종 트랙, 아트워크, 메타데이터를 추가하고 공개 시점을 선택하세요.",flow:"릴리스 흐름",flowTitle:"마스터에서 릴리스까지.",stepsFree:["최종 트랙 업로드","제목, 아트워크, 메타데이터 관리","준비가 끝나면 MOCIFY가 자동 공개"],stepsPaid:["최종 트랙 업로드","제목, 아트워크, 메타데이터 관리","준비되면 공개하거나 날짜 선택"],back:"대시보드로 돌아가기"},
hi:{kicker:"कलाकार डैशबोर्ड · रिलीज़",title:"रिलीज़ करें",introFree:"अपना फाइनल ट्रैक अपलोड करें और आर्टवर्क व मेटाडेटा जोड़ें। Artist Free रिलीज़ प्रोसेसिंग और चेक पूरा होने पर ऑटोमेटिक लाइव होती हैं।",introPaid:"फाइनल ट्रैक, आर्टवर्क और मेटाडेटा जोड़ें और चुनें रिलीज़ कब उपलब्ध होगी।",flow:"रिलीज़ फ्लो",flowTitle:"मास्टर से रिलीज़ तक।",stepsFree:["फाइनल ट्रैक अपलोड करें","टाइटल, आर्टवर्क और मेटाडेटा मैनेज करें","रिलीज़ तैयार होने पर MOCIFY ऑटोमेटिक प्रकाशित करता है"],stepsPaid:["फाइनल ट्रैक अपलोड करें","टाइटल, आर्टवर्क और मेटाडेटा मैनेज करें","तैयार होने पर प्रकाशित करें या रिलीज़ तारीख चुनें"],back:"डैशबोर्ड पर वापस"}}as const;

export default function UploadPage(){const{locale}=useLanguage();const t=(copy as any)[locale]??copy.en;const[plan,setPlan]=useState<ArtistPlanTier|null>(null);useEffect(()=>{const read=()=>setPlan(getStoredArtistPlan());read();const sync=(e:Event)=>{const p=(e as CustomEvent<ArtistPlanTier>).detail;if(p==="free"||p==="pro"||p==="max")setPlan(p)};addEventListener("mocify-plan-change",sync);return()=>removeEventListener("mocify-plan-change",sync)},[]);if(plan===null)return null;const canSchedule=hasArtistFeature(plan,"releaseScheduling");const steps=canSchedule?t.stepsPaid:t.stepsFree;return <ArtistPortalShell active="upload"><section className="artist-dashboard-page"><ArtistDashboardLayout plan={plan}><div className="mx-1 mt-5 mb-4 overflow-hidden rounded-2xl border border-white/10 px-7 py-7" style={{width:"100%",aspectRatio:"2120 / 742",minHeight:"0",boxSizing:"border-box",backgroundImage:"linear-gradient(90deg,rgba(6,8,18,.97) 0%,rgba(6,8,18,.84) 36%,rgba(6,8,18,.28) 64%,rgba(6,8,18,.10) 100%),url('/heroes/artist/hero-upload-release-hq.jpg')",backgroundSize:"cover",backgroundPosition:"center right",backgroundRepeat:"no-repeat"}}><p className="text-[9px] font-black tracking-[.16em] text-fuchsia-400">{t.kicker}</p><h1 className="mt-2 text-4xl font-black tracking-[-.05em] text-white md:text-5xl">{t.title} <span className="bg-gradient-to-r from-cyan-400 via-violet-500 to-fuchsia-500 bg-clip-text text-transparent">MOCIFY.</span></h1><p className="mt-3 max-w-2xl text-xs leading-6 text-zinc-400">{canSchedule?t.introPaid:t.introFree}</p></div><div className="mx-1 grid gap-4 lg:grid-cols-[.72fr_1.28fr]"><aside className="rounded-xl border border-white/10 bg-[linear-gradient(145deg,#0e101c,#090b15)] p-6"><p className="text-[9px] font-black tracking-[.14em] text-fuchsia-400">{t.flow}</p><h2 className="mt-2 text-2xl font-black text-white">{t.flowTitle}</h2><div className="mt-6 space-y-3 text-xs text-zinc-300">{steps.map((step,i)=><p className="rounded-lg border border-white/10 bg-black/20 p-4" key={step}><b className={`mr-3 ${i===0?"text-fuchsia-400":i===1?"text-violet-400":"text-cyan-400"}`}>0{i+1}</b>{step}</p>)}</div><Link className="mt-6 inline-flex rounded-lg border border-violet-500/50 bg-violet-500/10 px-4 py-3 text-xs text-white no-underline" href="/dashboard">← {t.back}</Link></aside><UploadForm plan={plan}/></div></ArtistDashboardLayout></section></ArtistPortalShell>}
