"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import { ArtistPortalShell } from "../artist-components";
import ArtistDashboardLayout from "../artist-dashboard-layout";
import {getStoredArtistPlan,hasArtistFeature,type ArtistPlanTier} from "../artist-access";
import {useLanguage} from "../i18n/language-provider";
import UploadForm from "./UploadForm";

const copy={
  en:{kicker:"ARTIST DASHBOARD · RELEASE",title:"Release on",introFree:"Upload your final track, add artwork and metadata. Artist Free releases go live automatically when processing and checks are complete.",introPaid:"Upload your final track, add artwork and metadata, and choose when your release becomes available to listeners.",flow:"RELEASE FLOW",flowTitle:"From master to release.",stepsFree:["Upload your final track","Manage title, artwork and metadata","MOCIFY publishes automatically when the release is ready"],stepsPaid:["Upload your final track","Manage title, artwork and metadata","Publish when ready or choose your own release date"],back:"Back to Dashboard"},
  nl:{kicker:"ARTIESTENDASHBOARD · RELEASE",title:"Release op",introFree:"Upload je definitieve track en voeg artwork en metadata toe. Artist Free-releases gaan automatisch live zodra verwerking en controles zijn afgerond.",introPaid:"Upload je definitieve track, voeg artwork en metadata toe en bepaal wanneer je release beschikbaar wordt voor luisteraars.",flow:"RELEASE FLOW",flowTitle:"Van master naar release.",stepsFree:["Upload je definitieve track","Beheer titel, artwork en metadata","MOCIFY publiceert automatisch zodra de release klaar is"],stepsPaid:["Upload je definitieve track","Beheer titel, artwork en metadata","Publiceer zodra hij klaar is of kies zelf een releasedatum"],back:"Terug naar Dashboard"},
  ro:{kicker:"DASHBOARD ARTIST · LANSARE",title:"Lansează pe",introFree:"Încarcă piesa finală și adaugă artwork și metadate. Lansările Artist Free devin publice automat după procesare și verificări.",introPaid:"Încarcă piesa finală, adaugă artwork și metadate și alege când devine lansarea disponibilă ascultătorilor.",flow:"FLUX LANSARE",flowTitle:"De la master la lansare.",stepsFree:["Încarcă piesa finală","Gestionează titlul, artwork-ul și metadatele","MOCIFY publică automat când lansarea este gata"],stepsPaid:["Încarcă piesa finală","Gestionează titlul, artwork-ul și metadatele","Publică atunci când este gata sau alege propria dată de lansare"],back:"Înapoi la Dashboard"}
}as const;

export default function UploadPage(){const{locale}=useLanguage();const t=copy[locale];const[plan,setPlan]=useState<ArtistPlanTier|null>(null);useEffect(()=>{const read=()=>setPlan(getStoredArtistPlan());read();const sync=(e:Event)=>{const p=(e as CustomEvent<ArtistPlanTier>).detail;if(p==="free"||p==="pro"||p==="max")setPlan(p)};addEventListener("mocify-plan-change",sync);return()=>removeEventListener("mocify-plan-change",sync)},[]);if(plan===null)return null;const canSchedule=hasArtistFeature(plan,"releaseScheduling");const steps=canSchedule?t.stepsPaid:t.stepsFree;return <ArtistPortalShell active="upload"><section className="artist-dashboard-page"><ArtistDashboardLayout plan={plan}><div className="mx-1 mt-5 mb-4 overflow-hidden rounded-2xl border border-white/10 px-7 py-7" style={{backgroundImage:"linear-gradient(90deg,rgba(6,8,18,.97) 0%,rgba(6,8,18,.84) 36%,rgba(6,8,18,.28) 64%,rgba(6,8,18,.10) 100%),url('/heroes/artist/hero-upload-release-hq.jpg')",backgroundSize:"cover",backgroundPosition:"center right",backgroundRepeat:"no-repeat"}}><p className="text-[9px] font-black tracking-[.16em] text-fuchsia-400">{t.kicker}</p><h1 className="mt-2 text-4xl font-black tracking-[-.05em] text-white md:text-5xl">{t.title} <span className="bg-gradient-to-r from-cyan-400 via-violet-500 to-fuchsia-500 bg-clip-text text-transparent">MOCIFY.</span></h1><p className="mt-3 max-w-2xl text-xs leading-6 text-zinc-400">{canSchedule?t.introPaid:t.introFree}</p></div><div className="mx-1 grid gap-4 lg:grid-cols-[.72fr_1.28fr]"><aside className="rounded-xl border border-white/10 bg-[linear-gradient(145deg,#0e101c,#090b15)] p-6"><p className="text-[9px] font-black tracking-[.14em] text-fuchsia-400">{t.flow}</p><h2 className="mt-2 text-2xl font-black text-white">{t.flowTitle}</h2><div className="mt-6 space-y-3 text-xs text-zinc-300">{steps.map((step,i)=><p className="rounded-lg border border-white/10 bg-black/20 p-4" key={step}><b className={`mr-3 ${i===0?"text-fuchsia-400":i===1?"text-violet-400":"text-cyan-400"}`}>0{i+1}</b>{step}</p>)}</div><Link className="mt-6 inline-flex rounded-lg border border-violet-500/50 bg-violet-500/10 px-4 py-3 text-xs text-white no-underline" href="/dashboard">← {t.back}</Link></aside><UploadForm plan={plan}/></div></ArtistDashboardLayout></section></ArtistPortalShell>}
