"use client";
import Link from "next/link";
import {useParams} from "next/navigation";
import {Shell} from "../../../components";
import {countryGenreMap,countryPlaylists,genrePlaylists,regionalGenres,releases} from "../../../data";
import {useListenerPlayer} from "../../../listener-player";
import {useEffect,useState} from "react";
import {SAVED_PLAYLIST_KEY,readIds,toggleId,combinedReleases,hydratedPublishedReleases,type PublishedRelease} from "../../../listener-account";
import {useLanguage} from "../../../i18n/language-provider";
const detailCopy={
 en:{all:"All playlists",unavailable:"Playlist not available",unavailableText:"This genre is not part of the selected country's playlist catalog.",chart:"COUNTRY CHART",playlist:"MOCIFY PLAYLIST",tracks:"tracks",play:"Play all",shuffle:"Shuffle",saved:"Saved",save:"Save",track:"Track",artist:"Artist",duration:"Duration",empty:"No releases yet",emptyText:"This playlist is ready and will automatically fill when matching releases are added to the catalog."},
 nl:{all:"Alle playlists",unavailable:"Playlist niet beschikbaar",unavailableText:"Dit genre maakt geen deel uit van de playlistcatalogus van het gekozen land.",chart:"LANDENCHART",playlist:"MOCIFY PLAYLIST",tracks:"tracks",play:"Alles afspelen",shuffle:"Shuffle",saved:"Opgeslagen",save:"Opslaan",track:"Track",artist:"Artiest",duration:"Duur",empty:"Nog geen releases",emptyText:"Deze playlist staat klaar en wordt automatisch gevuld zodra passende releases aan de catalogus worden toegevoegd."},
 ro:{all:"Toate playlisturile",unavailable:"Playlist indisponibil",unavailableText:"Acest gen nu face parte din catalogul țării selectate.",chart:"CLASAMENT NAȚIONAL",playlist:"PLAYLIST MOCIFY",tracks:"piese",play:"Redă tot",shuffle:"Aleatoriu",saved:"Salvat",save:"Salvează",track:"Piesă",artist:"Artist",duration:"Durată",empty:"Încă nu există lansări",emptyText:"Acest playlist se va completa automat când sunt adăugate lansări potrivite."},
 de:{all:"Alle Playlists",unavailable:"Playlist nicht verfügbar",unavailableText:"Dieses Genre gehört nicht zum Katalog des ausgewählten Landes.",chart:"LÄNDERCHART",playlist:"MOCIFY PLAYLIST",tracks:"Tracks",play:"Alle abspielen",shuffle:"Mischen",saved:"Gespeichert",save:"Speichern",track:"Track",artist:"Künstler",duration:"Dauer",empty:"Noch keine Releases",emptyText:"Diese Playlist füllt sich automatisch, sobald passende Releases hinzugefügt werden."},
 fr:{all:"Toutes les playlists",unavailable:"Playlist indisponible",unavailableText:"Ce genre ne fait pas partie du catalogue du pays sélectionné.",chart:"CLASSEMENT NATIONAL",playlist:"PLAYLIST MOCIFY",tracks:"titres",play:"Tout lire",shuffle:"Aléatoire",saved:"Enregistrée",save:"Enregistrer",track:"Titre",artist:"Artiste",duration:"Durée",empty:"Aucune sortie pour le moment",emptyText:"Cette playlist se remplira automatiquement avec les sorties correspondantes."},
 es:{all:"Todas las playlists",unavailable:"Playlist no disponible",unavailableText:"Este género no forma parte del catálogo del país seleccionado.",chart:"LISTA NACIONAL",playlist:"PLAYLIST MOCIFY",tracks:"pistas",play:"Reproducir todo",shuffle:"Aleatorio",saved:"Guardada",save:"Guardar",track:"Pista",artist:"Artista",duration:"Duración",empty:"Aún no hay lanzamientos",emptyText:"Esta playlist se llenará automáticamente cuando se añadan lanzamientos compatibles."},
 it:{all:"Tutte le playlist",unavailable:"Playlist non disponibile",unavailableText:"Questo genere non fa parte del catalogo del paese selezionato.",chart:"CLASSIFICA NAZIONALE",playlist:"PLAYLIST MOCIFY",tracks:"tracce",play:"Riproduci tutto",shuffle:"Casuale",saved:"Salvata",save:"Salva",track:"Traccia",artist:"Artista",duration:"Durata",empty:"Nessuna release",emptyText:"Questa playlist si riempirà automaticamente quando verranno aggiunte release compatibili."},
 pt:{all:"Todas as playlists",unavailable:"Playlist indisponível",unavailableText:"Este género não faz parte do catálogo do país selecionado.",chart:"TOP NACIONAL",playlist:"PLAYLIST MOCIFY",tracks:"faixas",play:"Reproduzir tudo",shuffle:"Aleatório",saved:"Guardada",save:"Guardar",track:"Faixa",artist:"Artista",duration:"Duração",empty:"Ainda sem lançamentos",emptyText:"Esta playlist será preenchida automaticamente quando forem adicionados lançamentos compatíveis."},
 pl:{all:"Wszystkie playlisty",unavailable:"Playlista niedostępna",unavailableText:"Ten gatunek nie należy do katalogu wybranego kraju.",chart:"LISTA KRAJOWA",playlist:"PLAYLISTA MOCIFY",tracks:"utwory",play:"Odtwórz wszystko",shuffle:"Losowo",saved:"Zapisano",save:"Zapisz",track:"Utwór",artist:"Artysta",duration:"Czas",empty:"Brak wydań",emptyText:"Ta playlista uzupełni się automatycznie po dodaniu pasujących wydań."},
 tr:{all:"Tüm çalma listeleri",unavailable:"Çalma listesi kullanılamıyor",unavailableText:"Bu tür seçilen ülkenin kataloğunda yer almıyor.",chart:"ÜLKE LİSTESİ",playlist:"MOCIFY ÇALMA LİSTESİ",tracks:"parça",play:"Tümünü çal",shuffle:"Karıştır",saved:"Kaydedildi",save:"Kaydet",track:"Parça",artist:"Sanatçı",duration:"Süre",empty:"Henüz yayın yok",emptyText:"Uygun yayınlar eklendiğinde bu liste otomatik olarak dolacaktır."},
 id:{all:"Semua playlist",unavailable:"Playlist tidak tersedia",unavailableText:"Genre ini tidak termasuk katalog negara yang dipilih.",chart:"CHART NEGARA",playlist:"PLAYLIST MOCIFY",tracks:"track",play:"Putar semua",shuffle:"Acak",saved:"Tersimpan",save:"Simpan",track:"Track",artist:"Artis",duration:"Durasi",empty:"Belum ada rilisan",emptyText:"Playlist ini akan terisi otomatis saat rilisan yang cocok ditambahkan."},
 ja:{all:"すべてのプレイリスト",unavailable:"プレイリストを利用できません",unavailableText:"このジャンルは選択した国のカタログに含まれていません。",chart:"国内チャート",playlist:"MOCIFY プレイリスト",tracks:"曲",play:"すべて再生",shuffle:"シャッフル",saved:"保存済み",save:"保存",track:"曲",artist:"アーティスト",duration:"時間",empty:"まだリリースがありません",emptyText:"該当するリリースが追加されると自動的に表示されます。"},
 ko:{all:"모든 플레이리스트",unavailable:"플레이리스트를 사용할 수 없음",unavailableText:"이 장르는 선택한 국가의 카탈로그에 포함되지 않습니다.",chart:"국가 차트",playlist:"MOCIFY 플레이리스트",tracks:"곡",play:"전체 재생",shuffle:"셔플",saved:"저장됨",save:"저장",track:"트랙",artist:"아티스트",duration:"길이",empty:"아직 릴리스가 없습니다",emptyText:"맞는 릴리스가 추가되면 이 플레이리스트가 자동으로 채워집니다."},
 hi:{all:"सभी प्लेलिस्ट",unavailable:"प्लेलिस्ट उपलब्ध नहीं",unavailableText:"यह जॉनर चुने गए देश के कैटलॉग का हिस्सा नहीं है।",chart:"देश चार्ट",playlist:"MOCIFY प्लेलिस्ट",tracks:"ट्रैक",play:"सभी चलाएँ",shuffle:"शफ़ल",saved:"सेव किया",save:"सेव करें",track:"ट्रैक",artist:"कलाकार",duration:"अवधि",empty:"अभी कोई रिलीज़ नहीं",emptyText:"मेल खाने वाली रिलीज़ जुड़ते ही यह प्लेलिस्ट अपने आप भर जाएगी।"}
} as const;
const top40Ids=["toca-bonbon","bella-ciao","fara-mine","money-money","kill-the-beat","digital-touch","after-you","zero-gravity","afterlight"];
const chartTitle=(code:string,name:string,size:number)=>(code==="INT"?"MOCIFY":code==="GB"?"UK":code==="US"?"US":name)+" Top "+size;
export default function PlaylistDetail(){
 const {locale}=useLanguage(),t=(detailCopy as any)[locale]??detailCopy.en;
 const params=useParams<{country:string;slug:string}>(),[saved,setSaved]=useState(false),[catalog,setCatalog]=useState<(typeof releases[number]|PublishedRelease)[]>(()=>[...combinedReleases(releases)]),code=(params.country||"int").toUpperCase(),slug=params.slug||"top40",player=useListenerPlayer();
 const playlistPath="/playlists/"+code.toLowerCase()+"/"+slug;useEffect(()=>{setSaved(readIds(SAVED_PLAYLIST_KEY).includes(playlistPath));const sync=()=>{void hydratedPublishedReleases().then(p=>setCatalog([...p,...releases]))};sync();addEventListener("mocify-library-change",sync);return()=>removeEventListener("mocify-library-change",sync)},[playlistPath]);
 const country=countryPlaylists.find(p=>p.code===code)??countryPlaylists[0],countryName=code==="INT"?"International":(new Intl.DisplayNames([locale],{type:"region"}).of(code)??country.country),allGenres=[...genrePlaylists,...Object.values(regionalGenres).flat()];
 const genre=allGenres.find(g=>g.slug===slug),allowed=(countryGenreMap[code]??countryGenreMap.INT).includes(slug);
 const chartSize=slug==="top40"?40:slug==="top100"?100:slug==="top1000"?1000:null;const playlist=chartSize?{title:chartTitle(code,countryName,chartSize),subtitle:chartSize===40?country.subtitle:"The "+chartSize+" most streamed tracks in this market.",releaseIds:code==="INT"?top40Ids:country.releaseIds}:allowed&&genre?genre:null;
 if(!playlist)return <Shell active="playlists"><section className="playlist-detail page-wrap"><Link href="/playlists">← {t.all}</Link><h1>{t.unavailable}</h1><p>{t.unavailableText}</p></section></Shell>;
 const fixed=playlist.releaseIds.map(id=>catalog.find(r=>r.id===id)).filter(Boolean),dynamic=catalog.filter(r=>r.id.startsWith("published-")&&(!r.country||r.country==="INT"||r.country===code)&&(!genre?.title||r.genre.toLowerCase().includes(genre.title.toLowerCase()))),tracks=[...dynamic,...fixed.filter(r=>!dynamic.some(d=>d.id===r?.id))].filter(Boolean) as typeof catalog,playable=tracks.filter(t=>"audioSrc"in t&&Boolean(t.audioSrc));
 const playAll=(shuffle=false)=>{let queue=playable;if(shuffle)queue=[...queue].sort(()=>Math.random()-.5);if(queue[0])player.selectTrack(queue[0],queue,true)};
 const playOne=(id:string)=>{const track=playable.find(t=>t.id===id);if(track)player.selectTrack(track,playable,true)};
 return <Shell active="playlists"><section className="playlist-detail page-wrap">
  <Link className="playlist-back" href="/playlists">← {t.all}</Link>
  <header className="playlist-detail-hero"><div className="playlist-detail-art"><span>{country.flag}</span><b>{chartSize?String(chartSize):"♫"}</b></div><div><small>{chartSize?t.chart:t.playlist} · {countryName}</small><h1>{playlist.title}</h1><p>{playlist.subtitle}</p><span>{tracks.length} {t.tracks}</span><div className="playlist-detail-actions"><button className="m-primary" disabled={!playable.length} onClick={()=>playAll(false)}>▶ {t.play}</button><button className="m-secondary" disabled={playable.length<2} onClick={()=>playAll(true)}>⤨ {t.shuffle}</button><button className="m-secondary" onClick={()=>setSaved(toggleId(SAVED_PLAYLIST_KEY,playlistPath))}>{saved?"♥ "+t.saved:"♡ "+t.save}</button></div></div></header>
  <div className="playlist-detail-list"><div className="playlist-detail-row head"><span>#</span><span>{t.track}</span><span>{t.artist}</span><span>{t.duration}</span><span></span></div>{tracks.length?tracks.map((track,i)=><button className="playlist-detail-row" key={track.id} onClick={()=>playOne(track.id)}><span>{i+1}</span><span className="detail-track"><i className={track.art}/><b>{track.title}</b></span><span>{track.artist}</span><span>{"duration"in track?track.duration:"—"}</span><span>▶</span></button>):<div className="playlist-detail-empty"><h3>{t.empty}</h3><p>{t.emptyText}</p></div>}</div>
 </section></Shell>
}