"use client";
import {Shell} from "../components";
import {useLanguage} from "../i18n/language-provider";
const copy={
en:{title:"About MOCIFY",p1:"MOCIFY is a home for discovering, listening to and publishing AI-created music. The platform connects listeners with artists and gives creators a dedicated workspace for releases and music tools.",p2:"MOCIFY is being built around clear artist attribution, listener control and a focused AI-music catalogue."},
nl:{title:"Over MOCIFY",p1:"MOCIFY is een plek om AI-gecreëerde muziek te ontdekken, te beluisteren en te publiceren. Het platform verbindt luisteraars met artiesten en geeft makers een eigen werkruimte voor releases en muziektools.",p2:"MOCIFY wordt gebouwd rond duidelijke artiestvermelding, controle voor luisteraars en een gerichte catalogus voor AI-muziek."},
ro:{title:"Despre MOCIFY",p1:"MOCIFY este un loc pentru descoperirea, ascultarea și publicarea muzicii create cu AI. Platforma conectează ascultătorii cu artiștii și oferă creatorilor un spațiu dedicat pentru lansări și instrumente muzicale.",p2:"MOCIFY este construit în jurul atribuirii clare a artiștilor, controlului pentru ascultători și unui catalog dedicat muzicii AI."},
de:{title:"Über MOCIFY",p1:"MOCIFY ist ein Ort zum Entdecken, Hören und Veröffentlichen von KI-erstellter Musik. Die Plattform verbindet Hörer mit Künstlern und bietet Creatorn einen eigenen Bereich für Releases und Musiktools.",p2:"MOCIFY wird mit klarer Künstlerzuordnung, Kontrolle für Hörer und einem fokussierten KI-Musikkatalog entwickelt."},
fr:{title:"À propos de MOCIFY",p1:"MOCIFY est un espace pour découvrir, écouter et publier de la musique créée avec l’IA. La plateforme relie auditeurs et artistes et offre aux créateurs un espace dédié aux sorties et aux outils musicaux.",p2:"MOCIFY est conçu autour d’une attribution claire des artistes, du contrôle des auditeurs et d’un catalogue dédié à la musique IA."},
es:{title:"Acerca de MOCIFY",p1:"MOCIFY es un espacio para descubrir, escuchar y publicar música creada con IA. La plataforma conecta a oyentes con artistas y ofrece a los creadores un espacio dedicado para lanzamientos y herramientas musicales.",p2:"MOCIFY se construye en torno a una atribución clara de los artistas, el control del oyente y un catálogo centrado en música con IA."},
it:{title:"Informazioni su MOCIFY",p1:"MOCIFY è uno spazio per scoprire, ascoltare e pubblicare musica creata con l’IA. La piattaforma collega ascoltatori e artisti e offre ai creator uno spazio dedicato a release e strumenti musicali.",p2:"MOCIFY è costruito attorno a una chiara attribuzione degli artisti, al controllo degli ascoltatori e a un catalogo dedicato alla musica AI."},
pt:{title:"Sobre o MOCIFY",p1:"MOCIFY é um espaço para descobrir, ouvir e publicar música criada com IA. A plataforma liga ouvintes a artistas e oferece aos criadores um espaço dedicado a lançamentos e ferramentas musicais.",p2:"MOCIFY está a ser construído com atribuição clara dos artistas, controlo para os ouvintes e um catálogo focado em música de IA."},
pl:{title:"O MOCIFY",p1:"MOCIFY to miejsce do odkrywania, słuchania i publikowania muzyki tworzonej przez AI. Platforma łączy słuchaczy z artystami i zapewnia twórcom przestrzeń do wydań i narzędzi muzycznych.",p2:"MOCIFY powstaje z myślą o jasnym oznaczaniu artystów, kontroli słuchacza i katalogu skupionym na muzyce AI."},
tr:{title:"MOCIFY Hakkında",p1:"MOCIFY, yapay zekâ ile oluşturulan müziği keşfetmek, dinlemek ve yayınlamak için bir alandır. Platform dinleyicilerle sanatçıları buluşturur ve üreticilere yayınlar ile müzik araçları için özel bir çalışma alanı sunar.",p2:"MOCIFY; açık sanatçı atfı, dinleyici kontrolü ve AI müziğine odaklı bir katalog etrafında geliştirilmektedir."},
id:{title:"Tentang MOCIFY",p1:"MOCIFY adalah tempat untuk menemukan, mendengarkan, dan menerbitkan musik yang dibuat dengan AI. Platform ini menghubungkan pendengar dengan artis dan memberi kreator ruang khusus untuk rilisan dan alat musik.",p2:"MOCIFY dibangun dengan atribusi artis yang jelas, kontrol bagi pendengar, dan katalog yang berfokus pada musik AI."},
ja:{title:"MOCIFYについて",p1:"MOCIFYは、AIで制作された音楽を発見・再生・公開するための場所です。リスナーとアーティストをつなぎ、クリエイターにはリリースや音楽ツールのための専用ワークスペースを提供します。",p2:"MOCIFYは、明確なアーティスト表記、リスナーによるコントロール、AI音楽に特化したカタログを軸に構築されています。"},
ko:{title:"MOCIFY 소개",p1:"MOCIFY는 AI로 제작된 음악을 발견하고 듣고 공개하는 공간입니다. 플랫폼은 리스너와 아티스트를 연결하고 크리에이터에게 릴리스와 음악 도구를 위한 전용 작업 공간을 제공합니다.",p2:"MOCIFY는 명확한 아티스트 표시, 리스너의 제어권, AI 음악에 집중한 카탈로그를 중심으로 구축됩니다."},
hi:{title:"MOCIFY के बारे में",p1:"MOCIFY AI से बनाए गए संगीत को खोजने, सुनने और प्रकाशित करने की जगह है। यह प्लेटफ़ॉर्म श्रोताओं को कलाकारों से जोड़ता है और क्रिएटर्स को रिलीज़ तथा संगीत टूल्स के लिए समर्पित वर्कस्पेस देता है।",p2:"MOCIFY स्पष्ट कलाकार श्रेय, श्रोता नियंत्रण और AI संगीत पर केंद्रित कैटलॉग के आधार पर बनाया जा रहा है।"}
} as const;
export default function About(){const{locale}=useLanguage();const t=(copy as any)[locale]??copy.en;return <Shell><main className="page-wrap legal-page"><p className="page-kicker">MOCIFY</p><h1>{t.title}</h1><p>{t.p1}</p><p>{t.p2}</p></main></Shell>}