"use client";
import Link from "next/link";
import {useEffect,useMemo,useState}from"react";
import{useSearchParams}from"next/navigation";
import{ArtistPortalShell}from"../../artist-components";
import ArtistDashboardLayout from"../../artist-dashboard-layout";
import{featuredTrack}from"../../data";
import{useLanguage}from"../../i18n/language-provider";
import styles from"./music.module.css";

type Filter="all"|"live"|"draft";
const copy={en:{kicker:"ARTIST LIBRARY",title:"My Music",intro:"Manage releases, drafts and upcoming music from one workspace.",upload:"Upload new",search:"Search your music",all:"All",live:"Live",drafts:"Drafts",track:"Track",status:"Status",released:"Released",streams:"Streams",actions:"Actions",published:"Published",draft:"Draft",edit:"Edit",view:"View",continue:"Continue",empty:"No music matches this search.",studio:"Open in MOCIFY STUDIO",dashboard:"Dashboard"},ro:{kicker:"BIBLIOTECĂ ARTIST",title:"Muzica mea",intro:"Gestionează lansările, ciornele și muzica viitoare într-un singur spațiu.",upload:"Încarcă nou",search:"Caută în muzica ta",all:"Toate",live:"Active",drafts:"Ciorne",track:"Piesă",status:"Stare",released:"Lansată",streams:"Redări",actions:"Acțiuni",published:"Publicată",draft:"Ciornă",edit:"Editează",view:"Vezi",continue:"Continuă",empty:"Nicio piesă nu corespunde căutării.",studio:"Deschide în MOCIFY STUDIO",dashboard:"Panou"},nl:{kicker:"ARTIESTENBIBLIOTHEEK",title:"Mijn muziek",intro:"Beheer releases, concepten en aankomende muziek vanuit één werkruimte.",upload:"Nieuwe upload",search:"Zoek in je muziek",all:"Alles",live:"Live",drafts:"Concepten",track:"Track",status:"Status",released:"Uitgebracht",streams:"Streams",actions:"Acties",published:"Gepubliceerd",draft:"Concept",edit:"Bewerken",view:"Bekijken",continue:"Doorgaan",empty:"Geen muziek gevonden voor deze zoekopdracht.",studio:"Openen in MOCIFY STUDIO",dashboard:"Dashboard"},
de:{kicker:"KÜNSTLERBIBLIOTHEK",title:"Meine Musik",intro:"Verwalte Releases, Entwürfe und kommende Musik in einem Bereich.",upload:"Neu hochladen",search:"Deine Musik durchsuchen",all:"Alle",live:"Live",drafts:"Entwürfe",track:"Track",status:"Status",released:"Veröffentlicht",streams:"Streams",actions:"Aktionen",published:"Veröffentlicht",draft:"Entwurf",edit:"Bearbeiten",view:"Ansehen",continue:"Fortsetzen",empty:"Keine Musik entspricht dieser Suche.",studio:"In MOCIFY STUDIO öffnen",dashboard:"Dashboard"},
fr:{kicker:"BIBLIOTHÈQUE ARTISTE",title:"Ma musique",intro:"Gérez sorties, brouillons et musique à venir depuis un seul espace.",upload:"Nouvel import",search:"Rechercher dans votre musique",all:"Tout",live:"En ligne",drafts:"Brouillons",track:"Titre",status:"Statut",released:"Sortie",streams:"Écoutes",actions:"Actions",published:"Publié",draft:"Brouillon",edit:"Modifier",view:"Voir",continue:"Continuer",empty:"Aucun titre ne correspond à cette recherche.",studio:"Ouvrir dans MOCIFY STUDIO",dashboard:"Dashboard"},
es:{kicker:"BIBLIOTECA DE ARTISTA",title:"Mi música",intro:"Gestiona lanzamientos, borradores y próxima música desde un solo espacio.",upload:"Nueva subida",search:"Buscar en tu música",all:"Todo",live:"En vivo",drafts:"Borradores",track:"Pista",status:"Estado",released:"Lanzado",streams:"Reproducciones",actions:"Acciones",published:"Publicado",draft:"Borrador",edit:"Editar",view:"Ver",continue:"Continuar",empty:"No hay música que coincida con la búsqueda.",studio:"Abrir en MOCIFY STUDIO",dashboard:"Panel"},
it:{kicker:"LIBRERIA ARTISTA",title:"La mia musica",intro:"Gestisci release, bozze e musica futura da un unico spazio.",upload:"Nuovo upload",search:"Cerca nella tua musica",all:"Tutto",live:"Live",drafts:"Bozze",track:"Traccia",status:"Stato",released:"Pubblicata",streams:"Stream",actions:"Azioni",published:"Pubblicata",draft:"Bozza",edit:"Modifica",view:"Vedi",continue:"Continua",empty:"Nessuna musica corrisponde alla ricerca.",studio:"Apri in MOCIFY STUDIO",dashboard:"Dashboard"},
pt:{kicker:"BIBLIOTECA DO ARTISTA",title:"A minha música",intro:"Gere lançamentos, rascunhos e música futura num único espaço.",upload:"Novo upload",search:"Pesquisar na tua música",all:"Tudo",live:"Live",drafts:"Rascunhos",track:"Faixa",status:"Estado",released:"Lançado",streams:"Reproduções",actions:"Ações",published:"Publicado",draft:"Rascunho",edit:"Editar",view:"Ver",continue:"Continuar",empty:"Nenhuma música corresponde à pesquisa.",studio:"Abrir no MOCIFY STUDIO",dashboard:"Dashboard"},
pl:{kicker:"BIBLIOTEKA ARTYSTY",title:"Moja muzyka",intro:"Zarządzaj wydaniami, szkicami i nadchodzącą muzyką w jednym miejscu.",upload:"Nowy upload",search:"Szukaj w swojej muzyce",all:"Wszystko",live:"Live",drafts:"Szkice",track:"Utwór",status:"Status",released:"Wydano",streams:"Odtworzenia",actions:"Akcje",published:"Opublikowano",draft:"Szkic",edit:"Edytuj",view:"Zobacz",continue:"Kontynuuj",empty:"Brak muzyki pasującej do wyszukiwania.",studio:"Otwórz w MOCIFY STUDIO",dashboard:"Panel"},
tr:{kicker:"SANATÇI KÜTÜPHANESİ",title:"Müziğim",intro:"Yayınlarını, taslaklarını ve gelecek müziğini tek alanda yönet.",upload:"Yeni yükleme",search:"Müziğinde ara",all:"Tümü",live:"Canlı",drafts:"Taslaklar",track:"Parça",status:"Durum",released:"Yayınlandı",streams:"Dinlenmeler",actions:"İşlemler",published:"Yayınlandı",draft:"Taslak",edit:"Düzenle",view:"Gör",continue:"Devam et",empty:"Bu aramayla eşleşen müzik yok.",studio:"MOCIFY STUDIO'da aç",dashboard:"Panel"}}as const;
const releases=[{id:"featured",title:featuredTrack.title,meta:`Single · ${featuredTrack.duration}`,date:"12 Sep 2026",streams:"14.2K",state:"live" as const,cover:featuredTrack.initials},{id:"digital",title:"Digital Touch",meta:"Single · 3:25",date:"04 Sep 2026",streams:"8.7K",state:"live" as const,cover:"DT"},{id:"after",title:"After You",meta:"Single · 3:32",date:"—",streams:"—",state:"draft" as const,cover:"AY"}];
export default function MyMusic(){const{locale}=useLanguage();const t=(copy as any)[locale]??copy.en;const params=useSearchParams();const[filter,setFilter]=useState<Filter>("all");const[q,setQ]=useState("");useEffect(()=>{setQ(params.get("q")??"")},[params]);const visible=useMemo(()=>releases.filter(r=>(filter==="all"||r.state===filter)&&r.title.toLowerCase().includes(q.trim().toLowerCase())),[filter,q]);return <ArtistPortalShell active="studio"><section className="artist-dashboard-page"><ArtistDashboardLayout><div className={styles.heading}><div><p className="page-kicker">{t.kicker}</p><h1>{t.title}</h1><p>{t.intro}</p></div><div className={styles.headingActions}><Link className={styles.dashboardLink} href="/dashboard">← {t.dashboard}</Link><Link className="m-primary" href="/upload">+ {t.upload}</Link></div></div><div className={styles.toolbar}><label><span>⌕</span><input aria-label={t.search} value={q} onChange={e=>setQ(e.target.value)} placeholder={t.search}/></label><div className={styles.filters}>{(["all","live","draft"]as Filter[]).map(f=><button type="button" key={f} onClick={()=>setFilter(f)} className={filter===f?styles.active:""}>{f==="all"?t.all:f==="live"?t.live:t.drafts}</button>)}</div></div><div className={styles.table}><div className={styles.tableHead}><span>{t.track}</span><span>{t.status}</span><span>{t.released}</span><span>{t.streams}</span><span>{t.actions}</span></div>{visible.length?visible.map((r,i)=><article className={styles.row} key={r.id}><div className={styles.track}><span className={`${styles.cover} ${styles[`cover${i+1}`]}`}>{r.cover}</span><div><b>{r.title}</b><small>{r.meta}</small></div></div><span><em className={r.state==="live"?styles.live:styles.draft}>{r.state==="live"?t.published:t.draft}</em></span><span className={styles.muted}>{r.date}</span><strong>{r.streams}</strong><div className={styles.actions}>{r.state==="draft"?<><button type="button">{t.continue}</button><Link href="/studio/projects">✦ {t.studio}</Link></>:<><button type="button">{t.edit}</button><Link href={r.id==="featured"?featuredTrack.href:"/explore"}>{t.view}</Link></>}</div></article>):<div className={styles.empty}>{t.empty}</div>}</div></ArtistDashboardLayout></section></ArtistPortalShell>}
