"use client";
import Link from "next/link";
import {useMemo,useState}from"react";
import{ArtistPortalShell}from"../../artist-components";
import ArtistDashboardLayout from"../../artist-dashboard-layout";
import{featuredTrack}from"../../data";
import{useLanguage}from"../../i18n/language-provider";
import styles from"./music.module.css";

type Filter="all"|"live"|"draft";
const copy={en:{kicker:"ARTIST LIBRARY",title:"My Music",intro:"Manage releases, drafts and upcoming music from one workspace.",upload:"Upload new",search:"Search your music",all:"All",live:"Live",drafts:"Drafts",track:"Track",status:"Status",released:"Released",streams:"Streams",actions:"Actions",published:"Published",draft:"Draft",edit:"Edit",view:"View",continue:"Continue",empty:"No music matches this search.",studio:"Open in MOCIFY STUDIO",dashboard:"Dashboard"},ro:{kicker:"BIBLIOTECĂ ARTIST",title:"Muzica mea",intro:"Gestionează lansările, ciornele și muzica viitoare într-un singur spațiu.",upload:"Încarcă nou",search:"Caută în muzica ta",all:"Toate",live:"Active",drafts:"Ciorne",track:"Piesă",status:"Stare",released:"Lansată",streams:"Redări",actions:"Acțiuni",published:"Publicată",draft:"Ciornă",edit:"Editează",view:"Vezi",continue:"Continuă",empty:"Nicio piesă nu corespunde căutării.",studio:"Deschide în MOCIFY STUDIO",dashboard:"Panou"},nl:{kicker:"ARTIESTENBIBLIOTHEEK",title:"Mijn muziek",intro:"Beheer releases, concepten en aankomende muziek vanuit één werkruimte.",upload:"Nieuwe upload",search:"Zoek in je muziek",all:"Alles",live:"Live",drafts:"Concepten",track:"Track",status:"Status",released:"Uitgebracht",streams:"Streams",actions:"Acties",published:"Gepubliceerd",draft:"Concept",edit:"Bewerken",view:"Bekijken",continue:"Doorgaan",empty:"Geen muziek gevonden voor deze zoekopdracht.",studio:"Openen in MOCIFY STUDIO",dashboard:"Dashboard"}}as const;
const releases=[{id:"featured",title:featuredTrack.title,meta:`Single · ${featuredTrack.duration}`,date:"12 Sep 2026",streams:"14.2K",state:"live" as const,cover:featuredTrack.initials},{id:"digital",title:"Digital Touch",meta:"Single · 3:25",date:"04 Sep 2026",streams:"8.7K",state:"live" as const,cover:"DT"},{id:"after",title:"After You",meta:"Single · 3:32",date:"—",streams:"—",state:"draft" as const,cover:"AY"}];
export default function MyMusic(){const{locale}=useLanguage();const t=copy[locale];const[filter,setFilter]=useState<Filter>("all");const[q,setQ]=useState("");const visible=useMemo(()=>releases.filter(r=>(filter==="all"||r.state===filter)&&r.title.toLowerCase().includes(q.trim().toLowerCase())),[filter,q]);return <ArtistPortalShell active="studio"><section className="artist-dashboard-page"><ArtistDashboardLayout><div className={styles.heading}><div><p className="page-kicker">{t.kicker}</p><h1>{t.title}</h1><p>{t.intro}</p></div><div className={styles.headingActions}><Link className={styles.dashboardLink} href="/dashboard">← {t.dashboard}</Link><Link className="m-primary" href="/upload">+ {t.upload}</Link></div></div><div className={styles.toolbar}><label><span>⌕</span><input aria-label={t.search} value={q} onChange={e=>setQ(e.target.value)} placeholder={t.search}/></label><div className={styles.filters}>{(["all","live","draft"]as Filter[]).map(f=><button type="button" key={f} onClick={()=>setFilter(f)} className={filter===f?styles.active:""}>{f==="all"?t.all:f==="live"?t.live:t.drafts}</button>)}</div></div><div className={styles.table}><div className={styles.tableHead}><span>{t.track}</span><span>{t.status}</span><span>{t.released}</span><span>{t.streams}</span><span>{t.actions}</span></div>{visible.length?visible.map((r,i)=><article className={styles.row} key={r.id}><div className={styles.track}><span className={`${styles.cover} ${styles[`cover${i+1}`]}`}>{r.cover}</span><div><b>{r.title}</b><small>{r.meta}</small></div></div><span><em className={r.state==="live"?styles.live:styles.draft}>{r.state==="live"?t.published:t.draft}</em></span><span className={styles.muted}>{r.date}</span><strong>{r.streams}</strong><div className={styles.actions}>{r.state==="draft"?<><button type="button">{t.continue}</button><Link href="/studio/projects">✦ {t.studio}</Link></>:<><button type="button">{t.edit}</button><Link href={r.id==="featured"?featuredTrack.href:"/explore"}>{t.view}</Link></>}</div></article>):<div className={styles.empty}>{t.empty}</div>}</div></ArtistDashboardLayout></section></ArtistPortalShell>}
