"use client";
import {Shell} from "../components";
import {useLanguage} from "../i18n/language-provider";
const copy={
en:{title:"Privacy",p1:"MOCIFY is designed to collect only the information needed to provide accounts, music libraries, releases and platform services. Account and payment data will be handled through the relevant secure services when backend functionality is connected.",p2:"Users will be given controls for their account and personal information as those services become active."},
nl:{title:"Privacy",p1:"MOCIFY is ontworpen om alleen informatie te verzamelen die nodig is voor accounts, muziekbibliotheken, releases en platformdiensten. Account- en betaalgegevens worden via de relevante beveiligde diensten verwerkt zodra de backendfunctionaliteit is aangesloten.",p2:"Gebruikers krijgen controle over hun account en persoonlijke informatie wanneer deze diensten actief worden."},
ro:{title:"Confidențialitate",p1:"MOCIFY este conceput să colecteze doar informațiile necesare pentru conturi, biblioteci muzicale, lansări și servicii ale platformei. Datele de cont și plată vor fi gestionate prin servicii securizate relevante atunci când funcționalitatea backend este conectată.",p2:"Utilizatorii vor primi controale pentru contul și informațiile personale pe măsură ce aceste servicii devin active."},
de:{title:"Datenschutz",p1:"MOCIFY ist darauf ausgelegt, nur die Informationen zu erfassen, die für Konten, Musikbibliotheken, Releases und Plattformdienste erforderlich sind. Konto- und Zahlungsdaten werden über geeignete sichere Dienste verarbeitet, sobald die Backend-Funktionen angebunden sind.",p2:"Nutzer erhalten Kontrolle über ihr Konto und ihre persönlichen Informationen, sobald diese Dienste aktiv werden."},
fr:{title:"Confidentialité",p1:"MOCIFY est conçu pour ne collecter que les informations nécessaires aux comptes, bibliothèques musicales, sorties et services de la plateforme. Les données de compte et de paiement seront traitées via les services sécurisés appropriés lorsque le backend sera connecté.",p2:"Les utilisateurs disposeront de contrôles sur leur compte et leurs informations personnelles à mesure que ces services seront activés."},
es:{title:"Privacidad",p1:"MOCIFY está diseñado para recopilar únicamente la información necesaria para cuentas, bibliotecas musicales, lanzamientos y servicios de la plataforma. Los datos de cuenta y pago se gestionarán mediante los servicios seguros correspondientes cuando se conecte el backend.",p2:"Los usuarios dispondrán de controles sobre su cuenta y su información personal a medida que estos servicios se activen."},
it:{title:"Privacy",p1:"MOCIFY è progettato per raccogliere solo le informazioni necessarie a fornire account, librerie musicali, release e servizi della piattaforma. I dati di account e pagamento saranno gestiti tramite servizi sicuri appropriati quando il backend sarà collegato.",p2:"Gli utenti avranno controlli sul proprio account e sulle informazioni personali man mano che questi servizi saranno attivati."},
pt:{title:"Privacidade",p1:"MOCIFY foi concebido para recolher apenas as informações necessárias para contas, bibliotecas de música, lançamentos e serviços da plataforma. Os dados de conta e pagamento serão tratados através dos serviços seguros adequados quando o backend for ligado.",p2:"Os utilizadores terão controlos sobre a sua conta e informações pessoais à medida que estes serviços forem ativados."},
pl:{title:"Prywatność",p1:"MOCIFY zaprojektowano tak, aby zbierać wyłącznie informacje potrzebne do obsługi kont, bibliotek muzycznych, wydań i usług platformy. Dane konta i płatności będą obsługiwane przez odpowiednie bezpieczne usługi po podłączeniu backendu.",p2:"Użytkownicy otrzymają możliwość zarządzania swoim kontem i danymi osobowymi wraz z uruchamianiem tych usług."},
tr:{title:"Gizlilik",p1:"MOCIFY yalnızca hesaplar, müzik kütüphaneleri, yayınlar ve platform hizmetleri için gereken bilgileri toplamak üzere tasarlanmıştır. Hesap ve ödeme verileri backend bağlandığında ilgili güvenli hizmetler üzerinden işlenecektir.",p2:"Bu hizmetler etkinleştikçe kullanıcılara hesapları ve kişisel bilgileri için kontroller sunulacaktır."},
id:{title:"Privasi",p1:"MOCIFY dirancang untuk hanya mengumpulkan informasi yang diperlukan bagi akun, perpustakaan musik, rilisan, dan layanan platform. Data akun dan pembayaran akan ditangani melalui layanan aman yang relevan ketika backend terhubung.",p2:"Pengguna akan diberikan kontrol atas akun dan informasi pribadi mereka saat layanan tersebut mulai aktif."},
ja:{title:"プライバシー",p1:"MOCIFYは、アカウント、音楽ライブラリ、リリース、プラットフォームサービスの提供に必要な情報のみを収集するよう設計されています。バックエンド機能が接続された際、アカウントおよび支払いデータは適切な安全なサービスを通じて処理されます。",p2:"各サービスの有効化に合わせて、ユーザーにはアカウントと個人情報を管理するための機能が提供されます。"},
ko:{title:"개인정보 보호",p1:"MOCIFY는 계정, 음악 라이브러리, 릴리스 및 플랫폼 서비스 제공에 필요한 정보만 수집하도록 설계되었습니다. 백엔드 기능이 연결되면 계정 및 결제 데이터는 관련 보안 서비스를 통해 처리됩니다.",p2:"해당 서비스가 활성화됨에 따라 사용자는 계정과 개인정보를 관리할 수 있는 기능을 제공받게 됩니다."},
hi:{title:"गोपनीयता",p1:"MOCIFY को केवल खातों, संगीत लाइब्रेरी, रिलीज़ और प्लेटफ़ॉर्म सेवाओं के लिए आवश्यक जानकारी एकत्र करने के लिए डिज़ाइन किया गया है। बैकएंड जुड़ने पर खाता और भुगतान डेटा संबंधित सुरक्षित सेवाओं के माध्यम से संभाला जाएगा।",p2:"इन सेवाओं के सक्रिय होने के साथ उपयोगकर्ताओं को अपने खाते और व्यक्तिगत जानकारी पर नियंत्रण दिया जाएगा।"}
} as const;
export default function Privacy(){const{locale}=useLanguage();const t=(copy as any)[locale]??copy.en;return <Shell><main className="page-wrap legal-page"><p className="page-kicker">MOCIFY</p><h1>{t.title}</h1><p>{t.p1}</p><p>{t.p2}</p></main></Shell>}