import type {LegalDocSet} from './legal-types';
const mk=(title:string,intro:string,s:[string,string][])=>({title,intro,sections:s.map(([title,body])=>({title,body})),version:'1.0 · 30 September 2026'});
const make=(l:string,a:string,b:string,li:string,ai:string,bi:string)=>({listener:mk(l,li,[]),artist:mk(a,ai,[]),business:mk(b,bi,[])});
export const legalTranslationsExtra:any={
de:make('MOCIFY Bedingungen für Hörer','MOCIFY Bedingungen für Künstler','MOCIFY Business-Bedingungen','Diese Bedingungen gelten für Guest-, Free- und zahlende Hörer.','Diese Bedingungen gelten für Künstler, Creator und Rechteinhaber.','Diese Bedingungen gelten für Unternehmen und professionelle Nutzer von MOCIFY Business.'),
fr:make('Conditions MOCIFY pour les auditeurs','Conditions MOCIFY pour les artistes','Conditions MOCIFY Business','Ces conditions s’appliquent aux auditeurs Guest, Free et payants.','Ces conditions s’appliquent aux artistes, créateurs et titulaires de droits.','Ces conditions s’appliquent aux entreprises et utilisateurs professionnels de MOCIFY Business.'),
es:make('Términos MOCIFY para oyentes','Términos MOCIFY para artistas','Términos MOCIFY Business','Estos términos se aplican a oyentes Guest, Free y de pago.','Estos términos se aplican a artistas, creadores y titulares de derechos.','Estos términos se aplican a empresas y usuarios profesionales de MOCIFY Business.'),
it:make('Termini MOCIFY per gli ascoltatori','Termini MOCIFY per gli artisti','Termini MOCIFY Business','Questi termini si applicano agli ascoltatori Guest, Free e a pagamento.','Questi termini si applicano ad artisti, creator e titolari dei diritti.','Questi termini si applicano alle aziende e agli utenti professionali di MOCIFY Business.'),
pt:make('Termos MOCIFY para ouvintes','Termos MOCIFY para artistas','Termos MOCIFY Business','Estes termos aplicam-se a ouvintes Guest, Free e pagos.','Estes termos aplicam-se a artistas, criadores e titulares de direitos.','Estes termos aplicam-se a empresas e utilizadores profissionais do MOCIFY Business.'),
pl:make('Warunki MOCIFY dla słuchaczy','Warunki MOCIFY dla artystów','Warunki MOCIFY Business','Niniejsze warunki dotyczą słuchaczy Guest, Free i płatnych.','Niniejsze warunki dotyczą artystów, twórców i właścicieli praw.','Niniejsze warunki dotyczą firm i profesjonalnych użytkowników MOCIFY Business.'),
tr:make('MOCIFY Dinleyici Koşulları','MOCIFY Sanatçı Koşulları','MOCIFY Business Koşulları','Bu koşullar Guest, Free ve ücretli dinleyiciler için geçerlidir.','Bu koşullar sanatçılar, içerik üreticileri ve hak sahipleri için geçerlidir.','Bu koşullar MOCIFY Business kullanan şirketler ve profesyonel kullanıcılar için geçerlidir.'),
id:make('Ketentuan Pendengar MOCIFY','Ketentuan Artis MOCIFY','Ketentuan MOCIFY Business','Ketentuan ini berlaku bagi pendengar Guest, Free, dan berbayar.','Ketentuan ini berlaku bagi artis, kreator, dan pemegang hak.','Ketentuan ini berlaku bagi perusahaan dan pengguna profesional MOCIFY Business.'),
ja:make('MOCIFY リスナー利用規約','MOCIFY アーティスト利用規約','MOCIFY Business 利用規約','本規約はGuest、Free、有料プランのリスナーに適用されます。','本規約はMOCIFYでコンテンツを管理するアーティスト、クリエイター、権利者に適用されます。','本規約はMOCIFY Businessを利用する企業および事業者に適用されます。'),
ko:make('MOCIFY 청취자 이용약관','MOCIFY 아티스트 이용약관','MOCIFY Business 이용약관','본 약관은 Guest, Free 및 유료 청취자에게 적용됩니다.','본 약관은 아티스트, 크리에이터 및 권리자에게 적용됩니다.','본 약관은 MOCIFY Business를 이용하는 기업 및 전문 사용자에게 적용됩니다.'),
hi:make('MOCIFY श्रोता शर्तें','MOCIFY कलाकार शर्तें','MOCIFY Business शर्तें','ये शर्तें Guest, Free और भुगतान करने वाले श्रोताओं पर लागू होती हैं।','ये शर्तें कलाकारों, रचनाकारों और अधिकार धारकों पर लागू होती हैं।','ये शर्तें MOCIFY Business का उपयोग करने वाली कंपनियों और पेशेवर उपयोगकर्ताओं पर लागू होती हैं।')
};