"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import CreatorPlaybackStop from "./creator-playback-stop";
import LanguageSwitcher from "./i18n/language-switcher";
import {useLanguage} from "./i18n/language-provider";
import {artistTranslations} from "./i18n/artist-translations";
import {clearArtistSession,readArtistSession} from "./artist-access";

const artistUiLabels={
 en:{home:"MOCIFY for Artists home",login:"Artist log in",logout:"Artist log out",nav:"Navigation",myArtists:"My Artists",myMusic:"My Music",promote:"Promote",earnings:"Earnings",plans:"Plans",contact:"Contact"},
 nl:{home:"MOCIFY voor Artiesten home",login:"Artist inloggen",logout:"Artist uitloggen",nav:"Navigatie",myArtists:"Mijn artiesten",myMusic:"Mijn muziek",promote:"Promoten",earnings:"Inkomsten",plans:"Abonnementen",contact:"Contact"},
 ro:{home:"Pagina principală MOCIFY pentru artiști",login:"Autentificare Artist",logout:"Deconectare Artist",nav:"Navigare",myArtists:"Artiștii mei",myMusic:"Muzica mea",promote:"Promovează",earnings:"Câștiguri",plans:"Abonamente",contact:"Contact"},
 de:{home:"MOCIFY für Künstler Startseite",login:"Künstler anmelden",logout:"Künstler abmelden",nav:"Navigation",myArtists:"Meine Künstler",myMusic:"Meine Musik",promote:"Bewerben",earnings:"Einnahmen",plans:"Pläne",contact:"Kontakt"},
 fr:{home:"Accueil MOCIFY pour artistes",login:"Connexion artiste",logout:"Déconnexion artiste",nav:"Navigation",myArtists:"Mes artistes",myMusic:"Ma musique",promote:"Promouvoir",earnings:"Revenus",plans:"Abonnements",contact:"Contact"},
 es:{home:"Inicio MOCIFY para artistas",login:"Iniciar sesión artista",logout:"Cerrar sesión artista",nav:"Navegación",myArtists:"Mis artistas",myMusic:"Mi música",promote:"Promocionar",earnings:"Ingresos",plans:"Planes",contact:"Contacto"},
 it:{home:"Home MOCIFY per artisti",login:"Accesso artista",logout:"Disconnetti artista",nav:"Navigazione",myArtists:"I miei artisti",myMusic:"La mia musica",promote:"Promuovi",earnings:"Guadagni",plans:"Piani",contact:"Contatti"},
 pt:{home:"Início MOCIFY para artistas",login:"Login de artista",logout:"Sair da conta de artista",nav:"Navegação",myArtists:"Os meus artistas",myMusic:"A minha música",promote:"Promover",earnings:"Ganhos",plans:"Planos",contact:"Contacto"},
 pl:{home:"Strona główna MOCIFY dla artystów",login:"Logowanie artysty",logout:"Wyloguj artystę",nav:"Nawigacja",myArtists:"Moi artyści",myMusic:"Moja muzyka",promote:"Promuj",earnings:"Zarobki",plans:"Plany",contact:"Kontakt"},
 tr:{home:"MOCIFY sanatçı ana sayfası",login:"Sanatçı girişi",logout:"Sanatçı çıkışı",nav:"Navigasyon",myArtists:"Sanatçılarım",myMusic:"Müziğim",promote:"Tanıt",earnings:"Kazançlar",plans:"Planlar",contact:"İletişim"}
} as const;

export function ArtistLogo(){const{locale}=useLanguage();const t=artistTranslations[locale];const ui=artistUiLabels[locale];const homeLabel=ui.home;return <Link className="artist-brand" href="/for-artists" aria-label={homeLabel}><img src="/mocify-bird.png?v=2" width={46} height={46} alt="" aria-hidden="true"/><span><b>MOCIFY</b><small>{t.forArtists}</small></span></Link>;}

export function ArtistPortalHeader({active=""}:{active?:string}){const router=useRouter();const{locale}=useLanguage();const t=artistTranslations[locale];const[loggedIn,setLoggedIn]=useState(false);useEffect(()=>{const sync=()=>setLoggedIn(Boolean(readArtistSession()));sync();addEventListener("mocify-artist-session-change",sync);addEventListener("storage",sync);return()=>{removeEventListener("mocify-artist-session-change",sync);removeEventListener("storage",sync)}},[]);const ui=artistUiLabels[locale];const logoutLabel=ui.logout;const loginLabel=ui.login;const logout=()=>{clearArtistSession();setLoggedIn(false);window.dispatchEvent(new Event("mocify-artist-session-change"));router.replace("/for-artists/login")};return <header className="artist-portal-header"><ArtistLogo/><nav aria-label={t.nav}><Link className={active==="plans"?"active":""} href="/for-artists">{t.plans}</Link><Link className={active==="studio"?"active":""} href="/dashboard">{t.studio}</Link><Link className={active==="upload"?"active":""} href="/upload">{t.upload}</Link></nav><div className="artist-portal-actions"><LanguageSwitcher/><Link className="artist-back" href="/">{t.back}</Link>{loggedIn?<button type="button" className="m-secondary compact" onClick={logout}>{logoutLabel}</button>:<Link className="m-secondary compact" href="/for-artists/login">{loginLabel}</Link>}<Link className="m-primary compact" href="/for-artists/signup">{t.getStarted}</Link></div></header>;}

export function ArtistPortalFooter(){const{locale}=useLanguage();const t=artistTranslations[locale];const ui=artistUiLabels[locale];const labels={nav:ui.nav,support:"MOCIFY",contact:ui.contact};return <footer className="artist-portal-footer artist-portal-footer-rich"><div className="artist-footer-brand"><ArtistLogo/><p>{t.footer}</p><span>CREATE · PROMOTE · GROW · BELONG</span></div><div className="artist-footer-links"><section><h3>{labels.nav}</h3><Link href="/dashboard">Dashboard</Link><Link href="/studio/artists">{ui.myArtists}</Link><Link href="/studio/music">{ui.myMusic}</Link><Link href="/upload">Upload / Release</Link></section><section><h3>{labels.support}</h3><Link href="/studio/analytics">Analytics</Link><Link href="/studio/promote">{ui.promote}</Link><Link href="/studio/earnings">{ui.earnings}</Link><Link href="/studio/projects">MOCIFY Studio</Link><Link href="/for-artists">{ui.plans}</Link><Link className="artist-footer-contact-link" href="/for-artists/contact">{labels.contact}</Link><Link href="/">{t.listen}</Link></section></div><div className="artist-footer-bottom"><span>© 2026 MOCIFY</span><span>AI MUSIC · INFINITE POSSIBILITIES</span></div></footer>}

export function ArtistPortalShell({children,active=""}:{children:React.ReactNode;active?:string}){const{locale}=useLanguage();const t=artistTranslations[locale];return <div className="artist-portal-shell"><CreatorPlaybackStop/><a className="skip-link" href="#artist-main">{t.skip}</a><ArtistPortalHeader active={active}/><main id="artist-main" tabIndex={-1}>{children}</main><ArtistPortalFooter/></div>}
