"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import CreatorPlaybackStop from "./creator-playback-stop";
import LanguageSwitcher from "./i18n/language-switcher";
import {useLanguage} from "./i18n/language-provider";
import {artistTranslations} from "./i18n/artist-translations";
import {clearArtistSession,readArtistSession} from "./artist-access";

export function ArtistLogo(){const{locale}=useLanguage();const t=artistTranslations[locale];const homeLabel=locale==="nl"?"MOCIFY voor Artiesten home":locale==="ro"?"Pagina principală MOCIFY pentru artiști":"MOCIFY for Artists home";return <Link className="artist-brand" href="/for-artists" aria-label={homeLabel}><img src="/mocify-bird.png?v=2" width={46} height={46} alt="" aria-hidden="true"/><span><b>MOCIFY</b><small>{t.forArtists}</small></span></Link>;}

export function ArtistPortalHeader({active=""}:{active?:string}){const router=useRouter();const{locale}=useLanguage();const t=artistTranslations[locale];const[loggedIn,setLoggedIn]=useState(false);useEffect(()=>{const sync=()=>setLoggedIn(Boolean(readArtistSession()));sync();addEventListener("mocify-artist-session-change",sync);addEventListener("storage",sync);return()=>{removeEventListener("mocify-artist-session-change",sync);removeEventListener("storage",sync)}},[]);const logoutLabel=locale==="nl"?"Artist uitloggen":locale==="ro"?"Deconectare Artist":"Artist log out";const loginLabel=locale==="nl"?"Artist inloggen":locale==="ro"?"Autentificare Artist":"Artist log in";const logout=()=>{clearArtistSession();setLoggedIn(false);window.dispatchEvent(new Event("mocify-artist-session-change"));router.replace("/for-artists/login")};return <header className="artist-portal-header"><ArtistLogo/><nav aria-label={t.nav}><Link className={active==="plans"?"active":""} href="/for-artists">{t.plans}</Link><Link className={active==="studio"?"active":""} href="/dashboard">{t.studio}</Link><Link className={active==="upload"?"active":""} href="/upload">{t.upload}</Link></nav><div className="artist-portal-actions"><LanguageSwitcher/><Link className="artist-back" href="/">{t.back}</Link>{loggedIn?<button type="button" className="m-secondary compact" onClick={logout}>{logoutLabel}</button>:<Link className="m-secondary compact" href="/for-artists/login">{loginLabel}</Link>}<Link className="m-primary compact" href="/for-artists/signup">{t.getStarted}</Link></div></header>;}

export function ArtistPortalFooter(){const{locale}=useLanguage();const t=artistTranslations[locale];const[name,setName]=useState("");const[email,setEmail]=useState("");const[message,setMessage]=useState("");const labels=locale==="nl"?{nav:"Navigatie",support:"MOCIFY",contact:"Contact",name:"Naam",email:"E-mail",message:"Bericht",send:"Bericht versturen",hint:"Opent je e-mailapp."}:locale==="ro"?{nav:"Navigare",support:"MOCIFY",contact:"Contact",name:"Nume",email:"E-mail",message:"Mesaj",send:"Trimite mesaj",hint:"Se deschide aplicația ta de e-mail."}:{nav:"Navigation",support:"MOCIFY",contact:"Contact",name:"Name",email:"Email",message:"Message",send:"Send message",hint:"Opens your email app."};const submit=(e:React.FormEvent)=>{e.preventDefault();const subject=encodeURIComponent("MOCIFY Artist Portal contact");const body=encodeURIComponent(`Name: ${name}\nEmail: ${email}\n\n${message}`);window.location.href=`mailto:contact@mocify.ai?subject=${subject}&body=${body}`};return <footer className="artist-portal-footer artist-portal-footer-rich"><div className="artist-footer-brand"><ArtistLogo/><p>{t.footer}</p><span>CREATE · PROMOTE · GROW · BELONG</span></div><div className="artist-footer-links"><section><h3>{labels.nav}</h3><Link href="/dashboard">Dashboard</Link><Link href="/studio/artists">{locale==="nl"?"Mijn artiesten":locale==="ro"?"Artiștii mei":"My Artists"}</Link><Link href="/studio/music">{locale==="nl"?"Mijn muziek":locale==="ro"?"Muzica mea":"My Music"}</Link><Link href="/upload">Upload / Release</Link></section><section><h3>{labels.support}</h3><Link href="/studio/analytics">Analytics</Link><Link href="/studio/promote">{locale==="nl"?"Promoten":locale==="ro"?"Promovează":"Promote"}</Link><Link href="/studio/earnings">{locale==="nl"?"Inkomsten":locale==="ro"?"Câștiguri":"Earnings"}</Link><Link href="/studio/projects">MOCIFY Studio</Link><Link href="/for-artists">{locale==="nl"?"Abonnementen":locale==="ro"?"Abonamente":"Plans"}</Link><Link href="/">{t.listen}</Link></section></div><form className="artist-footer-contact" onSubmit={submit}><h3>{labels.contact}</h3><div className="artist-footer-contact-row"><label><span>{labels.name}</span><input required value={name} onChange={e=>setName(e.target.value)} /></label><label><span>{labels.email}</span><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} /></label></div><label><span>{labels.message}</span><textarea required rows={3} value={message} onChange={e=>setMessage(e.target.value)} /></label><button type="submit">{labels.send} →</button><small>{labels.hint}</small></form><div className="artist-footer-bottom"><span>© 2026 MOCIFY</span><span>AI MUSIC · INFINITE POSSIBILITIES</span></div></footer>}

export function ArtistPortalShell({children,active=""}:{children:React.ReactNode;active?:string}){const{locale}=useLanguage();const t=artistTranslations[locale];return <div className="artist-portal-shell"><CreatorPlaybackStop/><a className="skip-link" href="#artist-main">{t.skip}</a><ArtistPortalHeader active={active}/><main id="artist-main" tabIndex={-1}>{children}</main><ArtistPortalFooter/></div>}
