"use client";

import Link from "next/link";
import { mobileNavigation, navigation, quickNavigation, type Release } from "./data";
import ListenerBanner from "./listener-banner";
import HeaderSearch from "./header-search";
import { TrackPlayButton } from "./listener-player";
import Player from "./listener-player-ui";
import LanguageSwitcher from "./i18n/language-switcher";
import { useLanguage } from "./i18n/language-provider";
import {useEffect,useState} from "react";
import {LIKED_KEY,readIds,readListenerSession,toggleId,type PublishedRelease} from "./listener-account";

const listenerContactLabels={en:"Contact",nl:"Contact",ro:"Contact",de:"Kontakt",fr:"Contact",es:"Contacto",it:"Contatti",pt:"Contacto",pl:"Kontakt",tr:"İletişim",id:"Kontak",ja:"お問い合わせ",ko:"문의",hi:"संपर्क"} as const;
const likeLabels={en:["Like","Unlike"],nl:["Vind ik leuk","Niet meer leuk"],ro:["Apreciază","Nu mai aprecia"],de:["Gefällt mir","Gefällt mir nicht mehr"],fr:["J’aime","Je n’aime plus"],es:["Me gusta","Ya no me gusta"],it:["Mi piace","Non mi piace più"],pt:["Gosto","Já não gosto"],pl:["Lubię","Nie lubię"],tr:["Beğen","Beğenmekten vazgeç"],id:["Suka","Batal suka"],ja:["いいね","いいねを解除"],ko:["좋아요","좋아요 취소"],hi:["पसंद करें","पसंद हटाएँ"]} as const;
const playlistNavLabels={en:"Playlists",nl:"Playlists",ro:"Playlisturi",de:"Playlists",fr:"Playlists",es:"Playlists",it:"Playlist",pt:"Playlists",pl:"Playlisty",tr:"Çalma listeleri",id:"Playlist",ja:"プレイリスト",ko:"플레이리스트",hi:"प्लेलिस्ट"} as const;

export function Logo() {return <Link className="m-logo" href="/" aria-label="MOCIFY home"><img src="/mocify-bird.png?v=2" width={52} height={52} alt="" aria-hidden="true"/><span>MOCIFY</span></Link>;}
function navLabel(dictionary: ReturnType<typeof useLanguage>["dictionary"], locale:keyof typeof playlistNavLabels, href:string, fallback:string){if(href==="/")return dictionary.nav.home;if(href==="/explore")return dictionary.nav.explore;if(href==="/artists")return dictionary.nav.artists;if(href==="/playlists")return playlistNavLabels[locale];if(href==="/radio")return dictionary.nav.radio;if(href==="/library")return dictionary.nav.library;if(href==="/premium")return dictionary.nav.premium;return fallback;}
export function Header({active=""}:{active?:string}){const{dictionary,locale}=useLanguage();const[session,setSession]=useState<{displayName:string}|null>(null);useEffect(()=>{setSession(readListenerSession())},[]);return <><header className="m-header"><Logo/><nav aria-label={dictionary.common.mainNavigation}>{navigation.map(({label,href})=><Link key={href} className={active===label.toLowerCase()?"active":""} aria-current={active===label.toLowerCase()?"page":undefined} href={href}>{navLabel(dictionary,locale,href,label)}</Link>)}</nav><div className="m-account"><HeaderSearch/><LanguageSwitcher/>{session?<Link className="m-login listener-profile-link" href="/profile">◉ {session.displayName}</Link>:<><Link className="m-login" href="/login">{dictionary.common.signIn}</Link><Link className="m-primary compact m-signup" href="/signup">{dictionary.common.signUp}</Link></>}</div></header><nav className="m-mobile-nav" aria-label={dictionary.common.mobileNavigation}>{mobileNavigation.map(({label,href,icon})=><Link key={href} href={href} aria-current={active===label.toLowerCase()?"page":undefined}><span aria-hidden="true">{icon}</span>{navLabel(dictionary,locale,href,label)}</Link>)}</nav></>;}
export function QuickMenu({active=""}:{active?:string}){const{dictionary,locale}=useLanguage();return <nav className="listener-quick-menu" aria-label={dictionary.common.quickNavigation}>{quickNavigation.map(({label,href,icon})=>{const selected=active===label.toLowerCase()||(label==="MOCIFY Radio"&&active==="radio");return <Link key={href} href={href} className={selected?"active":""} aria-current={selected?"page":undefined}><span className="quick-icon" aria-hidden="true">{icon}</span><span className="quick-label">{navLabel(dictionary,locale,href,label==="MOCIFY Radio"?"Radio":label)}</span></Link>;})}<div className="listener-creator-cta"><span>{dictionary.common.makeMusic}</span><Link href="/for-artists"><span aria-hidden="true">↑</span>{dictionary.common.uploadMusic}</Link></div></nav>;}
export function Footer(){const{dictionary,locale}=useLanguage();return <footer className="m-footer"><div><Logo/><p>{dictionary.common.tagline}</p></div><div><b>{dictionary.footer.discover}</b><Link href="/explore">{dictionary.nav.explore}</Link><Link href="/artists">{dictionary.nav.artists}</Link><Link href="/radio">MOCIFY {dictionary.nav.radio}</Link><Link href="/premium">{dictionary.nav.premium}</Link></div><div><b>{dictionary.footer.creators}</b><Link href="/for-artists">{dictionary.common.uploadMusic}</Link><Link href="/for-artists">{dictionary.footer.artistPortal}</Link></div><div><b>MOCIFY</b><span>{dictionary.footer.aboutSoon}</span><span>{dictionary.footer.termsSoon}</span><span>{dictionary.footer.privacySoon}</span><Link className="listener-footer-contact-link" href="/contact">{listenerContactLabels[locale]} →</Link></div><small>© 2026 MOCIFY</small></footer>;}
export function Shell({children,active="",player=true}:{children:React.ReactNode;active?:string;player?:boolean}){const{dictionary}=useLanguage();return <div className={player?"m-shell listener-shell has-player":"m-shell listener-shell"}><a className="skip-link" href="#main-content">{dictionary.common.skipToContent}</a><Header active={active}/><QuickMenu active={active}/><main id="main-content" className="m-main-frame" tabIndex={-1}>{children}</main><ListenerBanner/><Footer/>{player&&<Player/>}</div>;}
export function ComingSoonButton({children,className="m-secondary",label}:{children:React.ReactNode;className?:string;label?:string}){const{dictionary}=useLanguage();return <button type="button" className={`${className} prototype-control`} disabled title={label??dictionary.common.comingSoon}>{children}<span className="prototype-badge">{dictionary.common.comingSoon}</span></button>;}
export function ReleaseCard({r,index}:{r:Release|PublishedRelease;index:number}){const{dictionary,locale}=useLanguage();const[liked,setLiked]=useState(false);useEffect(()=>setLiked(readIds(LIKED_KEY).includes(r.id)),[r.id]);const card=<><div className={`release-art ${r.art}`}><span className="release-number" aria-hidden="true">{String(index+1).padStart(2,"0")}</span>{("detailReady"in r&&r.detailReady)?<span className="release-play" aria-hidden="true">▶</span>:<span className="release-soon">{dictionary.common.previewSoon}</span>}</div><small>{r.genre}</small><h3>{r.title}</h3><p>{r.artist}</p></>;const content="href" in r&&r.href?<Link className="release-card-link" href={r.href}>{card}</Link>:card;return <article id={r.id} className={`release-card${"href" in r&&r.href?"":" release-card-static"}`}>{content}<div className="release-card-actions"><TrackPlayButton track={r}/><button className={"release-like "+(liked?"active":"")} onClick={()=>setLiked(toggleId(LIKED_KEY,r.id))} aria-label={liked?likeLabels[locale][1]:likeLabels[locale][0]}>{liked?"♥":"♡"}</button></div></article>;}
