"use client";

import Link from "next/link";
import { mobileNavigation, navigation, quickNavigation, type Release } from "./data";
import ListenerBanner from "./listener-banner";
import HeaderSearch from "./header-search";
import { TrackPlayButton } from "./listener-player";
import Player from "./listener-player-ui";
import LanguageSwitcher from "./i18n/language-switcher";
import { useLanguage } from "./i18n/language-provider";
import {useEffect,useState} from "react";
import {LIKED_KEY,createPlaylist,ensureStarterPlaylist,readIds,readListenerSession,readPlaylists,toggleId,toggleTrackInPlaylist,type ListenerPlaylist,type PublishedRelease} from "./listener-account";

const listenerContactLabels={en:"Contact",nl:"Contact",ro:"Contact",de:"Kontakt",fr:"Contact",es:"Contacto",it:"Contatti",pt:"Contacto",pl:"Kontakt",tr:"İletişim",id:"Kontak",ja:"お問い合わせ",ko:"문의",hi:"संपर्क"} as const;
const likeLabels={en:["Like","Unlike"],nl:["Vind ik leuk","Niet meer leuk"],ro:["Apreciază","Nu mai aprecia"],de:["Gefällt mir","Gefällt mir nicht mehr"],fr:["J’aime","Je n’aime plus"],es:["Me gusta","Ya no me gusta"],it:["Mi piace","Non mi piace più"],pt:["Gosto","Já não gosto"],pl:["Lubię","Nie lubię"],tr:["Beğen","Beğenmekten vazgeç"],id:["Suka","Batal suka"],ja:["いいね","いいねを解除"],ko:["좋아요","좋아요 취소"],hi:["पसंद करें","पसंद हटाएँ"]} as const;

const playlistActionLabels={en:{add:"Add to playlist",new:"New playlist",name:"Playlist name",create:"Create",done:"Done",duplicate:"A playlist with this name already exists."},nl:{add:"Toevoegen aan playlist",new:"Nieuwe playlist",name:"Naam van playlist",create:"Maken",done:"Klaar",duplicate:"Er bestaat al een playlist met deze naam."},ro:{add:"Adaugă în playlist",new:"Playlist nou",name:"Numele playlistului",create:"Creează",done:"Gata",duplicate:"Există deja un playlist cu acest nume."},de:{add:"Zur Playlist hinzufügen",new:"Neue Playlist",name:"Playlist-Name",create:"Erstellen",done:"Fertig",duplicate:"Eine Playlist mit diesem Namen existiert bereits."},fr:{add:"Ajouter à une playlist",new:"Nouvelle playlist",name:"Nom de la playlist",create:"Créer",done:"Terminé",duplicate:"Une playlist portant ce nom existe déjà."},es:{add:"Añadir a playlist",new:"Nueva playlist",name:"Nombre de playlist",create:"Crear",done:"Listo",duplicate:"Ya existe una playlist con este nombre."},it:{add:"Aggiungi alla playlist",new:"Nuova playlist",name:"Nome playlist",create:"Crea",done:"Fatto",duplicate:"Esiste già una playlist con questo nome."},pt:{add:"Adicionar à playlist",new:"Nova playlist",name:"Nome da playlist",create:"Criar",done:"Concluído",duplicate:"Já existe uma playlist com este nome."},pl:{add:"Dodaj do playlisty",new:"Nowa playlista",name:"Nazwa playlisty",create:"Utwórz",done:"Gotowe",duplicate:"Playlista o tej nazwie już istnieje."},tr:{add:"Çalma listesine ekle",new:"Yeni çalma listesi",name:"Çalma listesi adı",create:"Oluştur",done:"Bitti",duplicate:"Bu ada sahip bir çalma listesi zaten var."},id:{add:"Tambahkan ke playlist",new:"Playlist baru",name:"Nama playlist",create:"Buat",done:"Selesai",duplicate:"Playlist dengan nama ini sudah ada."},ja:{add:"プレイリストに追加",new:"新しいプレイリスト",name:"プレイリスト名",create:"作成",done:"完了",duplicate:"同じ名前のプレイリストが既にあります。"},ko:{add:"플레이리스트에 추가",new:"새 플레이리스트",name:"플레이리스트 이름",create:"만들기",done:"완료",duplicate:"같은 이름의 플레이리스트가 이미 있습니다."},hi:{add:"प्लेलिस्ट में जोड़ें",new:"नई प्लेलिस्ट",name:"प्लेलिस्ट का नाम",create:"बनाएँ",done:"हो गया",duplicate:"इस नाम की प्लेलिस्ट पहले से मौजूद है।"}} as const;
const playlistNavLabels={en:"Playlists",nl:"Playlists",ro:"Playlisturi",de:"Playlists",fr:"Playlists",es:"Playlists",it:"Playlist",pt:"Playlists",pl:"Playlisty",tr:"Çalma listeleri",id:"Playlist",ja:"プレイリスト",ko:"플레이리스트",hi:"प्लेलिस्ट"} as const;

export function Logo() {return <Link className="m-logo" href="/" aria-label="MOCIFY home"><img src="/mocify-bird.png?v=2" width={52} height={52} alt="" aria-hidden="true"/><span>MOCIFY</span></Link>;}
function navLabel(dictionary: ReturnType<typeof useLanguage>["dictionary"], locale:keyof typeof playlistNavLabels, href:string, fallback:string){if(href==="/")return dictionary.nav.home;if(href==="/explore")return dictionary.nav.explore;if(href==="/artists")return dictionary.nav.artists;if(href==="/playlists")return playlistNavLabels[locale];if(href==="/radio")return dictionary.nav.radio;if(href==="/library")return dictionary.nav.library;if(href==="/premium")return dictionary.nav.premium;return fallback;}
export function Header({active=""}:{active?:string}){const{dictionary,locale}=useLanguage();const[session,setSession]=useState<{displayName:string}|null>(null);useEffect(()=>{setSession(readListenerSession())},[]);return <><header className="m-header"><Logo/><nav aria-label={dictionary.common.mainNavigation}>{navigation.map(({label,href})=><Link key={href} className={active===label.toLowerCase()?"active":""} aria-current={active===label.toLowerCase()?"page":undefined} href={href}>{navLabel(dictionary,locale,href,label)}</Link>)}</nav><div className="m-account"><HeaderSearch/><LanguageSwitcher/>{session?<Link className="m-login listener-profile-link" href="/profile">◉ {session.displayName}</Link>:<><Link className="m-login" href="/login">{dictionary.common.signIn}</Link><Link className="m-primary compact m-signup" href="/signup">{dictionary.common.signUp}</Link></>}</div></header><nav className="m-mobile-nav" aria-label={dictionary.common.mobileNavigation}>{mobileNavigation.map(({label,href,icon})=><Link key={href} href={href} aria-current={active===label.toLowerCase()?"page":undefined}><span aria-hidden="true">{icon}</span>{navLabel(dictionary,locale,href,label)}</Link>)}</nav></>;}
export function QuickMenu({active=""}:{active?:string}){const{dictionary,locale}=useLanguage();return <nav className="listener-quick-menu" aria-label={dictionary.common.quickNavigation}>{quickNavigation.map(({label,href,icon})=>{const selected=active===label.toLowerCase()||(label==="MOCIFY Radio"&&active==="radio");return <Link key={href} href={href} className={selected?"active":""} aria-current={selected?"page":undefined}><span className="quick-icon" aria-hidden="true">{icon}</span><span className="quick-label">{navLabel(dictionary,locale,href,label==="MOCIFY Radio"?"Radio":label)}</span></Link>;})}<div className="listener-creator-cta"><span>{dictionary.common.makeMusic}</span><Link href="/for-artists"><span aria-hidden="true">↑</span>{dictionary.common.uploadMusic}</Link></div></nav>;}
export function Footer(){const{dictionary,locale}=useLanguage();return <footer className="m-footer"><div><Logo/><p>{dictionary.common.tagline}</p></div><div><b>{dictionary.footer.discover}</b><Link href="/explore">{dictionary.nav.explore}</Link><Link href="/artists">{dictionary.nav.artists}</Link><Link href="/radio">MOCIFY {dictionary.nav.radio}</Link><Link href="/premium">{dictionary.nav.premium}</Link></div><div><b>{dictionary.footer.creators}</b><Link href="/for-artists">{dictionary.common.uploadMusic}</Link><Link href="/for-artists">{dictionary.footer.artistPortal}</Link></div><div><b>MOCIFY</b><span>{dictionary.footer.aboutSoon}</span><span>{dictionary.footer.termsSoon}</span><span>{dictionary.footer.privacySoon}</span><Link className="listener-footer-contact-link" href="/contact">{listenerContactLabels[locale]} →</Link></div><small>© 2026 MOCIFY</small></footer>;}
export function Shell({children,active="",player=true}:{children:React.ReactNode;active?:string;player?:boolean}){const{dictionary}=useLanguage();return <div className={player?"m-shell listener-shell has-player":"m-shell listener-shell"}><a className="skip-link" href="#main-content">{dictionary.common.skipToContent}</a><Header active={active}/><QuickMenu active={active}/><main id="main-content" className="m-main-frame" tabIndex={-1}>{children}</main><ListenerBanner/><Footer/>{player&&<Player/>}</div>;}
export function ComingSoonButton({children,className="m-secondary",label}:{children:React.ReactNode;className?:string;label?:string}){const{dictionary}=useLanguage();return <button type="button" className={`${className} prototype-control`} disabled title={label??dictionary.common.comingSoon}>{children}<span className="prototype-badge">{dictionary.common.comingSoon}</span></button>;}

export function AddToPlaylist({trackId}:{trackId:string}){const{locale}=useLanguage();const t=playlistActionLabels[locale];const[open,setOpen]=useState(false);const[items,setItems]=useState<ListenerPlaylist[]>([]);const[creating,setCreating]=useState(false);const[name,setName]=useState(""),[error,setError]=useState("");const refresh=()=>setItems(ensureStarterPlaylist());useEffect(()=>{if(open)refresh()},[open]);const toggle=(id:string)=>{toggleTrackInPlaylist(id,trackId);setItems(readPlaylists())};const make=()=>{const value=name.trim();if(!value)return;const p=createPlaylist(value);if(!p){setError(t.duplicate);return;}toggleTrackInPlaylist(p.id,trackId);setItems(readPlaylists());setName("");setError("");setCreating(false)};return <div className="playlist-action"><button type="button" className="release-playlist-add" aria-label={t.add} aria-expanded={open} onClick={()=>setOpen(v=>!v)}>＋</button>{open&&<div className="playlist-action-popover" role="dialog" aria-label={t.add}><strong>{t.add}</strong><div className="playlist-action-list">{items.map(p=>{const checked=p.trackIds.includes(trackId);return <button type="button" key={p.id} className={checked?"selected":""} onClick={()=>toggle(p.id)}><span>{p.name}</span><b>{checked?"✓":"＋"}</b></button>})}</div>{creating?<div className="playlist-action-create"><input autoFocus value={name} onChange={e=>{setName(e.target.value);setError("")}} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();make()}}} placeholder={t.name}/><button type="button" onClick={make} disabled={!name.trim()}>{t.create}</button>{error&&<small className="playlist-action-error" role="alert">{error}</small>}</div>:<button type="button" className="playlist-action-new" onClick={()=>setCreating(true)}>＋ {t.new}</button>}<button type="button" className="playlist-action-done" onClick={()=>setOpen(false)}>{t.done}</button></div>}</div>}

export function ReleaseCard({r,index}:{r:Release|PublishedRelease;index:number}){const{dictionary,locale}=useLanguage();const[liked,setLiked]=useState(false);useEffect(()=>setLiked(readIds(LIKED_KEY).includes(r.id)),[r.id]);const card=<><div className={`release-art ${r.art}`}><span className="release-number" aria-hidden="true">{String(index+1).padStart(2,"0")}</span>{("detailReady"in r&&r.detailReady)?<span className="release-play" aria-hidden="true">▶</span>:<span className="release-soon">{dictionary.common.previewSoon}</span>}</div><small>{r.genre}</small><h3>{r.title}</h3><p>{r.artist}</p></>;const content="href" in r&&r.href?<Link className="release-card-link" href={r.href}>{card}</Link>:card;return <article id={r.id} className={`release-card${"href" in r&&r.href?"":" release-card-static"}`}>{content}<div className="release-card-actions"><TrackPlayButton track={r}/><button className={"release-like "+(liked?"active":"")} onClick={()=>setLiked(toggleId(LIKED_KEY,r.id))} aria-label={liked?likeLabels[locale][1]:likeLabels[locale][0]}>{liked?"♥":"♡"}</button><AddToPlaylist trackId={r.id}/></div></article>;}
