"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { formatTime, useListenerPlayer, type RepeatMode } from "./listener-player";

const repeatLabels: Record<RepeatMode,string>={off:"Repeat off",queue:"Repeat queue",track:"Repeat current track"};
const BAR_COUNT=220;
const idleBars=Array.from({length:BAR_COUNT},(_,index)=>.025+((index*17)%7)*.006);

function PlayerIcon({name}:{name:"heart"|"more"|"shuffle"|"prev"|"next"|"repeat"|"volume"|"cast"|"queue"|"play"|"pause"}){
 const common={width:20,height:20,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.9,strokeLinecap:"round" as const,strokeLinejoin:"round" as const,"aria-hidden":true};
 if(name==="heart")return <svg {...common}><path d="M20.8 4.6a5.4 5.4 0 0 0-7.6 0L12 5.8l-1.2-1.2a5.4 5.4 0 1 0-7.6 7.6L12 21l8.8-8.8a5.4 5.4 0 0 0 0-7.6Z"/></svg>;
 if(name==="more")return <svg {...common}><circle cx="5" cy="12" r="1.25" fill="currentColor" stroke="none"/><circle cx="12" cy="12" r="1.25" fill="currentColor" stroke="none"/><circle cx="19" cy="12" r="1.25" fill="currentColor" stroke="none"/></svg>;
 if(name==="shuffle")return <svg {...common}><path d="M3 7h3.5c2.2 0 3.3 1.2 4.3 2.8l2.4 4.1c1 1.6 2.1 3.1 4.3 3.1H21"/><path d="m18 14 3 3-3 3"/><path d="M3 17h3.5c1.7 0 2.8-.7 3.7-1.9"/><path d="M14.2 8.9c.9-1.2 1.9-1.9 3.3-1.9H21"/><path d="m18 4 3 3-3 3"/></svg>;
 if(name==="prev")return <svg {...common}><path d="M6 5v14"/><path d="m19 6-9 6 9 6V6Z" fill="currentColor" stroke="none"/></svg>;
 if(name==="next")return <svg {...common}><path d="M18 5v14"/><path d="m5 6 9 6-9 6V6Z" fill="currentColor" stroke="none"/></svg>;
 if(name==="repeat")return <svg {...common}><path d="M17 2.8 20.2 6 17 9.2"/><path d="M3.8 10V8.5A2.5 2.5 0 0 1 6.3 6h13.3"/><path d="m7 21.2-3.2-3.2L7 14.8"/><path d="M20.2 14v1.5a2.5 2.5 0 0 1-2.5 2.5H4.4"/></svg>;
 if(name==="volume")return <svg {...common}><path d="M4 9v6h4l5 4V5L8 9H4Z"/><path d="M16 9.2a4 4 0 0 1 0 5.6"/></svg>;
 if(name==="cast")return <svg {...common}><path d="M4 18a2 2 0 0 1 2 2"/><path d="M4 14a6 6 0 0 1 6 6"/><path d="M4 10a10 10 0 0 1 10 10"/><path d="M8 5h9a3 3 0 0 1 3 3v8"/></svg>;
 if(name==="queue")return <svg {...common}><path d="M10 7h10M10 12h10M10 17h10"/><circle cx="5" cy="7" r="1" fill="currentColor" stroke="none"/><circle cx="5" cy="12" r="1" fill="currentColor" stroke="none"/><circle cx="5" cy="17" r="1" fill="currentColor" stroke="none"/></svg>;
 if(name==="pause")return <svg {...common} width="22" height="22"><path d="M9 6v12M15 6v12" strokeWidth="2.6"/></svg>;
 return <svg {...common} width="22" height="22"><path d="m9 6 9 6-9 6V6Z" fill="currentColor" stroke="none"/></svg>;
}

export default function Player(){
 const[queueOpen,setQueueOpen]=useState(false),[moreOpen,setMoreOpen]=useState(false),[savedIds,setSavedIds]=useState<string[]>([]),[spectrum,setSpectrum]=useState(idleBars);const lastAudibleVolume=useRef(1);
 const{currentTrack,queue,isPlaying,currentTime,duration,volume,shuffle,repeatMode,hasAudioSource,status,togglePlay,nextTrack,previousTrack,seek,setVolume,toggleShuffle,cycleRepeat,requestPlaybackTarget,selectTrack,sampleSpectrum}=useListenerPlayer();
 const progress=duration>0?Math.min(100,(currentTime/duration)*100):0,repeatLabel=repeatLabels[repeatMode];
 const isSaved=savedIds.includes(currentTrack.id);
 const persistSaved=(ids:string[])=>{setSavedIds(ids);try{localStorage.setItem("mocify-saved-track-ids",JSON.stringify(ids))}catch{}};
 const toggleSaved=()=>{const next=isSaved?savedIds.filter(id=>id!==currentTrack.id):[...savedIds,currentTrack.id];persistSaved(next)};
 const copyTrackLink=async()=>{const path=currentTrack.href??`/explore#${currentTrack.id}`;const url=typeof window!=="undefined"?new URL(path,window.location.origin).toString():path;try{await navigator.clipboard.writeText(url)}catch{}setMoreOpen(false)};
 const updateVolume=(value:number)=>{if(value>0)lastAudibleVolume.current=value;setVolume(value)};
 const toggleMute=()=>{if(volume>0){lastAudibleVolume.current=volume;setVolume(0)}else setVolume(lastAudibleVolume.current||.8)};
 const seekFromPointer=(event:React.PointerEvent<HTMLElement>)=>{if(!hasAudioSource||!duration)return;const rect=event.currentTarget.getBoundingClientRect();const ratio=Math.max(0,Math.min(1,(event.clientX-rect.left)/rect.width));seek(ratio*duration)};
 const beginWaveSeek=(event:React.PointerEvent<HTMLDivElement>)=>{if(!hasAudioSource||!duration)return;event.currentTarget.setPointerCapture?.(event.pointerId);seekFromPointer(event)};
 const dragWaveSeek=(event:React.PointerEvent<HTMLDivElement>)=>{if(event.currentTarget.hasPointerCapture?.(event.pointerId))seekFromPointer(event)};
 useEffect(()=>{try{const raw=localStorage.getItem("mocify-saved-track-ids");const parsed=raw?JSON.parse(raw):[];if(Array.isArray(parsed))setSavedIds(parsed.filter((id):id is string=>typeof id==="string"))}catch{}},[]);
 useEffect(()=>{let frame=0,last=0;const tick=(now:number)=>{if(isPlaying&&now-last>16){const live=sampleSpectrum(BAR_COUNT);setSpectrum(previous=>live.map((value,index)=>{const old=previous[index]??.025;const bass=index<BAR_COUNT*.22;const raw=Math.max(0,(value-(bass?.055:.075))/(bass?.72:.64));const gate=Math.max(0,Math.min(1,raw));const contrast=Math.pow(gate,bass?.72:.92);const accent=((index*13)%11===0?1.18:((index*7)%9===0?1.08:1));const target=Math.min(1,contrast*(bass?1.55:1.30)*accent);const attack=target>old?.96:.34;const next=old+(target-old)*attack;return Math.max(.018,Math.min(1,next))}));last=now}else if(!isPlaying&&now-last>55){setSpectrum(previous=>previous.map((value,index)=>value+(idleBars[index]-value)*.22));last=now}frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[isPlaying,sampleSpectrum]);
 return <section className="m-player" aria-label="Music player"><div className="m-player-accent" aria-hidden="true"/><div className="m-player-inner">
  <div className="m-player-top">
   <div className="m-player-track-area"><Link className="m-player-track" href={currentTrack.href??"/explore"}><span className={`m-player-cover ${currentTrack.art}`} aria-hidden="true"/><span className="m-player-track-copy"><b>{currentTrack.title}</b><small>{currentTrack.artist}</small></span></Link><button type="button" className={isSaved?"m-player-save active":"m-player-save"} aria-label={isSaved?`Remove ${currentTrack.title} from library`:`Save ${currentTrack.title} to library`} aria-pressed={isSaved} onClick={toggleSaved}><PlayerIcon name="heart"/></button><div className="m-player-more-wrap"><button type="button" className={moreOpen?"m-player-more active":"m-player-more"} aria-label="More options" aria-expanded={moreOpen} onClick={()=>setMoreOpen(v=>!v)}><PlayerIcon name="more"/></button>{moreOpen&&<div className="m-player-more-menu" role="menu"><button type="button" role="menuitem" onClick={()=>{toggleSaved();setMoreOpen(false)}}>{isSaved?"Remove from Library":"Save to Library"}</button><Link role="menuitem" href={currentTrack.href??`/explore#${currentTrack.id}`} onClick={()=>setMoreOpen(false)}>Open track</Link><button type="button" role="menuitem" onClick={copyTrackLink}>Copy track link</button></div>}</div></div>

   <div className="m-player-center"><div className="m-controls" aria-label="Playback controls"><button type="button" className={shuffle?"m-utility active":"m-utility"} aria-label={shuffle?"Turn off shuffle":"Turn on shuffle"} aria-pressed={shuffle} onClick={toggleShuffle}><PlayerIcon name="shuffle"/></button><button type="button" aria-label="Previous track" onClick={previousTrack} disabled={queue.length<2}><PlayerIcon name="prev"/></button><button type="button" aria-label={isPlaying?"Pause track":"Play track"} onClick={togglePlay} disabled={!hasAudioSource} className="m-play"><PlayerIcon name={isPlaying?"pause":"play"}/></button><button type="button" aria-label="Next track" onClick={nextTrack} disabled={queue.length<2}><PlayerIcon name="next"/></button><button type="button" className={repeatMode!=="off"?"m-utility active":"m-utility"} aria-label={repeatLabel} aria-pressed={repeatMode!=="off"} onClick={cycleRepeat} disabled={!hasAudioSource}><PlayerIcon name="repeat"/></button></div></div>

   <div className="m-player-tools"><div className="m-volume" aria-label={`Volume, ${Math.round(volume*100)} percent`}><button type="button" className="m-volume-mute" onClick={toggleMute} disabled={!hasAudioSource} aria-label={volume===0?"Unmute":"Mute"} title={volume===0?"Unmute":"Mute"}><PlayerIcon name="volume"/></button><input type="range" min="0" max="1" step="0.01" value={volume} onInput={e=>updateVolume(Number(e.currentTarget.value))} onChange={e=>updateVolume(Number(e.currentTarget.value))} aria-label={`Volume, ${Math.round(volume*100)} percent`} aria-valuetext={`${Math.round(volume*100)} percent`} disabled={!hasAudioSource}/></div><button type="button" className="m-cast-button" aria-label="Connect playback device" title="Connect playback device" onClick={requestPlaybackTarget}><PlayerIcon name="cast"/></button><div className="m-queue-wrap"><button type="button" className={queueOpen?"m-queue-button active":"m-queue-button"} aria-label={queueOpen?"Close queue":"Open queue"} aria-expanded={queueOpen} onClick={()=>setQueueOpen(o=>!o)}><PlayerIcon name="queue"/></button>{queueOpen&&<div className="m-queue-popover" role="dialog" aria-label="Playback queue"><b>Queue</b>{queue.map(track=><button type="button" key={track.id} className={track.id===currentTrack.id?"current":""} onClick={()=>{selectTrack(track,queue,true);setQueueOpen(false)}}><span>{track.title}</span><small>{track.artist}</small></button>)}</div>}</div><div className="m-player-brand"><img src="/mocify-bird.png?v=2" alt="" aria-hidden="true"/><span><b>MOCIFY</b><small>AI Music. Infinite Possibilities.</small></span></div></div>
  </div>

  <div className="m-player-timeline"><span className="m-player-time">{formatTime(currentTime)}</span><div className={`m-waveform mocify-signature-wave${isPlaying?" is-playing":""}${hasAudioSource&&duration?" is-seekable":""}`} role="slider" tabIndex={hasAudioSource&&duration?0:-1} aria-label="Seek through track" aria-valuemin={0} aria-valuemax={Math.round(duration||0)} aria-valuenow={Math.round(currentTime)} aria-valuetext={`${formatTime(currentTime)} of ${formatTime(duration)}`} onPointerDown={beginWaveSeek} onPointerMove={dragWaveSeek} onKeyDown={event=>{if(!hasAudioSource||!duration)return;if(event.key==="ArrowRight"){event.preventDefault();seek(Math.min(duration,currentTime+5))}else if(event.key==="ArrowLeft"){event.preventDefault();seek(Math.max(0,currentTime-5))}else if(event.key==="Home"){event.preventDefault();seek(0)}else if(event.key==="End"){event.preventDefault();seek(duration)}}}><div className="m-wave-glow" aria-hidden="true"/><div className="m-wave-bars" aria-hidden="true">{spectrum.map((level,index)=>{const pct=(index/(spectrum.length-1))*100;const played=pct<=progress;const envelope=.24+.38*Math.abs(Math.sin(index*.29+.7))+.22*Math.abs(Math.sin(index*.071+1.3))+.12*Math.abs(Math.sin(index*.83));const live=isPlaying?Math.min(.26,level*.26):0;const displayLevel=Math.min(1,Math.max(.12,envelope+live));return <span className={`m-wave-column${played?" played":""}`} key={index} style={{"--level":`${Math.round(12+displayLevel*88)}%`,"--bar-index":index} as React.CSSProperties}><i/></span>})}</div><div className="m-wave-progress" aria-hidden="true" style={{width:`${progress}%`}}/><span className="m-wave-playhead" aria-hidden="true" style={{left:`${progress}%`}}/></div><span className="m-player-time">{formatTime(duration)}</span></div>

  <div className="m-mobile-progress-row"><span>{formatTime(currentTime)}</span><input className="m-progress" style={{"--progress":`${progress}%`} as React.CSSProperties} type="range" min="0" max={duration||0} step="0.1" value={Math.min(currentTime,duration||0)} onInput={e=>seek(Number(e.currentTarget.value))} onChange={e=>seek(Number(e.currentTarget.value))} aria-label={`Seek track, ${formatTime(currentTime)} of ${formatTime(duration)}`} aria-valuetext={`${formatTime(currentTime)} of ${formatTime(duration)}`} disabled={!hasAudioSource||!duration}/><span>{formatTime(duration)}</span></div>
  <span className="m-player-status" role="status">{status}</span>
 </div></section>;
}
