import type{Locale}from"./i18n/config";
export const listenerAuthCopy:Record<Locale,{welcome:string;loginTitle:string;loginText:string;email:string;password:string;signIn:string;badLogin:string;newHere:string;create:string;join:string;createTitle:string;createText:string;name:string;country:string;language:string;badSignup:string;already:string}>={
en:{welcome:"WELCOME BACK",loginTitle:"Listener login",loginText:"Sign in to your MOCIFY account.",email:"Email",password:"Password",signIn:"Sign in",badLogin:"Email or password is incorrect.",newHere:"New here?",create:"Create listener account",join:"JOIN MOCIFY",createTitle:"Create listener account",createText:"Build your library, playlists and following.",name:"Display name",country:"Country",language:"Language",badSignup:"Enter a name, valid email and a password of at least 6 characters.",already:"Already have an account?"},
nl:{welcome:"WELKOM TERUG",loginTitle:"Luisteraar inloggen",loginText:"Log in op je MOCIFY-account.",email:"E-mail",password:"Wachtwoord",signIn:"Inloggen",badLogin:"E-mail of wachtwoord is onjuist.",newHere:"Nieuw hier?",create:"Luisteraarsaccount maken",join:"WORD LID VAN MOCIFY",createTitle:"Maak je luisteraarsaccount",createText:"Bouw je bibliotheek, playlists en gevolgde artiesten.",name:"Weergavenaam",country:"Land",language:"Taal",badSignup:"Vul een naam, geldig e-mailadres en wachtwoord van minimaal 6 tekens in.",already:"Heb je al een account?"},
ro:{welcome:"BINE AI REVENIT",loginTitle:"Autentificare ascultător",loginText:"Intră în contul tău MOCIFY.",email:"E-mail",password:"Parolă",signIn:"Autentificare",badLogin:"E-mailul sau parola este incorectă.",newHere:"Ești nou aici?",create:"Creează cont de ascultător",join:"ALĂTURĂ-TE MOCIFY",createTitle:"Creează contul de ascultător",createText:"Construiește-ți biblioteca, playlisturile și lista de artiști.",name:"Nume afișat",country:"Țară",language:"Limbă",badSignup:"Introdu un nume, un e-mail valid și o parolă de cel puțin 6 caractere.",already:"Ai deja cont?"},
de:{welcome:"WILLKOMMEN ZURÜCK",loginTitle:"Hörer-Login",loginText:"Melde dich bei deinem MOCIFY-Konto an.",email:"E-Mail",password:"Passwort",signIn:"Anmelden",badLogin:"E-Mail oder Passwort ist falsch.",newHere:"Neu hier?",create:"Hörerkonto erstellen",join:"MOCIFY BEITRETEN",createTitle:"Hörerkonto erstellen",createText:"Baue deine Bibliothek, Playlists und Künstler-Follows auf.",name:"Anzeigename",country:"Land",language:"Sprache",badSignup:"Name, gültige E-Mail und mindestens 6 Zeichen langes Passwort eingeben.",already:"Schon ein Konto?"},
fr:{welcome:"BON RETOUR",loginTitle:"Connexion auditeur",loginText:"Connectez-vous à votre compte MOCIFY.",email:"E-mail",password:"Mot de passe",signIn:"Se connecter",badLogin:"E-mail ou mot de passe incorrect.",newHere:"Nouveau ici ?",create:"Créer un compte auditeur",join:"REJOINDRE MOCIFY",createTitle:"Créer votre compte auditeur",createText:"Créez votre bibliothèque, vos playlists et vos abonnements.",name:"Nom affiché",country:"Pays",language:"Langue",badSignup:"Saisissez un nom, un e-mail valide et un mot de passe d’au moins 6 caractères.",already:"Vous avez déjà un compte ?"},
es:{welcome:"BIENVENIDO DE NUEVO",loginTitle:"Acceso de oyente",loginText:"Inicia sesión en tu cuenta MOCIFY.",email:"Correo",password:"Contraseña",signIn:"Iniciar sesión",badLogin:"El correo o la contraseña son incorrectos.",newHere:"¿Eres nuevo?",create:"Crear cuenta de oyente",join:"ÚNETE A MOCIFY",createTitle:"Crea tu cuenta de oyente",createText:"Crea tu biblioteca, playlists y artistas seguidos.",name:"Nombre visible",country:"País",language:"Idioma",badSignup:"Introduce un nombre, correo válido y contraseña de al menos 6 caracteres.",already:"¿Ya tienes una cuenta?"},
it:{welcome:"BENTORNATO",loginTitle:"Accesso ascoltatore",loginText:"Accedi al tuo account MOCIFY.",email:"E-mail",password:"Password",signIn:"Accedi",badLogin:"E-mail o password non corretti.",newHere:"Nuovo qui?",create:"Crea account ascoltatore",join:"UNISCITI A MOCIFY",createTitle:"Crea il tuo account",createText:"Crea la tua libreria, playlist e artisti seguiti.",name:"Nome visualizzato",country:"Paese",language:"Lingua",badSignup:"Inserisci nome, e-mail valida e password di almeno 6 caratteri.",already:"Hai già un account?"},
pt:{welcome:"BEM-VINDO DE VOLTA",loginTitle:"Login de ouvinte",loginText:"Entre na sua conta MOCIFY.",email:"E-mail",password:"Palavra-passe",signIn:"Entrar",badLogin:"E-mail ou palavra-passe incorretos.",newHere:"Novo por aqui?",create:"Criar conta de ouvinte",join:"JUNTE-SE AO MOCIFY",createTitle:"Crie a sua conta",createText:"Crie a sua biblioteca, playlists e artistas seguidos.",name:"Nome de exibição",country:"País",language:"Idioma",badSignup:"Introduza nome, e-mail válido e palavra-passe com pelo menos 6 caracteres.",already:"Já tem conta?"},
pl:{welcome:"WITAJ PONOWNIE",loginTitle:"Logowanie słuchacza",loginText:"Zaloguj się do konta MOCIFY.",email:"E-mail",password:"Hasło",signIn:"Zaloguj",badLogin:"E-mail lub hasło są nieprawidłowe.",newHere:"Nowy użytkownik?",create:"Utwórz konto słuchacza",join:"DOŁĄCZ DO MOCIFY",createTitle:"Utwórz konto słuchacza",createText:"Twórz bibliotekę, playlisty i obserwuj artystów.",name:"Nazwa wyświetlana",country:"Kraj",language:"Język",badSignup:"Podaj nazwę, poprawny e-mail i hasło min. 6 znaków.",already:"Masz już konto?"},
tr:{welcome:"TEKRAR HOŞ GELDİN",loginTitle:"Dinleyici girişi",loginText:"MOCIFY hesabına giriş yap.",email:"E-posta",password:"Şifre",signIn:"Giriş yap",badLogin:"E-posta veya şifre yanlış.",newHere:"Yeni misin?",create:"Dinleyici hesabı oluştur",join:"MOCIFY'A KATIL",createTitle:"Dinleyici hesabını oluştur",createText:"Kitaplığını, listelerini ve takiplerini oluştur.",name:"Görünen ad",country:"Ülke",language:"Dil",badSignup:"Ad, geçerli e-posta ve en az 6 karakterlik şifre gir.",already:"Zaten hesabın var mı?"},
id:{welcome:"SELAMAT DATANG KEMBALI",loginTitle:"Login pendengar",loginText:"Masuk ke akun MOCIFY Anda.",email:"Email",password:"Kata sandi",signIn:"Masuk",badLogin:"Email atau kata sandi salah.",newHere:"Baru di sini?",create:"Buat akun pendengar",join:"GABUNG MOCIFY",createTitle:"Buat akun pendengar",createText:"Bangun pustaka, playlist, dan artis yang diikuti.",name:"Nama tampilan",country:"Negara",language:"Bahasa",badSignup:"Masukkan nama, email valid, dan kata sandi minimal 6 karakter.",already:"Sudah punya akun?"},
ja:{welcome:"おかえりなさい",loginTitle:"リスナーログイン",loginText:"MOCIFYアカウントにログインします。",email:"メール",password:"パスワード",signIn:"ログイン",badLogin:"メールまたはパスワードが正しくありません。",newHere:"初めてですか？",create:"リスナーアカウントを作成",join:"MOCIFYに参加",createTitle:"リスナーアカウントを作成",createText:"ライブラリ、プレイリスト、フォローを作成できます。",name:"表示名",country:"国",language:"言語",badSignup:"名前、有効なメール、6文字以上のパスワードを入力してください。",already:"アカウントをお持ちですか？"},
ko:{welcome:"다시 오신 것을 환영합니다",loginTitle:"리스너 로그인",loginText:"MOCIFY 계정에 로그인하세요.",email:"이메일",password:"비밀번호",signIn:"로그인",badLogin:"이메일 또는 비밀번호가 올바르지 않습니다.",newHere:"처음이신가요?",create:"리스너 계정 만들기",join:"MOCIFY 가입",createTitle:"리스너 계정 만들기",createText:"라이브러리, 플레이리스트, 팔로우를 만들어 보세요.",name:"표시 이름",country:"국가",language:"언어",badSignup:"이름, 올바른 이메일, 6자 이상의 비밀번호를 입력하세요.",already:"이미 계정이 있나요?"},
hi:{welcome:"वापसी पर स्वागत है",loginTitle:"श्रोता लॉगिन",loginText:"अपने MOCIFY खाते में लॉगिन करें।",email:"ईमेल",password:"पासवर्ड",signIn:"लॉगिन",badLogin:"ईमेल या पासवर्ड गलत है।",newHere:"यहाँ नए हैं?",create:"श्रोता खाता बनाएँ",join:"MOCIFY से जुड़ें",createTitle:"अपना श्रोता खाता बनाएँ",createText:"अपनी लाइब्रेरी, प्लेलिस्ट और फ़ॉलो बनाएं।",name:"डिस्प्ले नाम",country:"देश",language:"भाषा",badSignup:"नाम, मान्य ईमेल और कम से कम 6 अक्षरों का पासवर्ड दर्ज करें।",already:"पहले से खाता है?"}
};