"use client";

import Link from "next/link";
import { useEffect, useRef, useState, type CSSProperties } from "react";
import { formatTime, useListenerPlayer, type RepeatMode } from "./listener-player";
import {useLanguage} from "./i18n/language-provider";
import {AddToPlaylist} from "./components";

const playerCopy={
en:{repeat:["Repeat off","Repeat queue","Repeat current track"],player:"Music player",controls:"Playback controls",expand:"Expand player",minimize:"Minimize player",remove:"Remove from library",save:"Save to library",more:"More options",open:"Open track",copy:"Copy track link",shuffleOff:"Turn off shuffle",shuffleOn:"Turn on shuffle",previous:"Previous track",pause:"Pause track",play:"Play track",next:"Next track",volume:"Volume",percent:"percent",unmute:"Unmute",mute:"Mute",device:"Connect playback device",closeQueue:"Close queue",openQueue:"Open queue",queue:"Queue",nowPlaying:"Now playing",playFromQueue:"Play from queue",seek:"Seek through track",of:"of"},
nl:{repeat:["Herhalen uit","Wachtrij herhalen","Huidig nummer herhalen"],player:"Muziekspeler",controls:"Afspeelbediening",expand:"Speler uitklappen",minimize:"Speler minimaliseren",remove:"Uit bibliotheek verwijderen",save:"Opslaan in bibliotheek",more:"Meer opties",open:"Nummer openen",copy:"Link naar nummer kopiëren",shuffleOff:"Shuffle uitzetten",shuffleOn:"Shuffle aanzetten",previous:"Vorig nummer",pause:"Nummer pauzeren",play:"Nummer afspelen",next:"Volgend nummer",volume:"Volume",percent:"procent",unmute:"Geluid aan",mute:"Dempen",device:"Afspeelapparaat verbinden",closeQueue:"Wachtrij sluiten",openQueue:"Wachtrij openen",queue:"Wachtrij",nowPlaying:"Speelt nu",playFromQueue:"Afspelen uit wachtrij",seek:"Door nummer zoeken",of:"van"},
ro:{repeat:["Repetare oprită","Repetă coada","Repetă piesa curentă"],player:"Player muzical",controls:"Comenzi redare",expand:"Extinde playerul",minimize:"Minimizează playerul",remove:"Elimină din bibliotecă",save:"Salvează în bibliotecă",more:"Mai multe opțiuni",open:"Deschide piesa",copy:"Copiază linkul piesei",shuffleOff:"Oprește redarea aleatorie",shuffleOn:"Pornește redarea aleatorie",previous:"Piesa anterioară",pause:"Pauză",play:"Redă piesa",next:"Piesa următoare",volume:"Volum",percent:"procente",unmute:"Activează sunetul",mute:"Dezactivează sunetul",device:"Conectează dispozitivul de redare",closeQueue:"Închide coada",openQueue:"Deschide coada",queue:"Coadă",seek:"Navighează în piesă",of:"din"},
de:{controls:"Wiedergabesteuerung",repeat:["Wiederholen aus","Warteschlange wiederholen","Aktuellen Titel wiederholen"],player:"Musikplayer",expand:"Player erweitern",minimize:"Player minimieren",remove:"Aus Bibliothek entfernen",save:"In Bibliothek speichern",more:"Weitere Optionen",open:"Titel öffnen",copy:"Titellink kopieren",shuffleOff:"Zufallswiedergabe aus",shuffleOn:"Zufallswiedergabe an",previous:"Vorheriger Titel",pause:"Titel pausieren",play:"Titel abspielen",next:"Nächster Titel",volume:"Lautstärke",percent:"Prozent",unmute:"Ton an",mute:"Stumm",device:"Wiedergabegerät verbinden",closeQueue:"Warteschlange schließen",openQueue:"Warteschlange öffnen",queue:"Warteschlange",seek:"Im Titel suchen",of:"von"},
fr:{controls:"Commandes de lecture",repeat:["Répétition désactivée","Répéter la file","Répéter le titre"],player:"Lecteur de musique",expand:"Agrandir le lecteur",minimize:"Réduire le lecteur",remove:"Retirer de la bibliothèque",save:"Enregistrer dans la bibliothèque",more:"Plus d’options",open:"Ouvrir le titre",copy:"Copier le lien",shuffleOff:"Désactiver l’aléatoire",shuffleOn:"Activer l’aléatoire",previous:"Titre précédent",pause:"Mettre en pause",play:"Lire le titre",next:"Titre suivant",volume:"Volume",percent:"pour cent",unmute:"Activer le son",mute:"Couper le son",device:"Connecter un appareil",closeQueue:"Fermer la file",openQueue:"Ouvrir la file",queue:"File d’attente",seek:"Parcourir le titre",of:"sur"},
es:{controls:"Controles de reproducción",repeat:["Repetición desactivada","Repetir cola","Repetir pista"],player:"Reproductor de música",expand:"Expandir reproductor",minimize:"Minimizar reproductor",remove:"Eliminar de la biblioteca",save:"Guardar en la biblioteca",more:"Más opciones",open:"Abrir pista",copy:"Copiar enlace",shuffleOff:"Desactivar aleatorio",shuffleOn:"Activar aleatorio",previous:"Pista anterior",pause:"Pausar pista",play:"Reproducir pista",next:"Pista siguiente",volume:"Volumen",percent:"por ciento",unmute:"Activar sonido",mute:"Silenciar",device:"Conectar dispositivo",closeQueue:"Cerrar cola",openQueue:"Abrir cola",queue:"Cola",seek:"Buscar en la pista",of:"de"},
it:{controls:"Controlli di riproduzione",repeat:["Ripetizione disattivata","Ripeti coda","Ripeti brano"],player:"Lettore musicale",expand:"Espandi lettore",minimize:"Riduci lettore",remove:"Rimuovi dalla libreria",save:"Salva nella libreria",more:"Altre opzioni",open:"Apri brano",copy:"Copia link",shuffleOff:"Disattiva casuale",shuffleOn:"Attiva casuale",previous:"Brano precedente",pause:"Pausa",play:"Riproduci",next:"Brano successivo",volume:"Volume",percent:"percento",unmute:"Attiva audio",mute:"Silenzia",device:"Collega dispositivo",closeQueue:"Chiudi coda",openQueue:"Apri coda",queue:"Coda",seek:"Cerca nel brano",of:"di"},
pt:{controls:"Controlos de reprodução",repeat:["Repetição desligada","Repetir fila","Repetir faixa"],player:"Leitor de música",expand:"Expandir leitor",minimize:"Minimizar leitor",remove:"Remover da biblioteca",save:"Guardar na biblioteca",more:"Mais opções",open:"Abrir faixa",copy:"Copiar ligação",shuffleOff:"Desligar aleatório",shuffleOn:"Ligar aleatório",previous:"Faixa anterior",pause:"Pausar faixa",play:"Reproduzir faixa",next:"Faixa seguinte",volume:"Volume",percent:"por cento",unmute:"Ativar som",mute:"Silenciar",device:"Ligar dispositivo",closeQueue:"Fechar fila",openQueue:"Abrir fila",queue:"Fila",seek:"Procurar na faixa",of:"de"},
pl:{controls:"Sterowanie odtwarzaniem",repeat:["Powtarzanie wyłączone","Powtarzaj kolejkę","Powtarzaj utwór"],player:"Odtwarzacz muzyki",expand:"Rozwiń odtwarzacz",minimize:"Zminimalizuj odtwarzacz",remove:"Usuń z biblioteki",save:"Zapisz w bibliotece",more:"Więcej opcji",open:"Otwórz utwór",copy:"Kopiuj link",shuffleOff:"Wyłącz losowanie",shuffleOn:"Włącz losowanie",previous:"Poprzedni utwór",pause:"Wstrzymaj",play:"Odtwórz",next:"Następny utwór",volume:"Głośność",percent:"procent",unmute:"Włącz dźwięk",mute:"Wycisz",device:"Połącz urządzenie",closeQueue:"Zamknij kolejkę",openQueue:"Otwórz kolejkę",queue:"Kolejka",seek:"Przewiń utwór",of:"z"},
tr:{controls:"Oynatma kontrolleri",repeat:["Tekrar kapalı","Sırayı tekrarla","Parçayı tekrarla"],player:"Müzik çalar",expand:"Oynatıcıyı genişlet",minimize:"Oynatıcıyı küçült",remove:"Kitaplıktan kaldır",save:"Kitaplığa kaydet",more:"Daha fazla seçenek",open:"Parçayı aç",copy:"Parça bağlantısını kopyala",shuffleOff:"Karışık çalmayı kapat",shuffleOn:"Karışık çalmayı aç",previous:"Önceki parça",pause:"Duraklat",play:"Parçayı çal",next:"Sonraki parça",volume:"Ses",percent:"yüzde",unmute:"Sesi aç",mute:"Sessize al",device:"Oynatma cihazı bağla",closeQueue:"Sırayı kapat",openQueue:"Sırayı aç",queue:"Sıra",seek:"Parçada gezin",of:"/"},
id:{controls:"Kontrol pemutaran",repeat:["Ulangi mati","Ulangi antrean","Ulangi track"],player:"Pemutar musik",expand:"Perbesar pemutar",minimize:"Perkecil pemutar",remove:"Hapus dari pustaka",save:"Simpan ke pustaka",more:"Opsi lainnya",open:"Buka track",copy:"Salin tautan track",shuffleOff:"Matikan acak",shuffleOn:"Aktifkan acak",previous:"Track sebelumnya",pause:"Jeda track",play:"Putar track",next:"Track berikutnya",volume:"Volume",percent:"persen",unmute:"Aktifkan suara",mute:"Bisukan",device:"Hubungkan perangkat",closeQueue:"Tutup antrean",openQueue:"Buka antrean",queue:"Antrean",seek:"Telusuri track",of:"dari"},
ja:{controls:"再生コントロール",repeat:["リピートオフ","キューをリピート","現在の曲をリピート"],player:"音楽プレーヤー",expand:"プレーヤーを展開",minimize:"プレーヤーを最小化",remove:"ライブラリから削除",save:"ライブラリに保存",more:"その他のオプション",open:"曲を開く",copy:"曲のリンクをコピー",shuffleOff:"シャッフルをオフ",shuffleOn:"シャッフルをオン",previous:"前の曲",pause:"一時停止",play:"再生",next:"次の曲",volume:"音量",percent:"パーセント",unmute:"ミュート解除",mute:"ミュート",device:"再生デバイスを接続",closeQueue:"キューを閉じる",openQueue:"キューを開く",queue:"キュー",seek:"曲内を移動",of:"/"},
ko:{controls:"재생 컨트롤",repeat:["반복 끄기","대기열 반복","현재 곡 반복"],player:"음악 플레이어",expand:"플레이어 펼치기",minimize:"플레이어 최소화",remove:"라이브러리에서 삭제",save:"라이브러리에 저장",more:"더 많은 옵션",open:"트랙 열기",copy:"트랙 링크 복사",shuffleOff:"셔플 끄기",shuffleOn:"셔플 켜기",previous:"이전 트랙",pause:"일시정지",play:"트랙 재생",next:"다음 트랙",volume:"볼륨",percent:"퍼센트",unmute:"음소거 해제",mute:"음소거",device:"재생 장치 연결",closeQueue:"대기열 닫기",openQueue:"대기열 열기",queue:"대기열",seek:"트랙 탐색",of:"/"},
hi:{controls:"प्लेबैक नियंत्रण",repeat:["रिपीट बंद","क्यू दोहराएँ","मौजूदा ट्रैक दोहराएँ"],player:"म्यूज़िक प्लेयर",expand:"प्लेयर फैलाएँ",minimize:"प्लेयर छोटा करें",remove:"लाइब्रेरी से हटाएँ",save:"लाइब्रेरी में सेव करें",more:"और विकल्प",open:"ट्रैक खोलें",copy:"ट्रैक लिंक कॉपी करें",shuffleOff:"शफल बंद करें",shuffleOn:"शफल चालू करें",previous:"पिछला ट्रैक",pause:"ट्रैक रोकें",play:"ट्रैक चलाएँ",next:"अगला ट्रैक",volume:"वॉल्यूम",percent:"प्रतिशत",unmute:"आवाज़ चालू करें",mute:"म्यूट",device:"प्लेबैक डिवाइस जोड़ें",closeQueue:"क्यू बंद करें",openQueue:"क्यू खोलें",queue:"क्यू",seek:"ट्रैक में जाएँ",of:"में से"}
} as const;
const BAR_COUNT=220;
const idleBars=Array.from({length:BAR_COUNT},(_,index)=>.025+((index*17)%7)*.006);

function PlayerIcon({name}:{name:"heart"|"more"|"shuffle"|"prev"|"next"|"repeat"|"volume"|"cast"|"queue"|"play"|"pause"}){
 const common={width:20,height:20,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.9,strokeLinecap:"round" as const,strokeLinejoin:"round" as const,"aria-hidden":true};
 if(name==="heart")return <svg {...common}><path d="M20.8 4.6a5.4 5.4 0 0 0-7.6 0L12 5.8l-1.2-1.2a5.4 5.4 0 1 0-7.6 7.6L12 21l8.8-8.8a5.4 5.4 0 0 0 0-7.6Z"/></svg>;
 if(name==="more")return <svg {...common}><circle cx="5" cy="12" r="1.25" fill="currentColor" stroke="none"/><circle cx="12" cy="12" r="1.25" fill="currentColor" stroke="none"/><circle cx="19" cy="12" r="1.25" fill="currentColor" stroke="none"/></svg>;
 if(name==="shuffle")return <svg {...common}><path d="M3 7h3.5c2.2 0 3.3 1.2 4.3 2.8l2.4 4.1c1 1.6 2.1 3.1 4.3 3.1H21"/><path d="m18 14 3 3-3 3"/><path d="M3 17h3.5c1.7 0 2.8-.7 3.7-1.9"/><path d="M14.2 8.9c.9-1.2 1.9-1.9 3.3-1.9H21"/><path d="m18 4 3 3-3 3"/></svg>;
 if(name==="prev")return <svg {...common}><path d="M6 5v14"/><path d="m19 6-9 6 9 6V6Z" fill="currentColor" stroke="none"/></svg>;
 if(name==="next")return <svg {...common}><path d="M18 5v14"/><path d="m5 6 9 6-9 6V6Z" fill="currentColor" stroke="none"/></svg>;
 if(name==="repeat")return <svg {...common}><path d="M17 2.8 20.2 6 17 9.2"/><path d="M3.8 10V8.5A2.5 2.5 0 0 1 6.3 6h13.3"/><path d="m7 21.2-3.2-3.2L7 14.8"/><path d="M20.2 14v1.5a2.5 2.5 0 0 1-2.5 2.5H4.4"/></svg>;
 if(name==="volume")return <svg {...common}><path d="M4 9v6h4l5 4V5L8 9H4Z"/><path d="M16 9.2a4 4 0 0 1 0 5.6"/></svg>;
 if(name==="cast")return <svg {...common}><path d="M4 18a2 2 0 0 1 2 2"/><path d="M4 14a6 6 0 0 1 6 6"/><path d="M4 10a10 10 0 0 1 10 10"/><path d="M8 5h9a3 3 0 0 1 3 3v8"/></svg>;
 if(name==="queue")return <svg {...common}><path d="M10 7h10M10 12h10M10 17h10"/><circle cx="5" cy="7" r="1" fill="currentColor" stroke="none"/><circle cx="5" cy="12" r="1" fill="currentColor" stroke="none"/><circle cx="5" cy="17" r="1" fill="currentColor" stroke="none"/></svg>;
 if(name==="pause")return <svg {...common} width="22" height="22"><path d="M9 6v12M15 6v12" strokeWidth="2.6"/></svg>;
 return <svg {...common} width="22" height="22"><path d="m9 6 9 6-9 6V6Z" fill="currentColor" stroke="none"/></svg>;
}

export default function Player(){
 const{locale}=useLanguage();const t=playerCopy[locale as keyof typeof playerCopy]??playerCopy.en;const[queueOpen,setQueueOpen]=useState(false),[moreOpen,setMoreOpen]=useState(false),[minimized,setMinimized]=useState(false),[miniPos,setMiniPos]=useState({top:0,left:18,width:170}),[savedIds,setSavedIds]=useState<string[]>([]),[spectrum,setSpectrum]=useState(idleBars);const lastAudibleVolume=useRef(1);
 const{currentTrack,queue,isPlaying,currentTime,duration,volume,shuffle,repeatMode,hasAudioSource,status,togglePlay,nextTrack,previousTrack,seek,setVolume,toggleShuffle,cycleRepeat,requestPlaybackTarget,selectTrack,sampleSpectrum}=useListenerPlayer();
 const progress=duration>0?Math.min(100,(currentTime/duration)*100):0,repeatLabel=t.repeat[repeatMode==="off"?0:repeatMode==="queue"?1:2];
 const isSaved=savedIds.includes(currentTrack.id);
 const persistSaved=(ids:string[])=>{setSavedIds(ids);try{localStorage.setItem("mocify-saved-track-ids",JSON.stringify(ids))}catch{}};
 const toggleSaved=()=>{const next=isSaved?savedIds.filter(id=>id!==currentTrack.id):[...savedIds,currentTrack.id];persistSaved(next)};
 const copyTrackLink=async()=>{const path=currentTrack.href??`/explore#${currentTrack.id}`;const url=typeof window!=="undefined"?new URL(path,window.location.origin).toString():path;try{await navigator.clipboard.writeText(url)}catch{}setMoreOpen(false)};
 const updateVolume=(value:number)=>{if(value>0)lastAudibleVolume.current=value;setVolume(value)};
 const toggleMute=()=>{if(volume>0){lastAudibleVolume.current=volume;setVolume(0)}else setVolume(lastAudibleVolume.current||.8)};
 const seekFromPointer=(event:React.PointerEvent<HTMLElement>)=>{if(!hasAudioSource||!duration)return;const rect=event.currentTarget.getBoundingClientRect();const ratio=Math.max(0,Math.min(1,(event.clientX-rect.left)/rect.width));seek(ratio*duration)};
 const beginWaveSeek=(event:React.PointerEvent<HTMLDivElement>)=>{if(!hasAudioSource||!duration)return;event.currentTarget.setPointerCapture?.(event.pointerId);seekFromPointer(event)};
 const dragWaveSeek=(event:React.PointerEvent<HTMLDivElement>)=>{if(event.currentTarget.hasPointerCapture?.(event.pointerId))seekFromPointer(event)};
 useEffect(()=>{try{const raw=localStorage.getItem("mocify-saved-track-ids");const parsed=raw?JSON.parse(raw):[];if(Array.isArray(parsed))setSavedIds(parsed.filter((id):id is string=>typeof id==="string"))}catch{}},[]);
 useEffect(()=>{try{setMinimized(localStorage.getItem("mocify-listener-player-minimized")==="1")}catch{}},[]);
 const setMinimizedPersist=(value:boolean)=>{setMinimized(value);try{localStorage.setItem("mocify-listener-player-minimized",value?"1":"0")}catch{}};
 useEffect(()=>{if(!minimized)return;const place=()=>{const cta=document.querySelector(".listener-creator-cta") as HTMLElement|null;if(!cta)return;const rect=cta.getBoundingClientRect();const styles=getComputedStyle(cta);const borderLeft=parseFloat(styles.borderLeftWidth)||0,borderRight=parseFloat(styles.borderRightWidth)||0;const targetWidth=Math.round(rect.width+borderLeft+borderRight);setMiniPos({top:Math.round(rect.bottom+14),left:Math.round(rect.left),width:targetWidth})};place();addEventListener("resize",place);addEventListener("scroll",place,{passive:true});const timer=setTimeout(place,80);return()=>{clearTimeout(timer);removeEventListener("resize",place);removeEventListener("scroll",place)}},[minimized]);
 useEffect(()=>{let frame=0,last=0;const tick=(now:number)=>{if(isPlaying&&now-last>16){const live=sampleSpectrum(BAR_COUNT);setSpectrum(previous=>live.map((value,index)=>{const old=previous[index]??.025;const bass=index<BAR_COUNT*.22;const raw=Math.max(0,(value-(bass?.055:.075))/(bass?.72:.64));const gate=Math.max(0,Math.min(1,raw));const contrast=Math.pow(gate,bass?.72:.92);const accent=((index*13)%11===0?1.18:((index*7)%9===0?1.08:1));const target=Math.min(1,contrast*(bass?1.55:1.30)*accent);const attack=target>old?.96:.34;const next=old+(target-old)*attack;return Math.max(.018,Math.min(1,next))}));last=now}else if(!isPlaying&&now-last>55){setSpectrum(previous=>previous.map((value,index)=>value+(idleBars[index]-value)*.22));last=now}frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[isPlaying,sampleSpectrum]);
 return <section className={minimized?"m-player minimized":"m-player"} style={minimized?({"--listener-mini-top":`${miniPos.top}px`,"--listener-mini-left":`${miniPos.left}px`,"--listener-mini-width":`${miniPos.width}px`} as CSSProperties):undefined} aria-label={t.player}><div className="m-player-accent" aria-hidden="true"/><div className="m-player-inner"><button type="button" className="m-player-minimize" onClick={()=>setMinimizedPersist(!minimized)} aria-label={minimized?t.expand:t.minimize} title={minimized?t.expand:t.minimize}>{minimized?"↗":"—"}</button>
  <div className="m-player-top">
   <div className="m-player-track-area"><Link className="m-player-track" href={currentTrack.href??"/explore"}><span className={`m-player-cover ${currentTrack.art}`} aria-hidden="true"/><span className="m-player-track-copy"><b>{currentTrack.title}</b><small>{currentTrack.artist}</small></span></Link><AddToPlaylist trackId={currentTrack.id}/><button type="button" className={isSaved?"m-player-save active":"m-player-save"} aria-label={`${isSaved?t.remove:t.save}: ${currentTrack.title}`} aria-pressed={isSaved} onClick={toggleSaved}><PlayerIcon name="heart"/></button><div className="m-player-more-wrap"><button type="button" className={moreOpen?"m-player-more active":"m-player-more"} aria-label={t.more} aria-expanded={moreOpen} onClick={()=>setMoreOpen(v=>!v)}><PlayerIcon name="more"/></button>{moreOpen&&<div className="m-player-more-menu" role="menu"><button type="button" role="menuitem" onClick={()=>{toggleSaved();setMoreOpen(false)}}>{isSaved?t.remove:t.save}</button><Link role="menuitem" href={currentTrack.href??`/explore#${currentTrack.id}`} onClick={()=>setMoreOpen(false)}>{t.open}</Link><button type="button" role="menuitem" onClick={copyTrackLink}>{t.copy}</button></div>}</div></div>

   <div className="m-player-center"><div className="m-controls" aria-label={t.controls}><button type="button" className={shuffle?"m-utility active":"m-utility"} aria-label={shuffle?t.shuffleOff:t.shuffleOn} aria-pressed={shuffle} onClick={toggleShuffle}><PlayerIcon name="shuffle"/></button><button type="button" aria-label={t.previous} onClick={previousTrack} disabled={queue.length<2}><PlayerIcon name="prev"/></button><button type="button" aria-label={isPlaying?t.pause:t.play} onClick={togglePlay} disabled={!hasAudioSource} className="m-play"><PlayerIcon name={isPlaying?"pause":"play"}/></button><button type="button" aria-label={t.next} onClick={nextTrack} disabled={queue.length<2}><PlayerIcon name="next"/></button><button type="button" className={repeatMode!=="off"?"m-utility active":"m-utility"} aria-label={repeatLabel} aria-pressed={repeatMode!=="off"} onClick={cycleRepeat} disabled={!hasAudioSource}><PlayerIcon name="repeat"/></button></div></div>

   <div className="m-player-tools"><div className="m-volume" aria-label={`${t.volume}, ${Math.round(volume*100)} ${t.percent}`}><button type="button" className="m-volume-mute" onClick={toggleMute} disabled={!hasAudioSource} aria-label={volume===0?t.unmute:t.mute} title={volume===0?t.unmute:t.mute}><PlayerIcon name="volume"/></button><input type="range" min="0" max="1" step="0.01" value={volume} onInput={e=>updateVolume(Number(e.currentTarget.value))} onChange={e=>updateVolume(Number(e.currentTarget.value))} aria-label={`${t.volume}, ${Math.round(volume*100)} ${t.percent}`} aria-valuetext={`${Math.round(volume*100)} ${t.percent}`} disabled={!hasAudioSource}/></div><button type="button" className="m-cast-button" aria-label={t.device} title={t.device} onClick={requestPlaybackTarget}><PlayerIcon name="cast"/></button><div className="m-queue-wrap"><button type="button" className={queueOpen?"m-queue-button active":"m-queue-button"} aria-label={queueOpen?t.closeQueue:t.openQueue} aria-expanded={queueOpen} onClick={()=>setQueueOpen(o=>!o)}><PlayerIcon name="queue"/></button>{queueOpen&&<div className="m-queue-popover" role="dialog" aria-label={t.queue}><div className="m-queue-head"><b>{t.queue}</b><small>{queue.length}</small></div><div className="m-queue-list">{queue.map((track,index)=>{const current=track.id===currentTrack.id;return <button type="button" key={track.id} className={current?"current":""} aria-label={`${current?((t as any).nowPlaying??t.queue):((t as any).playFromQueue??t.play)}: ${track.title}`} onClick={()=>{selectTrack(track,queue,true);setQueueOpen(false)}}><span className={`m-queue-art ${track.art}`} aria-hidden="true"/><span className="m-queue-copy"><b>{track.title}</b><small>{track.artist}</small></span><span className="m-queue-index">{current&&isPlaying?"Ⅱ":index+1}</span></button>})}</div></div>}</div><div className="m-player-brand"><img src="/mocify-bird.png?v=2" alt="" aria-hidden="true"/><span><b>MOCIFY</b><small>AI Music. Infinite Possibilities.</small></span></div><div className="m-player-mini-controls"><button type="button" aria-label={t.previous} onClick={previousTrack} disabled={queue.length<2}><PlayerIcon name="prev"/></button><button type="button" className="m-player-mini-play" aria-label={isPlaying?t.pause:t.play} onClick={togglePlay} disabled={!hasAudioSource}><PlayerIcon name={isPlaying?"pause":"play"}/></button><button type="button" aria-label={t.next} onClick={nextTrack} disabled={queue.length<2}><PlayerIcon name="next"/></button></div></div>
  </div>

  <div className="m-player-timeline"><span className="m-player-time">{formatTime(currentTime)}</span><div className={`m-waveform mocify-signature-wave${isPlaying?" is-playing":""}${hasAudioSource&&duration?" is-seekable":""}`} role="slider" tabIndex={hasAudioSource&&duration?0:-1} aria-label={t.seek} aria-valuemin={0} aria-valuemax={Math.round(duration||0)} aria-valuenow={Math.round(currentTime)} aria-valuetext={`${formatTime(currentTime)} ${t.of} ${formatTime(duration)}`} onPointerDown={beginWaveSeek} onPointerMove={dragWaveSeek} onKeyDown={event=>{if(!hasAudioSource||!duration)return;if(event.key==="ArrowRight"){event.preventDefault();seek(Math.min(duration,currentTime+5))}else if(event.key==="ArrowLeft"){event.preventDefault();seek(Math.max(0,currentTime-5))}else if(event.key==="Home"){event.preventDefault();seek(0)}else if(event.key==="End"){event.preventDefault();seek(duration)}}}><div className="m-wave-glow" aria-hidden="true"/><div className="m-wave-bars" aria-hidden="true">{spectrum.map((level,index)=>{const pct=(index/(spectrum.length-1))*100;const played=pct<=progress;const envelope=.24+.38*Math.abs(Math.sin(index*.29+.7))+.22*Math.abs(Math.sin(index*.071+1.3))+.12*Math.abs(Math.sin(index*.83));const live=isPlaying?Math.min(.26,level*.26):0;const displayLevel=Math.min(1,Math.max(.12,envelope+live));return <span className={`m-wave-column${played?" played":""}`} key={index} style={{"--level":`${Math.round(12+displayLevel*88)}%`,"--bar-index":index} as React.CSSProperties}><i/></span>})}</div><div className="m-wave-progress" aria-hidden="true" style={{width:`${progress}%`}}/><span className="m-wave-playhead" aria-hidden="true" style={{left:`${progress}%`}}/></div><span className="m-player-time">{formatTime(duration)}</span></div>

  <div className="m-mobile-progress-row"><span>{formatTime(currentTime)}</span><input className="m-progress" style={{"--progress":`${progress}%`} as React.CSSProperties} type="range" min="0" max={duration||0} step="0.1" value={Math.min(currentTime,duration||0)} onInput={e=>seek(Number(e.currentTarget.value))} onChange={e=>seek(Number(e.currentTarget.value))} aria-label={`${t.seek}, ${formatTime(currentTime)} ${t.of} ${formatTime(duration)}`} aria-valuetext={`${formatTime(currentTime)} ${t.of} ${formatTime(duration)}`} disabled={!hasAudioSource||!duration}/><span>{formatTime(duration)}</span></div>
  <span className="m-player-status" role="status">{status}</span>
 </div></section>;
}
