"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { formatTime, useListenerPlayer, type RepeatMode } from "./listener-player";

const repeatLabels: Record<RepeatMode,string>={off:"Repeat off",queue:"Repeat queue",track:"Repeat current track"};
const BAR_COUNT=56;
const idleBars=Array.from({length:BAR_COUNT},(_,index)=>.025+((index*17)%7)*.006);

export default function Player(){
 const[queueOpen,setQueueOpen]=useState(false),[spectrum,setSpectrum]=useState(idleBars);const lastAudibleVolume=useRef(1);
 const{currentTrack,queue,isPlaying,currentTime,duration,volume,shuffle,repeatMode,autoplay,hasAudioSource,status,togglePlay,nextTrack,previousTrack,seek,setVolume,toggleShuffle,cycleRepeat,toggleAutoplay,selectTrack,sampleSpectrum}=useListenerPlayer();
 const progress=duration>0?Math.min(100,(currentTime/duration)*100):0,repeatLabel=repeatLabels[repeatMode];
 const updateVolume=(value:number)=>{if(value>0)lastAudibleVolume.current=value;setVolume(value)};
 const toggleMute=()=>{if(volume>0){lastAudibleVolume.current=volume;setVolume(0)}else setVolume(lastAudibleVolume.current||.8)};
 const seekFromPointer=(event:React.PointerEvent<HTMLElement>)=>{if(!hasAudioSource||!duration)return;const rect=event.currentTarget.getBoundingClientRect();const ratio=Math.max(0,Math.min(1,(event.clientX-rect.left)/rect.width));seek(ratio*duration)};
 const beginWaveSeek=(event:React.PointerEvent<HTMLDivElement>)=>{if(!hasAudioSource||!duration)return;event.currentTarget.setPointerCapture?.(event.pointerId);seekFromPointer(event)};
 const dragWaveSeek=(event:React.PointerEvent<HTMLDivElement>)=>{if(event.currentTarget.hasPointerCapture?.(event.pointerId))seekFromPointer(event)};
 useEffect(()=>{let frame=0,last=0;const tick=(now:number)=>{if(isPlaying&&now-last>16){const live=sampleSpectrum(BAR_COUNT);setSpectrum(previous=>live.map((value,index)=>{const old=previous[index]??.025;const bass=index<BAR_COUNT*.22;const raw=Math.max(0,(value-(bass?.055:.075))/(bass?.72:.64));const gate=Math.max(0,Math.min(1,raw));const contrast=Math.pow(gate,bass?.72:.92);const accent=((index*13)%11===0?1.18:((index*7)%9===0?1.08:1));const target=Math.min(1,contrast*(bass?1.55:1.30)*accent);const attack=target>old?.96:.34;const next=old+(target-old)*attack;return Math.max(.018,Math.min(1,next))}));last=now}else if(!isPlaying&&now-last>55){setSpectrum(previous=>previous.map((value,index)=>value+(idleBars[index]-value)*.22));last=now}frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[isPlaying,sampleSpectrum]);
 return <section className="m-player" aria-label="Music player"><div className="m-player-accent" aria-hidden="true"/><div className="m-player-inner">
  <div className="m-player-track-area"><Link className="m-player-track" href={currentTrack.href??"/explore"}><span className={`m-player-cover ${currentTrack.art}`} aria-hidden="true"/><span className="m-player-track-copy"><b>{currentTrack.title}</b><small>{currentTrack.artist}</small></span></Link><Link href="/library" className="m-player-save" aria-label={`Save ${currentTrack.title} to library`}>♡</Link></div>
  <div className="m-player-wave-area"><div className={`m-waveform mocify-signature-wave${isPlaying?" is-playing":""}${hasAudioSource&&duration?" is-seekable":""}`} role="slider" tabIndex={hasAudioSource&&duration?0:-1} aria-label="Seek through track" aria-valuemin={0} aria-valuemax={Math.round(duration||0)} aria-valuenow={Math.round(currentTime)} aria-valuetext={`${formatTime(currentTime)} of ${formatTime(duration)}`} onPointerDown={beginWaveSeek} onPointerMove={dragWaveSeek} onKeyDown={event=>{if(!hasAudioSource||!duration)return;if(event.key==="ArrowRight"){event.preventDefault();seek(Math.min(duration,currentTime+5))}else if(event.key==="ArrowLeft"){event.preventDefault();seek(Math.max(0,currentTime-5))}else if(event.key==="Home"){event.preventDefault();seek(0)}else if(event.key==="End"){event.preventDefault();seek(duration)}}}><div className="m-wave-glow" aria-hidden="true"/><div className="m-wave-bars" aria-hidden="true">{spectrum.map((level,index)=>{const pct=(index/(spectrum.length-1))*100;const played=pct<=progress;return <span className={`m-wave-column${played?" played":""}`} key={index} style={{"--level":`${Math.round(2+level*98)}%`,"--bar-index":index} as React.CSSProperties}><i/><i className="reflection"/></span>})}</div><div className="m-wave-progress" aria-hidden="true" style={{width:`${progress}%`}}/><span className="m-wave-playhead" aria-hidden="true" style={{left:`${progress}%`}}/></div><div className="m-progress-row"><span>{formatTime(currentTime)}</span><input className="m-progress" style={{"--progress":`${progress}%`} as React.CSSProperties} type="range" min="0" max={duration||0} step="0.1" value={Math.min(currentTime,duration||0)} onInput={e=>seek(Number(e.currentTarget.value))} onChange={e=>seek(Number(e.currentTarget.value))} aria-label={`Seek track, ${formatTime(currentTime)} of ${formatTime(duration)}`} aria-valuetext={`${formatTime(currentTime)} of ${formatTime(duration)}`} disabled={!hasAudioSource||!duration}/><span>{formatTime(duration)}</span></div></div>
  <div className="m-player-center"><div className="m-controls" aria-label="Playback controls"><button type="button" className={shuffle?"m-utility active":"m-utility"} aria-label={shuffle?"Turn off shuffle":"Turn on shuffle"} aria-pressed={shuffle} onClick={toggleShuffle}>⤨</button><button type="button" aria-label="Previous track" onClick={previousTrack} disabled={queue.length<2}>◀</button><button type="button" aria-label={isPlaying?"Pause track":"Play track"} onClick={togglePlay} disabled={!hasAudioSource} className="m-play">{isPlaying?"Ⅱ":"▶"}</button><button type="button" aria-label="Next track" onClick={nextTrack} disabled={queue.length<2}>▶</button><button type="button" className={repeatMode!=="off"?"m-utility active":"m-utility"} aria-label={repeatLabel} aria-pressed={repeatMode!=="off"} onClick={cycleRepeat} disabled={!hasAudioSource}>{repeatMode==="track"?"↻1":"↻"}</button></div></div>
  <div className="m-player-tools"><button type="button" className={`m-mobile-utility${shuffle?" active":""}`} aria-label={shuffle?"Turn off shuffle":"Turn on shuffle"} aria-pressed={shuffle} onClick={toggleShuffle}>⤨</button><button type="button" className={`m-mobile-utility${repeatMode!=="off"?" active":""}`} aria-label={repeatLabel} aria-pressed={repeatMode!=="off"} onClick={cycleRepeat} disabled={!hasAudioSource}>{repeatMode==="track"?"↻1":"↻"}</button><div className="m-volume" aria-label={`Volume, ${Math.round(volume*100)} percent`}><button type="button" className="m-volume-mute" onClick={toggleMute} disabled={!hasAudioSource} aria-label={volume===0?"Unmute":"Mute"} title={volume===0?"Unmute":"Mute"}>{volume===0?"◯":"◖"}</button><input type="range" min="0" max="1" step="0.01" value={volume} onInput={e=>updateVolume(Number(e.currentTarget.value))} onChange={e=>updateVolume(Number(e.currentTarget.value))} aria-label={`Volume, ${Math.round(volume*100)} percent`} aria-valuetext={`${Math.round(volume*100)} percent`} disabled={!hasAudioSource}/></div><button type="button" className={autoplay?"m-tool-toggle active":"m-tool-toggle"} aria-label={autoplay?"Turn off autoplay":"Turn on autoplay"} aria-pressed={autoplay} title={autoplay?"Autoplay is on — play the next track automatically":"Autoplay is off — stop after the current track"} onClick={toggleAutoplay}>AUTO<span className="m-auto-state" aria-hidden="true">{autoplay?" ON":" OFF"}</span></button><div className="m-queue-wrap"><button type="button" className={queueOpen?"m-queue-button active":"m-queue-button"} aria-label={queueOpen?"Close queue":"Open queue"} aria-expanded={queueOpen} onClick={()=>setQueueOpen(o=>!o)}>☷</button>{queueOpen&&<div className="m-queue-popover" role="dialog" aria-label="Playback queue"><b>Queue</b>{queue.map(track=><button type="button" key={track.id} className={track.id===currentTrack.id?"current":""} onClick={()=>{selectTrack(track,queue,true);setQueueOpen(false)}}><span>{track.title}</span><small>{track.artist}</small></button>)}</div>}</div><div className="m-player-brand"><img src="/mocify-bird.png?v=2" alt="" aria-hidden="true"/><span><b>MOCIFY</b><small>AI Music. Infinite Possibilities.</small></span></div></div><span className="m-player-status" role="status">{status}</span>
 </div></section>;
}
