"use client";
import {Shell} from "../components";
import {useLanguage} from "../i18n/language-provider";
const copy={
en:{title:"Terms",p1:"These platform terms will govern accounts, uploads, listening features and creator tools. Users remain responsible for the content and rights associated with material they upload.",p2:"Commercial, payment and distribution terms must be accepted before those services are activated."},
nl:{title:"Voorwaarden",p1:"Deze platformvoorwaarden gelden voor accounts, uploads, luisterfuncties en tools voor makers. Gebruikers blijven verantwoordelijk voor de inhoud en de rechten van materiaal dat zij uploaden.",p2:"Commerciële, betalings- en distributievoorwaarden moeten worden geaccepteerd voordat die diensten worden geactiveerd."},
ro:{title:"Termeni",p1:"Acești termeni ai platformei vor reglementa conturile, încărcările, funcțiile de ascultare și instrumentele pentru creatori. Utilizatorii rămân responsabili pentru conținutul și drepturile materialelor pe care le încarcă.",p2:"Termenii comerciali, de plată și distribuție trebuie acceptați înainte de activarea acelor servicii."},
de:{title:"Bedingungen",p1:"Diese Plattformbedingungen regeln Konten, Uploads, Hörfunktionen und Creator-Tools. Nutzer bleiben für Inhalte und Rechte an hochgeladenem Material verantwortlich.",p2:"Geschäfts-, Zahlungs- und Vertriebsbedingungen müssen akzeptiert werden, bevor diese Dienste aktiviert werden."},
fr:{title:"Conditions",p1:"Ces conditions régiront les comptes, les imports, les fonctions d’écoute et les outils pour créateurs. Les utilisateurs restent responsables du contenu et des droits liés aux éléments qu’ils publient.",p2:"Les conditions commerciales, de paiement et de distribution doivent être acceptées avant l’activation de ces services."},
es:{title:"Términos",p1:"Estos términos regirán las cuentas, las subidas, las funciones de escucha y las herramientas para creadores. Los usuarios siguen siendo responsables del contenido y de los derechos del material que suben.",p2:"Los términos comerciales, de pago y distribución deberán aceptarse antes de activar esos servicios."},
it:{title:"Termini",p1:"Questi termini regolano account, upload, funzioni di ascolto e strumenti per creator. Gli utenti restano responsabili dei contenuti e dei diritti relativi al materiale caricato.",p2:"I termini commerciali, di pagamento e distribuzione devono essere accettati prima dell’attivazione di tali servizi."},
pt:{title:"Termos",p1:"Estes termos regem contas, carregamentos, funcionalidades de audição e ferramentas para criadores. Os utilizadores continuam responsáveis pelo conteúdo e pelos direitos do material que carregam.",p2:"Os termos comerciais, de pagamento e distribuição devem ser aceites antes da ativação desses serviços."},
pl:{title:"Warunki",p1:"Niniejsze warunki regulują konta, przesyłanie treści, funkcje słuchania i narzędzia dla twórców. Użytkownicy pozostają odpowiedzialni za treści i prawa związane z przesyłanymi materiałami.",p2:"Warunki handlowe, płatności i dystrybucji muszą zostać zaakceptowane przed uruchomieniem tych usług."},
tr:{title:"Koşullar",p1:"Bu platform koşulları hesapları, yüklemeleri, dinleme özelliklerini ve üretici araçlarını düzenler. Kullanıcılar yükledikleri içerik ve ilgili haklardan sorumlu olmaya devam eder.",p2:"Ticari, ödeme ve dağıtım koşulları bu hizmetler etkinleştirilmeden önce kabul edilmelidir."},
id:{title:"Ketentuan",p1:"Ketentuan platform ini mengatur akun, unggahan, fitur mendengarkan, dan alat kreator. Pengguna tetap bertanggung jawab atas konten dan hak yang terkait dengan materi yang mereka unggah.",p2:"Ketentuan komersial, pembayaran, dan distribusi harus disetujui sebelum layanan tersebut diaktifkan."},
ja:{title:"利用規約",p1:"本プラットフォーム規約は、アカウント、アップロード、再生機能、クリエイターツールを対象とします。ユーザーはアップロードする素材の内容および権利について引き続き責任を負います。",p2:"商用、支払い、配信に関する条件は、それらのサービスを有効にする前に同意する必要があります。"},
ko:{title:"이용약관",p1:"본 플랫폼 약관은 계정, 업로드, 청취 기능 및 크리에이터 도구에 적용됩니다. 사용자는 업로드하는 자료의 콘텐츠와 권리에 대해 계속 책임을 집니다.",p2:"상업, 결제 및 배포 관련 조건은 해당 서비스를 활성화하기 전에 동의해야 합니다."},
hi:{title:"नियम",p1:"ये प्लेटफ़ॉर्म नियम खातों, अपलोड, सुनने की सुविधाओं और क्रिएटर टूल्स पर लागू होंगे। उपयोगकर्ता अपने अपलोड किए गए सामग्री और उससे जुड़े अधिकारों के लिए जिम्मेदार रहेंगे।",p2:"व्यावसायिक, भुगतान और वितरण संबंधी शर्तों को उन सेवाओं के सक्रिय होने से पहले स्वीकार करना होगा।"}
} as const;
export default function Terms(){const{locale}=useLanguage();const t=(copy as any)[locale]??copy.en;return <Shell><main className="page-wrap legal-page"><p className="page-kicker">MOCIFY</p><h1>{t.title}</h1><p>{t.p1}</p><p>{t.p2}</p></main></Shell>}