"use client";
import Link from"next/link";import{useSearchParams}from"next/navigation";import{useEffect,useMemo,useState,type FormEvent}from"react";import{ArtistPortalShell}from"../../artist-components";import ArtistDashboardLayout from"../../artist-dashboard-layout";import{ACTIVE_ARTIST_KEY,MANAGED_ARTISTS_KEY,ensurePrimaryArtist,getStoredArtistPlan,hasArtistFeature,readManagedArtists,setActiveArtist,type ManagedArtist,type ArtistPlanTier}from"../../artist-access";import{useLanguage}from"../../i18n/language-provider";import{releases}from"../../data";import styles from"./artists.module.css";
const copy={en:{kicker:"ARTIST PRO / MAX",title:"My Artists",intro:"Create and manage multiple AI artist identities from one MOCIFY account.",add:"Create artist",name:"Artist name",genre:"Genre / sound",concept:"Artist concept",namePh:"e.g. Nova Vale",genrePh:"e.g. Dark pop / R&B",conceptPh:"Short description of the identity, style or world...",save:"Add artist",cancel:"Cancel",active:"ACTIVE",primary:"PRIMARY",switch:"Make active",remove:"Remove",empty:"No artists match your search.",freeTitle:"Multiple artists are part of Artist Pro",freeText:"Artist Free includes one primary artist profile. Upgrade to Artist Pro or Artist Max to create and manage multiple artists from the same account.",upgrade:"View Artist Pro",back:"Back to Dashboard",search:"Search your artists",account:"One account · multiple artist identities"},nl:{kicker:"ARTIST PRO / MAX",title:"Mijn artiesten",intro:"Maak en beheer meerdere AI-artiestidentiteiten vanuit één MOCIFY-account.",add:"Artiest maken",name:"Artiestennaam",genre:"Genre / sound",concept:"Artiestconcept",namePh:"bijv. Nova Vale",genrePh:"bijv. Dark pop / R&B",conceptPh:"Korte beschrijving van identiteit, stijl of wereld...",save:"Artiest toevoegen",cancel:"Annuleren",active:"ACTIEF",primary:"PRIMAIR",switch:"Actief maken",remove:"Verwijderen",empty:"Geen artiesten gevonden.",freeTitle:"Meerdere artiesten horen bij Artist Pro",freeText:"Artist Free bevat één primair artiestprofiel. Upgrade naar Artist Pro of Artist Max om meerdere artiesten vanuit hetzelfde account te maken en beheren.",upgrade:"Bekijk Artist Pro",back:"Terug naar Dashboard",search:"Zoek in je artiesten",account:"Eén account · meerdere artiestidentiteiten"},ro:{kicker:"ARTIST PRO / MAX",title:"Artiștii mei",intro:"Creează și gestionează mai multe identități de artist AI dintr-un singur cont MOCIFY.",add:"Creează artist",name:"Nume artist",genre:"Gen / sound",concept:"Concept artist",namePh:"ex. Nova Vale",genrePh:"ex. Dark pop / R&B",conceptPh:"Descriere scurtă a identității, stilului sau universului...",save:"Adaugă artist",cancel:"Anulează",active:"ACTIV",primary:"PRINCIPAL",switch:"Setează activ",remove:"Șterge",empty:"Nu există artiști pentru această căutare.",freeTitle:"Mai mulți artiști fac parte din Artist Pro",freeText:"Artist Free include un singur profil principal. Treci la Artist Pro sau Artist Max pentru a crea și gestiona mai mulți artiști din același cont.",upgrade:"Vezi Artist Pro",back:"Înapoi la Dashboard",search:"Caută în artiștii tăi",account:"Un cont · mai multe identități de artist"},
de:{kicker:"ARTIST PRO / MAX",title:"Meine Künstler",intro:"Erstelle und verwalte mehrere KI-Künstleridentitäten in einem MOCIFY-Konto.",add:"Künstler erstellen",name:"Künstlername",genre:"Genre / Sound",concept:"Künstlerkonzept",namePh:"z. B. Nova Vale",genrePh:"z. B. Dark Pop / R&B",conceptPh:"Kurze Beschreibung von Identität, Stil oder Welt...",save:"Künstler hinzufügen",cancel:"Abbrechen",active:"AKTIV",primary:"PRIMÄR",switch:"Aktiv setzen",remove:"Entfernen",empty:"Keine Künstler gefunden.",freeTitle:"Mehrere Künstler sind Teil von Artist Pro",freeText:"Artist Free enthält ein primäres Künstlerprofil. Upgrade auf Artist Pro oder Max für mehrere Künstler.",upgrade:"Artist Pro ansehen",back:"Zurück zum Dashboard",search:"Deine Künstler durchsuchen",account:"Ein Konto · mehrere Künstleridentitäten"},
fr:{kicker:"ARTIST PRO / MAX",title:"Mes artistes",intro:"Créez et gérez plusieurs identités d’artistes IA depuis un seul compte MOCIFY.",add:"Créer un artiste",name:"Nom d’artiste",genre:"Genre / son",concept:"Concept artiste",namePh:"ex. Nova Vale",genrePh:"ex. Dark pop / R&B",conceptPh:"Brève description de l’identité, du style ou de l’univers...",save:"Ajouter l’artiste",cancel:"Annuler",active:"ACTIF",primary:"PRINCIPAL",switch:"Rendre actif",remove:"Supprimer",empty:"Aucun artiste trouvé.",freeTitle:"Plusieurs artistes font partie d’Artist Pro",freeText:"Artist Free comprend un profil principal. Passez à Artist Pro ou Max pour gérer plusieurs artistes.",upgrade:"Voir Artist Pro",back:"Retour au Dashboard",search:"Rechercher vos artistes",account:"Un compte · plusieurs identités d’artiste"},
es:{kicker:"ARTIST PRO / MAX",title:"Mis artistas",intro:"Crea y gestiona varias identidades de artista IA desde una sola cuenta MOCIFY.",add:"Crear artista",name:"Nombre artístico",genre:"Género / sonido",concept:"Concepto del artista",namePh:"p. ej. Nova Vale",genrePh:"p. ej. Dark pop / R&B",conceptPh:"Breve descripción de la identidad, estilo o universo...",save:"Añadir artista",cancel:"Cancelar",active:"ACTIVO",primary:"PRINCIPAL",switch:"Hacer activo",remove:"Eliminar",empty:"No se encontraron artistas.",freeTitle:"Varios artistas forman parte de Artist Pro",freeText:"Artist Free incluye un perfil principal. Mejora a Artist Pro o Max para crear y gestionar varios artistas.",upgrade:"Ver Artist Pro",back:"Volver al panel",search:"Buscar tus artistas",account:"Una cuenta · varias identidades de artista"},
it:{kicker:"ARTIST PRO / MAX",title:"I miei artisti",intro:"Crea e gestisci più identità artistiche AI da un solo account MOCIFY.",add:"Crea artista",name:"Nome artista",genre:"Genere / sound",concept:"Concept artista",namePh:"es. Nova Vale",genrePh:"es. Dark pop / R&B",conceptPh:"Breve descrizione dell’identità, stile o mondo...",save:"Aggiungi artista",cancel:"Annulla",active:"ATTIVO",primary:"PRINCIPALE",switch:"Rendi attivo",remove:"Rimuovi",empty:"Nessun artista trovato.",freeTitle:"Più artisti fanno parte di Artist Pro",freeText:"Artist Free include un profilo principale. Passa a Artist Pro o Max per gestire più artisti.",upgrade:"Vedi Artist Pro",back:"Torna alla Dashboard",search:"Cerca i tuoi artisti",account:"Un account · più identità artistiche"},
pt:{kicker:"ARTIST PRO / MAX",title:"Os meus artistas",intro:"Cria e gere várias identidades de artista IA numa só conta MOCIFY.",add:"Criar artista",name:"Nome artístico",genre:"Género / som",concept:"Conceito do artista",namePh:"ex. Nova Vale",genrePh:"ex. Dark pop / R&B",conceptPh:"Descrição curta da identidade, estilo ou universo...",save:"Adicionar artista",cancel:"Cancelar",active:"ATIVO",primary:"PRINCIPAL",switch:"Tornar ativo",remove:"Remover",empty:"Nenhum artista encontrado.",freeTitle:"Vários artistas fazem parte do Artist Pro",freeText:"Artist Free inclui um perfil principal. Atualiza para Artist Pro ou Max para gerir vários artistas.",upgrade:"Ver Artist Pro",back:"Voltar ao Dashboard",search:"Pesquisar os teus artistas",account:"Uma conta · várias identidades de artista"},
pl:{kicker:"ARTIST PRO / MAX",title:"Moi artyści",intro:"Twórz i zarządzaj wieloma tożsamościami artystów AI na jednym koncie MOCIFY.",add:"Utwórz artystę",name:"Nazwa artysty",genre:"Gatunek / brzmienie",concept:"Koncepcja artysty",namePh:"np. Nova Vale",genrePh:"np. Dark pop / R&B",conceptPh:"Krótki opis tożsamości, stylu lub świata...",save:"Dodaj artystę",cancel:"Anuluj",active:"AKTYWNY",primary:"GŁÓWNY",switch:"Ustaw aktywny",remove:"Usuń",empty:"Nie znaleziono artystów.",freeTitle:"Wielu artystów jest częścią Artist Pro",freeText:"Artist Free obejmuje jeden główny profil. Przejdź na Artist Pro lub Max, aby zarządzać wieloma artystami.",upgrade:"Zobacz Artist Pro",back:"Wróć do panelu",search:"Szukaj swoich artystów",account:"Jedno konto · wiele tożsamości artysty"},
tr:{kicker:"ARTIST PRO / MAX",title:"Sanatçılarım",intro:"Tek MOCIFY hesabından birden fazla AI sanatçı kimliği oluştur ve yönet.",add:"Sanatçı oluştur",name:"Sanatçı adı",genre:"Tür / sound",concept:"Sanatçı konsepti",namePh:"örn. Nova Vale",genrePh:"örn. Dark pop / R&B",conceptPh:"Kimlik, stil veya dünya hakkında kısa açıklama...",save:"Sanatçı ekle",cancel:"İptal",active:"AKTİF",primary:"ANA",switch:"Aktif yap",remove:"Kaldır",empty:"Sanatçı bulunamadı.",freeTitle:"Birden fazla sanatçı Artist Pro'nun parçasıdır",freeText:"Artist Free bir ana sanatçı profili içerir. Birden fazla sanatçı için Artist Pro veya Max'e yükselt.",upgrade:"Artist Pro'yu gör",back:"Panele dön",search:"Sanatçılarında ara",account:"Tek hesap · birden fazla sanatçı kimliği"},
id:{kicker:"ARTIST PRO / MAX",title:"Artisku",intro:"Buat dan kelola beberapa identitas artis AI dari satu akun MOCIFY.",add:"Buat artis",name:"Nama artis",genre:"Genre / sound",concept:"Konsep artis",namePh:"mis. Nova Vale",genrePh:"mis. Dark pop / R&B",conceptPh:"Deskripsi singkat identitas, gaya, atau dunia...",save:"Tambahkan artis",cancel:"Batal",active:"AKTIF",primary:"UTAMA",switch:"Jadikan aktif",remove:"Hapus",empty:"Tidak ada artis yang cocok.",freeTitle:"Multi-artis adalah bagian dari Artist Pro",freeText:"Artist Free mencakup satu profil artis utama. Upgrade ke Artist Pro atau Max untuk membuat dan mengelola beberapa artis.",upgrade:"Lihat Artist Pro",back:"Kembali ke Dashboard",search:"Cari artismu",account:"Satu akun · banyak identitas artis"},
ja:{kicker:"ARTIST PRO / MAX",title:"マイアーティスト",intro:"1つのMOCIFYアカウントから複数のAIアーティストを作成・管理。",add:"アーティスト作成",name:"アーティスト名",genre:"ジャンル / サウンド",concept:"アーティストコンセプト",namePh:"例：Nova Vale",genrePh:"例：Dark pop / R&B",conceptPh:"アイデンティティ、スタイル、世界観の短い説明...",save:"アーティスト追加",cancel:"キャンセル",active:"有効",primary:"メイン",switch:"有効にする",remove:"削除",empty:"一致するアーティストがいません。",freeTitle:"複数アーティストはArtist Proの機能です",freeText:"Artist Freeには1つのメインアーティストプロフィールが含まれます。複数管理にはArtist ProまたはMaxへアップグレード。",upgrade:"Artist Proを見る",back:"ダッシュボードへ戻る",search:"アーティストを検索",account:"1アカウント · 複数アーティスト"},
ko:{kicker:"ARTIST PRO / MAX",title:"내 아티스트",intro:"하나의 MOCIFY 계정에서 여러 AI 아티스트 아이덴티티를 만들고 관리하세요.",add:"아티스트 만들기",name:"아티스트 이름",genre:"장르 / 사운드",concept:"아티스트 콘셉트",namePh:"예: Nova Vale",genrePh:"예: Dark pop / R&B",conceptPh:"아이덴티티, 스타일 또는 세계관의 짧은 설명...",save:"아티스트 추가",cancel:"취소",active:"활성",primary:"기본",switch:"활성으로 설정",remove:"삭제",empty:"검색과 일치하는 아티스트가 없습니다.",freeTitle:"여러 아티스트는 Artist Pro 기능입니다",freeText:"Artist Free에는 기본 아티스트 프로필 하나가 포함됩니다. 여러 아티스트 관리는 Artist Pro 또는 Max로 업그레이드하세요.",upgrade:"Artist Pro 보기",back:"대시보드로 돌아가기",search:"아티스트 검색",account:"하나의 계정 · 여러 아티스트 아이덴티티"},
hi:{kicker:"ARTIST PRO / MAX",title:"मेरे कलाकार",intro:"एक MOCIFY खाते से कई AI कलाकार पहचान बनाएँ और मैनेज करें।",add:"कलाकार बनाएँ",name:"कलाकार नाम",genre:"जॉनर / साउंड",concept:"कलाकार कॉन्सेप्ट",namePh:"जैसे Nova Vale",genrePh:"जैसे Dark pop / R&B",conceptPh:"पहचान, स्टाइल या दुनिया का छोटा विवरण...",save:"कलाकार जोड़ें",cancel:"रद्द करें",active:"सक्रिय",primary:"मुख्य",switch:"सक्रिय बनाएँ",remove:"हटाएँ",empty:"खोज से कोई कलाकार नहीं मिला।",freeTitle:"कई कलाकार Artist Pro का हिस्सा हैं",freeText:"Artist Free में एक मुख्य कलाकार प्रोफ़ाइल शामिल है। कई कलाकारों के लिए Artist Pro या Max में अपग्रेड करें।",upgrade:"Artist Pro देखें",back:"डैशबोर्ड पर वापस",search:"अपने कलाकार खोजें",account:"एक खाता · कई कलाकार पहचान"}}as const;
const artistDetailCopy={
en:{edit:"Edit",update:"Save changes",overview:"Artist overview",songs:"Song analytics",songsText:"See how every song from this artist is performing in one place.",streams:"Streams",listeners:"Listeners",saves:"Saves",completion:"Completion",trend:"28d trend",releases:"Songs",noSongs:"No released songs for this artist yet.",artistTotal:"Artist total",select:"Select an artist to view performance.",profile:"Profile",analytics:"Analytics"},
nl:{edit:"Bewerken",update:"Wijzigingen opslaan",overview:"Artiestoverzicht",songs:"Songanalyse",songsText:"Bekijk op één plek hoe alle songs van deze artiest presteren.",streams:"Streams",listeners:"Luisteraars",saves:"Saves",completion:"Uitluisterpercentage",trend:"Trend 28d",releases:"Songs",noSongs:"Deze artiest heeft nog geen uitgebrachte songs.",artistTotal:"Totaal artiest",select:"Selecteer een artiest om de prestaties te bekijken.",profile:"Profiel",analytics:"Analyse"},
ro:{edit:"Editează",update:"Salvează modificările",overview:"Prezentare artist",songs:"Analiză piese",songsText:"Vezi într-un singur loc cum performează toate piesele acestui artist.",streams:"Redări",listeners:"Ascultători",saves:"Salvări",completion:"Rată completare",trend:"Trend 28z",releases:"Piese",noSongs:"Acest artist nu are încă piese lansate.",artistTotal:"Total artist",select:"Selectează un artist pentru performanță.",profile:"Profil",analytics:"Analize"},
de:{edit:"Bearbeiten",update:"Änderungen speichern",overview:"Künstlerübersicht",songs:"Song-Analysen",songsText:"Sieh an einem Ort, wie alle Songs dieses Künstlers performen.",streams:"Streams",listeners:"Hörer",saves:"Saves",completion:"Abschlussrate",trend:"28-Tage-Trend",releases:"Songs",noSongs:"Dieser Künstler hat noch keine veröffentlichten Songs.",artistTotal:"Künstler gesamt",select:"Wähle einen Künstler für die Performance.",profile:"Profil",analytics:"Analysen"},
fr:{edit:"Modifier",update:"Enregistrer",overview:"Vue artiste",songs:"Analyse des titres",songsText:"Voyez au même endroit les performances de tous les titres de cet artiste.",streams:"Écoutes",listeners:"Auditeurs",saves:"Sauvegardes",completion:"Taux d’écoute",trend:"Tendance 28j",releases:"Titres",noSongs:"Cet artiste n’a encore aucun titre publié.",artistTotal:"Total artiste",select:"Sélectionnez un artiste pour voir ses performances.",profile:"Profil",analytics:"Analyses"},
es:{edit:"Editar",update:"Guardar cambios",overview:"Resumen del artista",songs:"Analítica de canciones",songsText:"Mira en un solo lugar cómo rinden todas las canciones de este artista.",streams:"Reproducciones",listeners:"Oyentes",saves:"Guardados",completion:"Finalización",trend:"Tendencia 28d",releases:"Canciones",noSongs:"Este artista aún no tiene canciones publicadas.",artistTotal:"Total artista",select:"Selecciona un artista para ver el rendimiento.",profile:"Perfil",analytics:"Analíticas"},
it:{edit:"Modifica",update:"Salva modifiche",overview:"Panoramica artista",songs:"Analisi brani",songsText:"Vedi in un solo posto come stanno andando tutti i brani di questo artista.",streams:"Stream",listeners:"Ascoltatori",saves:"Salvataggi",completion:"Completamento",trend:"Trend 28g",releases:"Brani",noSongs:"Questo artista non ha ancora brani pubblicati.",artistTotal:"Totale artista",select:"Seleziona un artista per vedere le performance.",profile:"Profilo",analytics:"Analytics"},
pt:{edit:"Editar",update:"Guardar alterações",overview:"Visão do artista",songs:"Análise das faixas",songsText:"Vê num só lugar o desempenho de todas as músicas deste artista.",streams:"Reproduções",listeners:"Ouvintes",saves:"Guardados",completion:"Conclusão",trend:"Tendência 28d",releases:"Faixas",noSongs:"Este artista ainda não tem músicas lançadas.",artistTotal:"Total do artista",select:"Seleciona um artista para ver o desempenho.",profile:"Perfil",analytics:"Análises"},
pl:{edit:"Edytuj",update:"Zapisz zmiany",overview:"Przegląd artysty",songs:"Analityka utworów",songsText:"Zobacz w jednym miejscu, jak radzą sobie wszystkie utwory tego artysty.",streams:"Odtworzenia",listeners:"Słuchacze",saves:"Zapisy",completion:"Ukończenie",trend:"Trend 28d",releases:"Utwory",noSongs:"Ten artysta nie ma jeszcze opublikowanych utworów.",artistTotal:"Suma artysty",select:"Wybierz artystę, aby zobaczyć wyniki.",profile:"Profil",analytics:"Analityka"},
tr:{edit:"Düzenle",update:"Değişiklikleri kaydet",overview:"Sanatçı özeti",songs:"Şarkı analizleri",songsText:"Bu sanatçının tüm şarkılarının performansını tek yerde gör.",streams:"Dinlenmeler",listeners:"Dinleyiciler",saves:"Kayıtlar",completion:"Tamamlama",trend:"28g trend",releases:"Şarkılar",noSongs:"Bu sanatçının henüz yayınlanmış şarkısı yok.",artistTotal:"Sanatçı toplamı",select:"Performansı görmek için sanatçı seç.",profile:"Profil",analytics:"Analizler"},
id:{edit:"Edit",update:"Simpan perubahan",overview:"Ringkasan artis",songs:"Analitik lagu",songsText:"Lihat performa semua lagu artis ini dalam satu tempat.",streams:"Stream",listeners:"Pendengar",saves:"Simpanan",completion:"Penyelesaian",trend:"Tren 28h",releases:"Lagu",noSongs:"Artis ini belum memiliki lagu yang dirilis.",artistTotal:"Total artis",select:"Pilih artis untuk melihat performa.",profile:"Profil",analytics:"Analitik"},
ja:{edit:"編集",update:"変更を保存",overview:"アーティスト概要",songs:"楽曲分析",songsText:"このアーティストの全楽曲のパフォーマンスを1か所で確認。",streams:"再生数",listeners:"リスナー",saves:"保存数",completion:"完聴率",trend:"28日トレンド",releases:"楽曲",noSongs:"このアーティストにはまだ公開曲がありません。",artistTotal:"アーティスト合計",select:"アーティストを選択してパフォーマンスを表示。",profile:"プロフィール",analytics:"分析"},
ko:{edit:"편집",update:"변경사항 저장",overview:"아티스트 개요",songs:"곡 분석",songsText:"이 아티스트의 모든 곡 성과를 한 곳에서 확인하세요.",streams:"스트림",listeners:"리스너",saves:"저장",completion:"완주율",trend:"28일 추세",releases:"곡",noSongs:"이 아티스트는 아직 공개된 곡이 없습니다.",artistTotal:"아티스트 합계",select:"성과를 보려면 아티스트를 선택하세요.",profile:"프로필",analytics:"분석"},
hi:{edit:"एडिट",update:"बदलाव सेव करें",overview:"कलाकार ओवरव्यू",songs:"गीत एनालिटिक्स",songsText:"इस कलाकार के सभी गीतों की परफॉर्मेंस एक ही जगह देखें।",streams:"स्ट्रीम",listeners:"श्रोता",saves:"सेव",completion:"पूर्णता",trend:"28 दिन ट्रेंड",releases:"गीत",noSongs:"इस कलाकार के अभी कोई प्रकाशित गीत नहीं हैं।",artistTotal:"कलाकार कुल",select:"परफॉर्मेंस देखने के लिए कलाकार चुनें।",profile:"प्रोफ़ाइल",analytics:"एनालिटिक्स"}
}as const;

const metricSeed:Record<string,{streams:number;listeners:number;saves:number;completion:number;trend:number}>={
 "toca-bonbon":{streams:14240,listeners:8760,saves:1932,completion:78,trend:12.4},
 "digital-touch":{streams:8710,listeners:5920,saves:1104,completion:73,trend:8.1},
 "after-you":{streams:5140,listeners:3610,saves:722,completion:69,trend:-1.8},
 "zero-gravity":{streams:3290,listeners:2440,saves:481,completion:75,trend:5.6}
};
function metrics(id:string,index:number){return metricSeed[id]??{streams:1800+index*730,listeners:1100+index*410,saves:240+index*95,completion:66+(index%4)*4,trend:2.5+index*1.3}}

export default function ArtistManager(){
 const{locale}=useLanguage();const t=(copy as any)[locale]??copy.en;const d=(artistDetailCopy as any)[locale]??artistDetailCopy.en;const params=useSearchParams();
 const[plan,setPlan]=useState<ArtistPlanTier|null>(null);const[artists,setArtists]=useState<ManagedArtist[]>([]);const[activeId,setActiveId]=useState("");const[showForm,setShowForm]=useState(false);const[editId,setEditId]=useState<string|null>(null);const[name,setName]=useState("");const[genre,setGenre]=useState("");const[concept,setConcept]=useState("");const[q,setQ]=useState("");
 useEffect(()=>{const current=getStoredArtistPlan();setPlan(current);const list=ensurePrimaryArtist();setArtists(list);setActiveId(localStorage.getItem(ACTIVE_ARTIST_KEY)||list[0]?.id||"");setQ(params.get("q")||"")},[params]);
 const canManage=plan!==null&&hasArtistFeature(plan,"multiArtist");
 const visible=useMemo(()=>artists.filter(a=>a.name.toLowerCase().includes(q.trim().toLowerCase())||a.genre.toLowerCase().includes(q.trim().toLowerCase())),[artists,q]);
 const activeArtist=artists.find(a=>a.id===activeId)??artists[0]??null;
 const activeSongs=useMemo(()=>activeArtist?releases.filter(r=>r.artist.toLowerCase()===activeArtist.name.toLowerCase()):[],[activeArtist]);
 const songRows=activeSongs.map((song,index)=>({song,...metrics(song.id,index)}));
 const totals=songRows.reduce((a,x)=>({streams:a.streams+x.streams,listeners:a.listeners+x.listeners,saves:a.saves+x.saves}),{streams:0,listeners:0,saves:0});
 const numberLocale=({en:"en-US",nl:"nl-NL",ro:"ro-RO",de:"de-DE",fr:"fr-FR",es:"es-ES",it:"it-IT",pt:"pt-PT",pl:"pl-PL",tr:"tr-TR",id:"id-ID",ja:"ja-JP",ko:"ko-KR",hi:"hi-IN"}as const)[locale]??"en-US";
 const fmt=(n:number)=>new Intl.NumberFormat(numberLocale,{notation:n>=10000?"compact":"standard",maximumFractionDigits:1}).format(n);
 function persist(next:ManagedArtist[]){setArtists(next);localStorage.setItem(MANAGED_ARTISTS_KEY,JSON.stringify(next))}
 function resetForm(){setName("");setGenre("");setConcept("");setEditId(null);setShowForm(false)}
 function startCreate(){if(showForm&&!editId){resetForm();return}setEditId(null);setName("");setGenre("");setConcept("");setShowForm(true)}
 function startEdit(artist:ManagedArtist){setEditId(artist.id);setName(artist.name);setGenre(artist.genre);setConcept(artist.concept);setShowForm(true);window.scrollTo({top:0,behavior:"smooth"})}
 function submit(e:FormEvent){e.preventDefault();const clean=name.trim();if(!clean)return;if(editId){persist(artists.map(a=>a.id===editId?{...a,name:clean,genre:genre.trim()||"AI Artist",concept:concept.trim()}:a));resetForm();return}const artist:ManagedArtist={id:`artist-${Date.now()}`,name:clean,genre:genre.trim()||"AI Artist",concept:concept.trim(),createdAt:Date.now()};persist([...artists,artist]);resetForm()}
 function activate(id:string){setActiveId(id);setActiveArtist(id)}
 function remove(id:string){const target=artists.find(a=>a.id===id);if(!target||target.primary)return;const next=artists.filter(a=>a.id!==id);persist(next);if(activeId===id){const fallback=next[0];if(fallback){setActiveId(fallback.id);setActiveArtist(fallback.id)}}}
 if(plan===null)return null;
 return <ArtistPortalShell active="studio"><section className="artist-dashboard-page"><ArtistDashboardLayout plan={plan}><div className={styles.page}>
  <header className={styles.heading}><div><p>{t.kicker}</p><h1>{t.title}</h1><span>{t.intro}</span></div>{canManage&&<button onClick={startCreate}>{showForm&&!editId?t.cancel:`+ ${t.add}`}</button>}</header>
  {!canManage?<section className={styles.gate}><div><small>ARTIST FREE · PRO FEATURE</small><h2>{t.freeTitle}</h2><p>{t.freeText}</p><div><Link className={styles.primary} href="/for-artists">{t.upgrade}</Link><Link href="/dashboard">{t.back}</Link></div></div><aside><strong>1</strong><span>{locale==="nl"?"primair artiestprofiel":locale==="ro"?"profil principal":"primary artist profile"}</span></aside></section>:<>
   {showForm&&<form className={styles.form} onSubmit={submit}><label>{t.name}<input value={name} onChange={e=>setName(e.target.value)} placeholder={t.namePh} required/></label><label>{t.genre}<input value={genre} onChange={e=>setGenre(e.target.value)} placeholder={t.genrePh}/></label><label className={styles.full}>{t.concept}<textarea value={concept} onChange={e=>setConcept(e.target.value)} placeholder={t.conceptPh}/></label><div className={styles.formActions}><button className={styles.primary} type="submit">{editId?d.update:t.save}</button><button type="button" onClick={resetForm}>{t.cancel}</button></div></form>}
   <div className={styles.toolbar}><label><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder={t.search}/></label><small>{t.account}</small></div>
   <div className={styles.grid}>{visible.length?visible.map((artist,i)=>{const isActive=artist.id===activeId;return <article className={`${styles.card} ${isActive?styles.activeCard:""}`} key={artist.id} onClick={()=>activate(artist.id)}><div className={`${styles.avatar} ${styles[`tone${i%4}`]}`}>{artist.name.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase()}</div><div className={styles.cardHead}><div><small>{artist.primary?t.primary:isActive?t.active:"AI ARTIST"}</small><h2>{artist.name}</h2></div>{isActive&&<em>{t.active}</em>}</div><p>{artist.genre}</p><span>{artist.concept||"—"}</span><div className={styles.actions} onClick={e=>e.stopPropagation()}>{!isActive&&<button onClick={()=>activate(artist.id)}>{t.switch}</button>}<button onClick={()=>startEdit(artist)}>{d.edit}</button>{!artist.primary&&<button className={styles.remove} onClick={()=>remove(artist.id)}>{t.remove}</button>}</div></article>}):<div className={styles.empty}>{t.empty}</div>}</div>
   <section className={styles.artistOverview}>
    <div className={styles.overviewHead}><div><small>{d.analytics}</small><h2>{activeArtist?activeArtist.name:d.overview}</h2><p>{d.songsText}</p></div>{activeArtist&&<span>{activeArtist.genre}</span>}</div>
    {activeArtist?<><div className={styles.summaryStats}><article><small>{d.streams}</small><strong>{fmt(totals.streams)}</strong></article><article><small>{d.listeners}</small><strong>{fmt(totals.listeners)}</strong></article><article><small>{d.saves}</small><strong>{fmt(totals.saves)}</strong></article><article><small>{d.releases}</small><strong>{activeSongs.length}</strong></article></div>
    <div className={styles.songPanel}><div className={styles.songPanelTitle}><div><small>{d.artistTotal}</small><h3>{d.songs}</h3></div><Link href="/studio/analytics">{t.analytics??"Analytics"} →</Link></div>{songRows.length?<div className={styles.songTable}><div className={styles.songTableHead}><span>{d.releases}</span><span>{d.streams}</span><span>{d.listeners}</span><span>{d.saves}</span><span>{d.completion}</span><span>{d.trend}</span></div>{songRows.map(({song,streams,listeners,saves,completion,trend})=><div className={styles.songRow} key={song.id}><div><b>{song.title}</b><small>{song.genre}</small></div><span>{fmt(streams)}</span><span>{fmt(listeners)}</span><span>{fmt(saves)}</span><span>{completion}%</span><span className={trend>=0?styles.positive:styles.negative}>{trend>=0?"+":""}{trend.toFixed(1)}%</span></div>)}</div>:<div className={styles.noSongs}>{d.noSongs}</div>}</div></>:<div className={styles.noSongs}>{d.select}</div>}
   </section>
  </>}
 </div></ArtistDashboardLayout></section></ArtistPortalShell>
}