const freeUsers=[
 ["David Klein","david.k@example.com","Germany","18 Sep 2026","Active","148"],
 ["Emma de Jong","emma.dj@example.com","Netherlands","16 Sep 2026","Active","93"],
 ["Mateo Ruiz","mateo.r@example.com","Spain","11 Sep 2026","Active","211"],
 ["Aylin Demir","aylin.d@example.com","Türkiye","08 Sep 2026","Review","67"],
 ["Julia Nowak","julia.n@example.com","Poland","03 Sep 2026","Active","184"]
];
const premiumUsers=[
 ["Lena Vos","lena.v@example.com","Netherlands","€8.99 / mo","14 Oct 2026","Active"],
 ["Sofia Martens","sofia.m@example.com","Belgium","€8.99 / mo","12 Oct 2026","Active"],
 ["Kenji Sato","kenji.s@example.com","Japan","€8.99 / mo","09 Oct 2026","Active"],
 ["Ana Popescu","ana.p@example.com","Romania","€8.99 / mo","04 Oct 2026","Payment issue"],
 ["Min-jun Kim","minjun.k@example.com","South Korea","€8.99 / mo","02 Oct 2026","Active"]
];
function Status({value}:{value:string}){const c=value==="Active"?"green":value==="Payment issue"?"red":"amber";return <span className={`adminPill ${c}`}>{value}</span>}
export default function UsersPage(){return <>
 <div className="adminPageHead"><div><div className="adminEyebrow">PEOPLE · LISTENERS</div><h1 className="adminTitle">Listener accounts</h1><p className="adminMuted">Free and Premium are deliberately separated so you can immediately see who uses which plan. All records below are fictitious demo data.</p></div><button className="adminPrimaryBtn">+ Add account</button></div>
 <section className="adminAccountSummary"><div className="adminSummaryBox free"><span>FREE ACCOUNTS</span><strong>9,556</strong><small>74.4% of registered listeners</small></div><div className="adminSummaryBox premium"><span>PREMIUM ACCOUNTS</span><strong>3,284</strong><small>25.6% of registered listeners</small></div><div className="adminSummaryBox revenue"><span>PREMIUM MRR</span><strong>€29,523</strong><small>Demo · before fees/tax</small></div><div className="adminSummaryBox attention"><span>NEEDS ATTENTION</span><strong>42</strong><small>Payment, review or account issues</small></div></section>
 <div className="adminFilterBar"><div className="adminLocalSearch"><span>⌕</span><input placeholder="Search by name, email or country…"/></div><select aria-label="Account status"><option>All statuses</option><option>Active</option><option>Review</option><option>Payment issue</option><option>Suspended</option></select><select aria-label="Country"><option>All countries</option><option>Netherlands</option><option>Belgium</option><option>Germany</option><option>Romania</option></select><button>Export</button></div>
 <section className="adminPlanSection adminPlanFree"><div className="adminPlanHeader"><div><span className="adminPlanTag">FREE</span><h2>Free listener accounts</h2><p>Ad-supported registered listeners. Separate from Premium for fast management.</p></div><div className="adminPlanNumber">9,556 <small>accounts</small></div></div><div className="adminTableWrap"><table className="adminTable"><thead><tr><th>Listener</th><th>Country</th><th>Joined</th><th>Status</th><th>Streams*</th><th></th></tr></thead><tbody>{freeUsers.map(u=><tr key={u[1]}><td><strong>{u[0]}</strong><small className="adminCellSub">{u[1]}</small></td><td>{u[2]}</td><td>{u[3]}</td><td><Status value={u[4]}/></td><td>{u[5]}</td><td><button className="adminRowBtn">View</button></td></tr>)}</tbody></table></div><div className="adminTableFoot"><span>* Demo monthly activity</span><button>View all Free accounts →</button></div></section>
 <section className="adminPlanSection adminPlanPremium"><div className="adminPlanHeader"><div><span className="adminPlanTag">PREMIUM</span><h2>Premium listener accounts</h2><p>Paying listeners, renewal status and subscription value in one block.</p></div><div className="adminPlanNumber">3,284 <small>accounts</small></div></div><div className="adminTableWrap"><table className="adminTable"><thead><tr><th>Listener</th><th>Country</th><th>Plan value</th><th>Next billing</th><th>Status</th><th></th></tr></thead><tbody>{premiumUsers.map(u=><tr key={u[1]}><td><strong>{u[0]}</strong><small className="adminCellSub">{u[1]}</small></td><td>{u[2]}</td><td>{u[3]}</td><td>{u[4]}</td><td><Status value={u[5]}/></td><td><button className="adminRowBtn">View</button></td></tr>)}</tbody></table></div><div className="adminTableFoot"><span>Payment data is demo-only until backend/payment provider connection.</span><button>View all Premium accounts →</button></div></section>
 </>}
