"use client";
import { artistTracks, featuredArtist } from "../../data";
import Link from "next/link";
import {ComingSoonButton,Shell} from "../../components";
import {useLanguage} from"../../i18n/language-provider";
import {useEffect,useState} from "react";
import {FOLLOWED_KEY,readIds,toggleId} from "../../listener-account";
const copy={en:{verified:"VERIFIED AI ARTIST",bio:"Neon emotion, late-night melodies and a futuristic pop identity built for MOCIFY.",play:"Play artist",playSoon:"Artist playback is coming soon",follow:"Follow",followSoon:"Following artists is coming soon",top:"TOP TRACKS",popular:"Popular",trackSoon:"Track page coming soon"},nl:{verified:"GEVERIFIEERDE AI-ARTIEST",bio:"Neonemotie, late-night melodieën en een futuristische popidentiteit gebouwd voor MOCIFY.",play:"Artiest afspelen",playSoon:"Artiest afspelen komt binnenkort",follow:"Volgen",followSoon:"Artiesten volgen komt binnenkort",top:"TOPTRACKS",popular:"Populair",trackSoon:"Trackpagina komt binnenkort"},ro:{verified:"ARTIST AI VERIFICAT",bio:"Emoție neon, melodii de noapte și o identitate pop futuristă creată pentru MOCIFY.",play:"Redă artistul",playSoon:"Redarea artistului va fi disponibilă în curând",follow:"Urmărește",followSoon:"Urmărirea artiștilor va fi disponibilă în curând",top:"PIESE DE TOP",popular:"Populare",trackSoon:"Pagina piesei va fi disponibilă în curând"},
de:{verified:"VERIFIZIERTER KI-KÜNSTLER",bio:"Neon-Emotion, Late-Night-Melodien und eine futuristische Pop-Identität für MOCIFY.",play:"Künstler abspielen",playSoon:"Künstlerwiedergabe kommt bald",follow:"Folgen",followSoon:"Künstler folgen kommt bald",top:"TOP-TRACKS",popular:"Beliebt",trackSoon:"Trackseite kommt bald"},
fr:{verified:"ARTISTE IA VÉRIFIÉ",bio:"Émotion néon, mélodies nocturnes et identité pop futuriste conçue pour MOCIFY.",play:"Lire l’artiste",playSoon:"La lecture de l’artiste arrive bientôt",follow:"Suivre",followSoon:"Le suivi des artistes arrive bientôt",top:"TOP TITRES",popular:"Populaire",trackSoon:"Page du titre bientôt disponible"},
es:{verified:"ARTISTA IA VERIFICADO",bio:"Emoción neón, melodías nocturnas y una identidad pop futurista creada para MOCIFY.",play:"Reproducir artista",playSoon:"La reproducción del artista llegará pronto",follow:"Seguir",followSoon:"Seguir artistas llegará pronto",top:"PISTAS TOP",popular:"Popular",trackSoon:"Página de la pista próximamente"},
it:{verified:"ARTISTA AI VERIFICATO",bio:"Emozione neon, melodie notturne e un’identità pop futuristica creata per MOCIFY.",play:"Riproduci artista",playSoon:"Riproduzione artista presto disponibile",follow:"Segui",followSoon:"Seguire artisti presto disponibile",top:"TRACCE TOP",popular:"Popolari",trackSoon:"Pagina traccia presto disponibile"},
pt:{verified:"ARTISTA IA VERIFICADO",bio:"Emoção néon, melodias noturnas e uma identidade pop futurista criada para MOCIFY.",play:"Reproduzir artista",playSoon:"Reprodução do artista em breve",follow:"Seguir",followSoon:"Seguir artistas em breve",top:"TOP FAIXAS",popular:"Popular",trackSoon:"Página da faixa em breve"},
pl:{verified:"ZWERYFIKOWANY ARTYSTA AI",bio:"Neonowe emocje, nocne melodie i futurystyczna tożsamość pop stworzona dla MOCIFY.",play:"Odtwórz artystę",playSoon:"Odtwarzanie artysty już wkrótce",follow:"Obserwuj",followSoon:"Obserwowanie artystów już wkrótce",top:"TOP UTWORY",popular:"Popularne",trackSoon:"Strona utworu już wkrótce"},
tr:{verified:"DOĞRULANMIŞ AI SANATÇISI",bio:"Neon duygu, gece melodileri ve MOCIFY için oluşturulmuş fütüristik pop kimliği.",play:"Sanatçıyı çal",playSoon:"Sanatçı oynatma yakında",follow:"Takip et",followSoon:"Sanatçı takibi yakında",top:"EN İYİ PARÇALAR",popular:"Popüler",trackSoon:"Parça sayfası yakında"},
id:{verified:"ARTIS AI TERVERIFIKASI",bio:"Emosi neon, melodi larut malam, dan identitas pop futuristik yang dibuat untuk MOCIFY.",play:"Putar artis",playSoon:"Pemutaran artis segera tersedia",follow:"Ikuti",followSoon:"Fitur mengikuti artis segera tersedia",top:"TRACK TERATAS",popular:"Populer",trackSoon:"Halaman track segera tersedia"},
ja:{verified:"認証済みAIアーティスト",bio:"ネオンの感情、深夜のメロディ、MOCIFYのための未来的なポップアイデンティティ。",play:"アーティストを再生",playSoon:"アーティスト再生は近日公開",follow:"フォロー",followSoon:"アーティストフォローは近日公開",top:"トップトラック",popular:"人気",trackSoon:"トラックページは近日公開"},
ko:{verified:"인증된 AI 아티스트",bio:"네온 감성, 늦은 밤의 멜로디, MOCIFY를 위한 미래적인 팝 아이덴티티.",play:"아티스트 재생",playSoon:"아티스트 재생 기능 곧 제공",follow:"팔로우",followSoon:"아티스트 팔로우 기능 곧 제공",top:"인기 트랙",popular:"인기",trackSoon:"트랙 페이지 곧 제공"},
hi:{verified:"सत्यापित AI कलाकार",bio:"नीयन एहसास, देर रात की धुनें और MOCIFY के लिए बनाई गई फ्यूचरिस्टिक पॉप पहचान।",play:"कलाकार चलाएँ",playSoon:"कलाकार प्लेबैक जल्द उपलब्ध होगा",follow:"फॉलो करें",followSoon:"कलाकार फॉलो करना जल्द उपलब्ध होगा",top:"टॉप ट्रैक",popular:"लोकप्रिय",trackSoon:"ट्रैक पेज जल्द उपलब्ध होगा"}}as const;
export default function Artist(){const{locale}=useLanguage();const t=(copy as any)[locale]??copy.en;const[followed,setFollowed]=useState(false);useEffect(()=>setFollowed(readIds(FOLLOWED_KEY).includes(featuredArtist.name)),[]);return <Shell active="artists"><section className="page-wrap py-12"><div className="relative overflow-hidden rounded-[28px] border border-fuchsia-500/20 bg-[radial-gradient(circle_at_75%_20%,rgba(255,43,193,.32),transparent_30%),linear-gradient(120deg,#170929,#27105c_48%,#061127)] p-8 md:p-12"><div className="flex flex-col gap-8 md:flex-row md:items-end"><div className="grid h-48 w-48 shrink-0 place-items-center rounded-full border-2 border-white/20 text-5xl font-black shadow-[0_0_50px_rgba(237,53,197,.25)]" style={{background:featuredArtist.avatarCss}}>{featuredArtist.initials}</div><div><p className="page-kicker">{t.verified}</p><h1 className="mt-3 text-6xl font-black tracking-[-.06em] md:text-8xl">{featuredArtist.name}</h1><p className="mt-4 max-w-xl text-zinc-300">{t.bio}</p><div className="mt-6 flex flex-wrap gap-3"><ComingSoonButton className="m-primary" label={t.playSoon}>▶ {t.play}</ComingSoonButton><button className="m-secondary" onClick={()=>setFollowed(toggleId(FOLLOWED_KEY,featuredArtist.name))}>{followed?"✓ Following":t.follow}</button></div></div></div></div><section className="py-12"><div className="home-heading"><div><p className="page-kicker">{t.top}</p><h2>{t.popular}</h2></div></div><div className="overflow-hidden rounded-2xl border border-white/10 bg-white/[.02]">{artistTracks.map((song,i)=>{const content=<><span className="text-zinc-500">{i+1}</span><div><b>{song.title}</b><p className="mt-1 text-xs text-zinc-400">{featuredArtist.name}</p></div><span className="text-xs text-zinc-400">{song.duration}</span></>;const className="grid grid-cols-[38px_1fr_auto] items-center border-b border-white/8 p-5 last:border-0 hover:bg-white/[.035]";return song.id==="toca-bonbon"?<Link id={song.id} href={song.href} key={song.title} className={className}>{content}</Link>:<div id={song.id} key={song.title} className={className}>{content}<span className="sr-only">{t.trackSoon}</span></div>})}</div></section></section></Shell>}
