"use client";
import Link from "next/link";
import {Shell} from "../components";
import {useLanguage} from "../i18n/language-provider";

const copy={en:{kicker:"ACCOUNT",title:"Settings",lead:"These controls are visual placeholders until accounts are connected.",rows:[["Profile","Manage your public name and profile."],["Playback","Audio quality and playback preferences."],["Notifications","Choose what MOCIFY can notify you about."],["Privacy","Control profile visibility and activity."]],soon:"SOON",back:"Back to MOCIFY",titleSoon:"settings are coming soon"},nl:{kicker:"ACCOUNT",title:"Instellingen",lead:"Deze opties zijn visuele placeholders totdat accounts zijn gekoppeld.",rows:[["Profiel","Beheer je openbare naam en profiel."],["Afspelen","Audiokwaliteit en afspeelvoorkeuren."],["Meldingen","Kies waarover MOCIFY je mag informeren."],["Privacy","Beheer de zichtbaarheid en activiteit van je profiel."]],soon:"BINNENKORT",back:"Terug naar MOCIFY",titleSoon:"instellingen komen binnenkort"},ro:{kicker:"CONT",title:"Setări",lead:"Aceste opțiuni sunt elemente vizuale până când conturile vor fi conectate.",rows:[["Profil","Gestionează numele public și profilul."],["Redare","Calitatea audio și preferințele de redare."],["Notificări","Alege despre ce te poate notifica MOCIFY."],["Confidențialitate","Controlează vizibilitatea și activitatea profilului."]],soon:"ÎN CURÂND",back:"Înapoi la MOCIFY",titleSoon:"setările vor fi disponibile în curând"},
de:{kicker:"KONTO",title:"Einstellungen",lead:"Diese Einstellungen sind visuelle Platzhalter, bis Konten verbunden sind.",rows:[["Profil","Öffentlichen Namen und Profil verwalten."],["Wiedergabe","Audioqualität und Wiedergabeeinstellungen."],["Benachrichtigungen","Wähle, worüber MOCIFY dich informieren darf."],["Datenschutz","Steuere Sichtbarkeit und Aktivität deines Profils."]],soon:"BALD",back:"Zurück zu MOCIFY",titleSoon:"Einstellungen kommen bald"},
fr:{kicker:"COMPTE",title:"Paramètres",lead:"Ces contrôles sont des placeholders visuels jusqu’à la connexion des comptes.",rows:[["Profil","Gérez votre nom public et votre profil."],["Lecture","Qualité audio et préférences de lecture."],["Notifications","Choisissez les notifications MOCIFY."],["Confidentialité","Contrôlez visibilité et activité du profil."]],soon:"BIENTÔT",back:"Retour à MOCIFY",titleSoon:"paramètres bientôt disponibles"},
es:{kicker:"CUENTA",title:"Ajustes",lead:"Estos controles son placeholders visuales hasta que las cuentas estén conectadas.",rows:[["Perfil","Gestiona tu nombre público y perfil."],["Reproducción","Calidad de audio y preferencias."],["Notificaciones","Elige qué puede notificarte MOCIFY."],["Privacidad","Controla visibilidad y actividad."]],soon:"PRÓXIMAMENTE",back:"Volver a MOCIFY",titleSoon:"ajustes próximamente"},
it:{kicker:"ACCOUNT",title:"Impostazioni",lead:"Questi controlli sono placeholder visivi finché gli account non saranno collegati.",rows:[["Profilo","Gestisci nome pubblico e profilo."],["Riproduzione","Qualità audio e preferenze."],["Notifiche","Scegli cosa può notificarti MOCIFY."],["Privacy","Controlla visibilità e attività."]],soon:"PRESTO",back:"Torna a MOCIFY",titleSoon:"impostazioni in arrivo"},
pt:{kicker:"CONTA",title:"Definições",lead:"Estes controlos são placeholders visuais até as contas estarem ligadas.",rows:[["Perfil","Gere nome público e perfil."],["Reprodução","Qualidade de áudio e preferências."],["Notificações","Escolhe sobre o que o MOCIFY te pode notificar."],["Privacidade","Controla visibilidade e atividade."]],soon:"EM BREVE",back:"Voltar ao MOCIFY",titleSoon:"definições em breve"},
pl:{kicker:"KONTO",title:"Ustawienia",lead:"Te opcje są wizualnymi placeholderami do czasu podłączenia kont.",rows:[["Profil","Zarządzaj publiczną nazwą i profilem."],["Odtwarzanie","Jakość dźwięku i preferencje."],["Powiadomienia","Wybierz, o czym MOCIFY może powiadamiać."],["Prywatność","Kontroluj widoczność i aktywność profilu."]],soon:"WKRÓTCE",back:"Wróć do MOCIFY",titleSoon:"ustawienia już wkrótce"},
tr:{kicker:"HESAP",title:"Ayarlar",lead:"Bu kontroller hesaplar bağlanana kadar görsel yer tutuculardır.",rows:[["Profil","Herkese açık adını ve profilini yönet."],["Oynatma","Ses kalitesi ve oynatma tercihleri."],["Bildirimler","MOCIFY'ın sana neleri bildireceğini seç."],["Gizlilik","Profil görünürlüğünü ve etkinliği kontrol et."]],soon:"YAKINDA",back:"MOCIFY'a dön",titleSoon:"ayarlar yakında"}}as const;
export default function Settings(){const{locale}=useLanguage();const t=(copy as any)[locale]??copy.en;return <Shell player={false}><section className="page-wrap max-w-3xl py-16"><p className="page-kicker">{t.kicker}</p><h1 className="page-title">{t.title}</h1><p className="page-lead mt-5">{t.lead}</p><div className="mt-9 space-y-3">{t.rows.map(([title,text])=><button type="button" disabled title={`${title}: ${t.titleSoon}`} key={title} className="settings-row flex w-full items-center justify-between rounded-2xl border border-white/10 bg-white/[.025] p-5 text-left"><span><span className="block font-bold">{title}</span><span className="mt-1 block text-xs text-zinc-400">{text}</span></span><span className="prototype-badge">{t.soon}</span></button>)}</div><Link href="/" className="mt-8 inline-block text-xs text-zinc-400">← {t.back}</Link></section></Shell>}
