"use client";
import Link from "next/link";
import {Shell} from "../components";
import {useLanguage} from "../i18n/language-provider";

const copy={en:{kicker:"ACCOUNT",title:"Settings",lead:"These controls are visual placeholders until accounts are connected.",rows:[["Profile","Manage your public name and profile."],["Playback","Audio quality and playback preferences."],["Notifications","Choose what MOCIFY can notify you about."],["Privacy","Control profile visibility and activity."]],soon:"SOON",back:"Back to MOCIFY",titleSoon:"settings are coming soon"},nl:{kicker:"ACCOUNT",title:"Instellingen",lead:"Deze opties zijn visuele placeholders totdat accounts zijn gekoppeld.",rows:[["Profiel","Beheer je openbare naam en profiel."],["Afspelen","Audiokwaliteit en afspeelvoorkeuren."],["Meldingen","Kies waarover MOCIFY je mag informeren."],["Privacy","Beheer de zichtbaarheid en activiteit van je profiel."]],soon:"BINNENKORT",back:"Terug naar MOCIFY",titleSoon:"instellingen komen binnenkort"},ro:{kicker:"CONT",title:"Setări",lead:"Aceste opțiuni sunt elemente vizuale până când conturile vor fi conectate.",rows:[["Profil","Gestionează numele public și profilul."],["Redare","Calitatea audio și preferințele de redare."],["Notificări","Alege despre ce te poate notifica MOCIFY."],["Confidențialitate","Controlează vizibilitatea și activitatea profilului."]],soon:"ÎN CURÂND",back:"Înapoi la MOCIFY",titleSoon:"setările vor fi disponibile în curând"},
de:{kicker:"KONTO",title:"Einstellungen",lead:"Diese Einstellungen sind visuelle Platzhalter, bis Konten verbunden sind.",rows:[["Profil","Öffentlichen Namen und Profil verwalten."],["Wiedergabe","Audioqualität und Wiedergabeeinstellungen."],["Benachrichtigungen","Wähle, worüber MOCIFY dich informieren darf."],["Datenschutz","Steuere Sichtbarkeit und Aktivität deines Profils."]],soon:"BALD",back:"Zurück zu MOCIFY",titleSoon:"Einstellungen kommen bald"},
fr:{kicker:"COMPTE",title:"Paramètres",lead:"Ces contrôles sont des placeholders visuels jusqu’à la connexion des comptes.",rows:[["Profil","Gérez votre nom public et votre profil."],["Lecture","Qualité audio et préférences de lecture."],["Notifications","Choisissez les notifications MOCIFY."],["Confidentialité","Contrôlez visibilité et activité du profil."]],soon:"BIENTÔT",back:"Retour à MOCIFY",titleSoon:"paramètres bientôt disponibles"},
es:{kicker:"CUENTA",title:"Ajustes",lead:"Estos controles son placeholders visuales hasta que las cuentas estén conectadas.",rows:[["Perfil","Gestiona tu nombre público y perfil."],["Reproducción","Calidad de audio y preferencias."],["Notificaciones","Elige qué puede notificarte MOCIFY."],["Privacidad","Controla visibilidad y actividad."]],soon:"PRÓXIMAMENTE",back:"Volver a MOCIFY",titleSoon:"ajustes próximamente"},
it:{kicker:"ACCOUNT",title:"Impostazioni",lead:"Questi controlli sono placeholder visivi finché gli account non saranno collegati.",rows:[["Profilo","Gestisci nome pubblico e profilo."],["Riproduzione","Qualità audio e preferenze."],["Notifiche","Scegli cosa può notificarti MOCIFY."],["Privacy","Controlla visibilità e attività."]],soon:"PRESTO",back:"Torna a MOCIFY",titleSoon:"impostazioni in arrivo"},
pt:{kicker:"CONTA",title:"Definições",lead:"Estes controlos são placeholders visuais até as contas estarem ligadas.",rows:[["Perfil","Gere nome público e perfil."],["Reprodução","Qualidade de áudio e preferências."],["Notificações","Escolhe sobre o que o MOCIFY te pode notificar."],["Privacidade","Controla visibilidade e atividade."]],soon:"EM BREVE",back:"Voltar ao MOCIFY",titleSoon:"definições em breve"},
pl:{kicker:"KONTO",title:"Ustawienia",lead:"Te opcje są wizualnymi placeholderami do czasu podłączenia kont.",rows:[["Profil","Zarządzaj publiczną nazwą i profilem."],["Odtwarzanie","Jakość dźwięku i preferencje."],["Powiadomienia","Wybierz, o czym MOCIFY może powiadamiać."],["Prywatność","Kontroluj widoczność i aktywność profilu."]],soon:"WKRÓTCE",back:"Wróć do MOCIFY",titleSoon:"ustawienia już wkrótce"},
tr:{kicker:"HESAP",title:"Ayarlar",lead:"Bu kontroller hesaplar bağlanana kadar görsel yer tutuculardır.",rows:[["Profil","Herkese açık adını ve profilini yönet."],["Oynatma","Ses kalitesi ve oynatma tercihleri."],["Bildirimler","MOCIFY'ın sana neleri bildireceğini seç."],["Gizlilik","Profil görünürlüğünü ve etkinliği kontrol et."]],soon:"YAKINDA",back:"MOCIFY'a dön",titleSoon:"ayarlar yakında"},
id:{kicker:"AKUN",title:"Pengaturan",lead:"Kontrol ini adalah placeholder visual sampai akun terhubung.",rows:[["Profil","Kelola nama publik dan profilmu."],["Pemutaran","Kualitas audio dan preferensi pemutaran."],["Notifikasi","Pilih apa yang boleh MOCIFY beri tahu."],["Privasi","Atur visibilitas dan aktivitas profil."]],soon:"SEGERA",back:"Kembali ke MOCIFY",titleSoon:"pengaturan segera tersedia"},
ja:{kicker:"アカウント",title:"設定",lead:"アカウント接続まではこれらは視覚的なプレースホルダーです。",rows:[["プロフィール","公開名とプロフィールを管理。"],["再生","音質と再生設定。"],["通知","MOCIFYから受け取る通知を選択。"],["プライバシー","プロフィールの表示とアクティビティを管理。"]],soon:"近日",back:"MOCIFYへ戻る",titleSoon:"設定は近日公開"},
ko:{kicker:"계정",title:"설정",lead:"계정이 연결될 때까지 이 항목들은 시각적 자리표시자입니다.",rows:[["프로필","공개 이름과 프로필을 관리합니다."],["재생","오디오 품질과 재생 환경 설정."],["알림","MOCIFY 알림 항목을 선택합니다."],["개인정보","프로필 공개 범위와 활동을 관리합니다."]],soon:"곧",back:"MOCIFY로 돌아가기",titleSoon:"설정은 곧 제공됩니다"},
hi:{kicker:"खाता",title:"सेटिंग्स",lead:"खाते जुड़ने तक ये कंट्रोल विज़ुअल प्लेसहोल्डर हैं।",rows:[["प्रोफ़ाइल","अपना सार्वजनिक नाम और प्रोफ़ाइल मैनेज करें।"],["प्लेबैक","ऑडियो क्वालिटी और प्लेबैक पसंद।"],["नोटिफिकेशन","चुनें MOCIFY आपको किस बारे में बताए।"],["प्राइवेसी","प्रोफ़ाइल विज़िबिलिटी और एक्टिविटी नियंत्रित करें।"]],soon:"जल्द",back:"MOCIFY पर वापस",titleSoon:"सेटिंग्स जल्द उपलब्ध होंगी"}}as const;
export default function Settings(){const{locale}=useLanguage();const t=(copy as any)[locale]??copy.en;return <Shell player={false}><section className="page-wrap max-w-3xl py-16"><p className="page-kicker">{t.kicker}</p><h1 className="page-title">{t.title}</h1><p className="page-lead mt-5">{t.lead}</p><div className="mt-9 space-y-3">{t.rows.map(([title,text])=><button type="button" disabled title={`${title}: ${t.titleSoon}`} key={title} className="settings-row flex w-full items-center justify-between rounded-2xl border border-white/10 bg-white/[.025] p-5 text-left"><span><span className="block font-bold">{title}</span><span className="mt-1 block text-xs text-zinc-400">{text}</span></span><span className="prototype-badge">{t.soon}</span></button>)}</div><Link href="/" className="mt-8 inline-block text-xs text-zinc-400">← {t.back}</Link></section></Shell>}
