"use client";

import { formatTime, useListenerPlayer } from "../listener-player";
import {useLanguage} from"../i18n/language-provider";
const copy={en:{player:"MOCIFY Radio player",prev:"Previous track",next:"Next track",play:"Play radio",pause:"Pause radio",noAudio:"Audio previews are not connected yet"},nl:{player:"MOCIFY Radio-speler",prev:"Vorige track",next:"Volgende track",play:"Radio afspelen",pause:"Radio pauzeren",noAudio:"Audiopreviews zijn nog niet gekoppeld"},ro:{player:"Player MOCIFY Radio",prev:"Piesa anterioară",next:"Piesa următoare",play:"Redă radio",pause:"Pauză radio",noAudio:"Previzualizările audio nu sunt încă conectate"},
de:{player:"MOCIFY Radio-Player",prev:"Vorheriger Track",next:"Nächster Track",play:"Radio abspielen",pause:"Radio pausieren",noAudio:"Audiovorschauen sind noch nicht verbunden"},
fr:{player:"Lecteur MOCIFY Radio",prev:"Titre précédent",next:"Titre suivant",play:"Lire la radio",pause:"Mettre la radio en pause",noAudio:"Les aperçus audio ne sont pas encore connectés"},
es:{player:"Reproductor MOCIFY Radio",prev:"Pista anterior",next:"Pista siguiente",play:"Reproducir radio",pause:"Pausar radio",noAudio:"Las previsualizaciones de audio aún no están conectadas"},
it:{player:"Player MOCIFY Radio",prev:"Traccia precedente",next:"Traccia successiva",play:"Riproduci radio",pause:"Pausa radio",noAudio:"Le anteprime audio non sono ancora collegate"},
pt:{player:"Leitor MOCIFY Radio",prev:"Faixa anterior",next:"Faixa seguinte",play:"Reproduzir rádio",pause:"Pausar rádio",noAudio:"As prévias de áudio ainda não estão ligadas"},
pl:{player:"Odtwarzacz MOCIFY Radio",prev:"Poprzedni utwór",next:"Następny utwór",play:"Odtwórz radio",pause:"Wstrzymaj radio",noAudio:"Podglądy audio nie są jeszcze podłączone"},
tr:{player:"MOCIFY Radyo oynatıcı",prev:"Önceki parça",next:"Sonraki parça",play:"Radyoyu çal",pause:"Radyoyu duraklat",noAudio:"Ses önizlemeleri henüz bağlı değil"},
id:{player:"Pemutar MOCIFY Radio",prev:"Track sebelumnya",next:"Track berikutnya",play:"Putar radio",pause:"Jeda radio",noAudio:"Pratinjau audio belum terhubung"},
ja:{player:"MOCIFY Radio プレイヤー",prev:"前のトラック",next:"次のトラック",play:"ラジオを再生",pause:"ラジオを一時停止",noAudio:"音声プレビューはまだ接続されていません"},
ko:{player:"MOCIFY Radio 플레이어",prev:"이전 트랙",next:"다음 트랙",play:"라디오 재생",pause:"라디오 일시정지",noAudio:"오디오 미리보기가 아직 연결되지 않았습니다"},
hi:{player:"MOCIFY Radio प्लेयर",prev:"पिछला ट्रैक",next:"अगला ट्रैक",play:"रेडियो चलाएँ",pause:"रेडियो रोकें",noAudio:"ऑडियो प्रीव्यू अभी जुड़े नहीं हैं"}}as const;
export default function RadioClient(){const{locale}=useLanguage();const t=(copy as any)[locale]??copy.en;const { currentTrack, isPlaying, hasAudioSource, status, currentTime, queue, togglePlay, nextTrack, previousTrack } = useListenerPlayer();return <div className="mockup-radio-player" aria-label={t.player}><div className={`mockup-radio-cover ${currentTrack.art}`}/><div className="mockup-radio-track"><b>{currentTrack.title}</b><small>{currentTrack.artist}</small><span role="status">{hasAudioSource ? formatTime(currentTime) : status}</span></div><button type="button" className="mockup-radio-control" aria-label={t.prev} onClick={previousTrack} disabled={queue.length < 2}>◀</button><button type="button" className="mockup-radio-control main" aria-label={isPlaying?t.pause:t.play} title={!hasAudioSource?t.noAudio:undefined} onClick={togglePlay} disabled={!hasAudioSource}>{isPlaying?"Ⅱ":"▶"}</button><button type="button" className="mockup-radio-control" aria-label={t.next} onClick={nextTrack} disabled={queue.length < 2}>▶</button><div className="mockup-radio-volume" aria-hidden="true"/></div>}
